### ISSUE TITLE
Better Document SNI and PyOpenSSL Support

### ISSUE THREAD

**Issue by Lukasa** [requests/requests#1969]
It looks like the standard library [might start directing more people our way in order to get SNI on Python 2.7](http://bugs.python.org/issue5639#msg214170). This is great, but right now we don't really document it, and we don't test it. I think we should do both.

This means
- new CI environment that installs our SNI dependencies and actually tries to use it.
- better docs.

**Comment by sigmavirus24** [comment]
:+1:

**Comment by Lukasa** [comment]
No guarantees, actually, I've seen chats on Twitter that suggest that Nick Coghlan might be chatting with Christian and Alex about fixing 2.7. We're a bit in limbo here.

**Comment by athoik** [comment]
Until python 2.7 supports SNI, maybe we can make use of https://github.com/trevp/tlslite ?

**Comment by Lukasa** [comment]
We do support SNI. =) We just don't support it in an obvious way. Given the option between using pyOpenSSL and tlslite we're always going to choose pyOpenSSL. tlslite has very limited ciphersuite support and just generally lacks the features we need.

**Comment by glyph** [comment]
Suggestion: rather than documenting `pip install pyopenssl ndg-httpsclient pyasn1`, turn it into a setuptools extra so you can `pip install requests[sni]` and get those dependencies so you only have to remember that one string.  (I always forget `ndg-httpsclient`.)

**Comment by sigmavirus24** [comment]
@glyph there's a separate issue (#1995) for that. Feel free to ping Kenneth there.

**Comment by alex** [comment]
FWIW, it looks like the stdlib in 2.7 will support SNI (and a whole host of other things), just as soon as someone reviews and merges @dreid and my patch.

**Comment by Lukasa** [comment]
:cake:

**Comment by sigmavirus24** [comment]
If anyone picks this up, please also add documentation for `pip install requests[security]`.

**Comment by b4stien** [comment]
I can confirm that it's not obvious for newcomers (like me!) to realise we need to install extra packages for SNI support.

**Comment by alex** [comment]
We should also push people towards Python 2.7.9, which addresses this.

On Sun, Feb 15, 2015 at 5:14 PM, Bastien Gandouet notifications@github.com
wrote:

> I can confirm that it's not obvious for newcomers (like me!) to realise we
> need to install extra packages for SNI support.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kennethreitz/requests/issues/1969#issuecomment-74440187
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by glyph** [comment]
> We should also push people towards Python 2.7.9, which addresses this.

Definitely, but killing earlier versions will still take quite some time, so documenting what to do in the meanwhile is still important.

**Comment by WhyNotHugo** [comment]
I think this can be closed, since #2195 seems to resolve it?
