### ISSUE TITLE
Move utility functions from requests.utils to requests-toolbelt

### ISSUE THREAD

**Issue by sigmavirus24** [requests/requests#2266]
# Reasoning

requests is an _HTTP_ library, not an HTML library. Some of these utility functions are far more focused on HTML and a Response's body than on HTTP. With that said, they don't belong in requests proper. Instead they belong in a third-party library and currently the best place for that is requests-toolbelt.
# Path to removal

Step 1:
- [x] Add `DeprecationWarning`s to all of these functions in the very next possible release of requests (either 2.4.3 or 2.5.0) (See PR https://github.com/kennethreitz/requests/pull/2309)

Step 2:

Prior to releasing 3.0, remove the following functions and migrate them to [requests-toolbelt](/sigmavirus24/requests-toolbelt). Allow requests-toolbelt to release a version first and then release 3.0.
- [x] `get_encodings_from_content`
- [x] `get_unicode_from_response`
- [ ] more functions?

**Comment by kennethreitz** [comment]
+1000000

**Comment by untitaker** [comment]
Why `get_unicode_from_response`?

**Comment by sigmavirus24** [comment]
We already provide the unicode in the response as `r.text`.

**Comment by kennethreitz** [comment]
Back in the day, we had a function that would convert any Request object into a curl command string.

...lol

**Comment by sigmavirus24** [comment]
Yeah, people have recreated that time and again. That's not ending up in the toolbelt frankly. On the other hand, if someone wrote a function to convert it to an HTTPie command string... I might consider that ;)

**Comment by sigmavirus24** [comment]
I think we can close this.
