### ISSUE TITLE
Extensions Guide

### ISSUE THREAD

**Issue by kennethreitz** [requests/requests#3134]
We currently have a list of _recommended_ (e.g. softly endorsed) extensions in the documentation (this needs some love). 

In addition, we should have a document that lists all community extensions, grouped by category.

---

Prompted by https://github.com/kennethreitz/requests/issues/3131

**Comment by kennethreitz** [comment]
Feel free to paste extensions you're aware of here.

**Comment by sigmavirus24** [comment]
PyPI catalogs these for us see:
- [searching for requests on PyPI](https://pypi.python.org/pypi?:action=search&term=requests&submit=search)
- [searching for requests on Warehouse](https://pypi.io/search/?q=requests)

Judging by the number of these packages, I'm not sure we want to keep a list of _every_ community extension. That seems... extreme.

**Comment by kennethreitz** [comment]
Yeah, no API clients (maybe one or two exceptions; doubtful). They have to look at least somewhat generally useful.

**Comment by kennethreitz** [comment]
I forsee this being a fairly large list, intended to be for discovering new toys, or looking for something specific via ctrl-f.

**Comment by auvipy** [comment]
you can start with some well used n promising ones first
