### ISSUE TITLE
get request with a payload param key having a '-' dash in the word, does not work

### ISSUE THREAD

**Issue by mnikhil-git** [requests/requests#3564]
example:
url_payload = { 'username': user, 'severity': 'critical', 'job-type': 'spark', 'finished-time-begin': START_TIME, 'finished-time-end': FINISH_TIME}

results in non-200 code while testing with curl or postman or a browser with a same parameter with '-' in it, yields correct results.
Any clues?

**Comment by sigmavirus24** [comment]
We need a lot more details about the actual code before being able to be helpful.
