### ISSUE TITLE
Drop 2.6 support

### ISSUE THREAD

**Issue by Lukasa** [requests/requests#3928]
Our main dependent that still supports 2.6, pip, has just dropped support (pypa/pip#4343). We are now free to do the same.

**Comment by kennethreitz** [comment]
let's do this in 3.0.

**Comment by sigmavirus24** [comment]
@kennethreitz perfectly reasonable to do it with 3.0

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
i think this is a bit of a political statement, but a good one.

**Comment by nateprewitt** [comment]
With #4118 merged into the 3.0.0 branch, I think we can consider this resolved. Python 2.6 support will be removed in that release. Thanks @hobarrera!

**Comment by kennethreitz** [comment]
✨🍰✨
