### ISSUE TITLE
remove 301 redirect cache

### ISSUE THREAD

**Issue by kennethreitz** [requests/requests#4055]
it's not thread-safe, it's problematic, and it's just not the best of ideas. 

-----------

I'm assigning this to myself, but anyone can feel free to take this on if they're in the mood!

Just comment here when you start working on it, if so!

**Comment by sigmavirus24** [comment]
I thought we'd already removed this for 3.0?

**Comment by Lukasa** [comment]
I think @kennethreitz has OK'd removing it for 2.x too.

**Comment by kennethreitz** [comment]
Yeah, I'm personally fine with that.

**Comment by bcongdon** [comment]
I opened a PR for this issue. (#4100)

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by ericfrederich** [comment]
@kennethreitz 

How is it not threadsafe?

This `RecentlyUsedContainer` seems to be threadsafe. 
 The implementation uses `threading.RLock` [see source](https://github.com/urllib3/urllib3/blob/master/src/urllib3/_collections.py)

Even if the redirect cache was just a Python dictionary it would be threadsafe... right?

https://docs.python.org/3/glossary.html#term-global-interpreter-lock

> The mechanism used by the CPython interpreter to assure that only one thread executes Python bytecode at a time. This simplifies the CPython implementation by making the object model (including critical built-in types such as dict) implicitly safe against concurrent access.
