### ISSUE TITLE
Since 2.17.1, urllib3 is no longer in requests.packages

### ISSUE THREAD

**Issue by andy-maier** [requests/requests#4105]
The newly released v2.17.1 of the requests package introduced an issue in that `urllib3` is no longer in `requests.packages`:

```
python -c "import zhmcclient; print('Import: ok')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "zhmcclient/__init__.py", line 30, in <module>
    from ._session import *       # noqa: F401
  File "zhmcclient/_session.py", line 29, in <module>
    from requests.packages import urllib3
ImportError: cannot import name urllib3
```

Version 2.17.0 and before worked fine.

We circumvented this issue by fixing the version of requests to 2.17.0, for now.

## Expected Result

`urllib3` is again in `requests.packages`.

## Actual Result

`urllib3` is no longer in `requests.packages`.

## Reproduction Steps

```python
from requests.packages import urllib3
```

## System Information

This could be reproduced on Python 2.7, 3.4, 3.5, 3.6 and on all OS platforms that we test on (Ubuntu, OS-X and Windows).

**Comment by kennethreitz** [comment]
Closing for #4104
