### ISSUE TITLE
Installation fails on platforms without multiprocessing

### ISSUE THREAD

**Issue by cyberjacob** [requests/requests#4113]
On the latest version of requests in pypi, requests requires the multiprocessing module to install correctly, even though it is not used in the installation, only in the unit tests. This means it is no longer possible to install requests on platforms that lack multiprocessing support (such as Android or IoT devices)

## Expected Result

Requests is installed and available for use

## Actual Result

Installation fails with the following:

```
Downloading/unpacking requests
  Downloading requests-2.17.3.tar.gz (123Kb): 123Kb downloaded
  Running setup.py egg_info for package requests
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/build/requests/setup.py", line 11, in <module>
        from multiprocessing import cpu_count
    ImportError: No module named multiprocessing
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/build/requests/setup.py", line 11, in <module>

    from multiprocessing import cpu_count

ImportError: No module named multiprocessing

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /sdcard/com.hipipal.qpyplus/.pip/pip.log
```

## Reproduction Steps

From a platform without multiprocessing:

```
pip install requests
```

## System Information

For obvious reasons, requests.help is not available, but I've tried to piece together the information that it would produce:

- platform.system()   Linux
- platform.release()   3.14.29
- implementation     CPython
- implementation_version   2.7.2
- ssl.OPENSSL_VERSION_NUMBER   268443727L
- requests_version   2.17.3

**Comment by girlpunk** [comment]
Appears to be since e6e3589, I'll see if I can do a fix for it

**Comment by Lukasa** [comment]
Thanks for this report. It should be entirely possible to pull the multiprocessing import into a tighter scope.
