### ISSUE TITLE
TypeError when using a custom HTTPSConnectionPool

### ISSUE THREAD

**Issue by amatyukhin0** [requests/requests#4119]
An issue #4010 was closed, but this error
```python
TypeError: _new_pool() got an unexpected keyword argument 'request_context'
```
still appears in requests 2.17.3. Details are in the issue #4010.

**Comment by Lukasa** [comment]
@amatyukhin0 Did you read [this comment](https://github.com/requests/requests/issues/4010#issuecomment-300352930)? I believe it explains your concern.

**Comment by amatyukhin0** [comment]
@Lukasa Sorry, i was inattentive, it works after the fix.
