### ISSUE TITLE
chardet version check in >=2.16.0 is breaking our tox tests

### ISSUE THREAD

**Issue by cas--** [requests/requests#4125]
The latest update (2.16.0 and 2.17.3) to version check chardet has broken one of our sphinx docs tox tests on travis.

```
  File "/home/travis/build/cas--/Deluge/.tox/docs/local/lib/python2.7/site-packages/requests/__init__.py", line 66, in <module>

    major, minor, patch = chardet.__version__.split('.')[:3]

AttributeError: type object '__version__' has no attribute 'split'
```

I have no idea how/why this is occurring but it's your new code in `__init__.py` that is breaking when version checking chardet.

Commit that introduced the issue: 2b34880e2fa3fe6006bf64517e036f5ed74478d6

Full details of OS and versions: https://travis-ci.org/cas--/Deluge/jobs/239401586

**Comment by sigmavirus24** [comment]
Is this reproducible for you outside of Travis CI? I cannot reproduce it.

**Comment by nateprewitt** [comment]
@cas-- It looks like this is directly related to the [`conf.py`](https://github.com/deluge-torrent/deluge/blob/6743b0c813769bd1fd6e3b0c96e2f037adc78dd0/docs/source/conf.py) file in Deluge's `docs/source` directory. It's replacing `chardet` with a Mock object which has an attr `__version__` of type `type`. Are modern versions of `chardet` using C extensions? I can't seem to find anything that points to that, so I'm not sure why this extension is being mocked out.

**Comment by cas--** [comment]
So sorry, recently been dealing lots of failing tests due to module changes and completely forgot about mock in docs test!

**Comment by sigmavirus24** [comment]
> Are modern versions of chardet using C extensions?

To answer the question: No.

**Comment by nateprewitt** [comment]
@sigmavirus24 thanks! 😊

@cas-- No need to apologize, glad you got it worked out.
