### ISSUE TITLE
digest auth with netrc

### ISSUE THREAD

**Issue by PhilipStefanov** [requests/requests#4126]
According to the documentation:

netrc Authentication

If no authentication method is given with the auth argument, Requests will attempt to get the authentication credentials for the URL's hostname from the user's netrc file. The netrc file overrides raw HTTP authentication headers set with headers=.

If credentials for the hostname are found, the request is sent with HTTP Basic Auth.

How can i use then Digest with ~/.netrc ?

**Comment by Lukasa** [comment]
At this time Requests does not enable the use of Digest Auth with `~/.netrc`. This would be a feature worth having, though it's a difficult one to add because right now Requests does not have any kind of multi-auth support. The toolbelt does though.

**Comment by sigmavirus24** [comment]
@PhilipStefanov "the toolbelt" = https://github.com/requests/toolbelt. Feel free to move this issue over there. 😃
