### ISSUE TITLE
investigate pytest-timeout plugin

### ISSUE THREAD

**Issue by kennethreitz** [requests/requests#4128]
will increase the reliability of tests on windows, perhaps. 

- [ ] identify tests that hang on windows

https://pypi.python.org/pypi/pytest-timeout

**Comment by vikramcse** [comment]
I want to work on this issue! Can I take this issue as a beginner in OSS?

**Comment by sigmavirus24** [comment]
I don't think this will help much with the Windows tests. Thanks for the interest @vikramcse
