### ISSUE TITLE
why don't wrapper urllib3 LocationValueError("No host specified.")

### ISSUE THREAD

**Issue by dading** [requests/requests#4139]
Summary.

## Expected Result
i can import exception from requests.

## Actual Result

when i catch LocationValueError, i need import LocationValueError from urllib3.exceptions, not from requests....

## System Information

    $ python v2.7.0

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hey @dading, it looks like this may be a duplicate of #3220. Could you please provide some more information on when you're encountering this exception? Is it occurring with a specific domain, or is this failure periodic?

Could you also provide the version of Requests you're currently using? Thank you!

**Comment by dading** [comment]
I am wrong, thanks
