### ISSUE TITLE
No method to retrieve cookie object by name

### ISSUE THREAD

**Issue by lordjabez** [requests/requests#4142]
I would like to be able to get a cookie object out of the cookie jar by name and inspect its attributes (e.g. domain, expires, secure flag). My use case is a test script that ensures my webserver is configuring cookies properly.

I expect to have some kind of function like `get` that returns the whole cookie object, not just the value, but no function seems to exist.

## Reproduction Steps

```python
import requests
response = requests.get('http://google.com')
response.cookies.get('NID')  # Only returns cookie value
for c in response.cookies:
    print(c)  # c is entire cookie object
```

If this is a desired feature, I'd be happy to code it up myself. My suggestion is a simple `get_cookie` function, but am open to other ideas.

**Comment by Lukasa** [comment]
You're right, this is not a feature that exists currently. I don't think we want it though: I'm reluctant to expand `RequestsCookieJar` too far, especially when we have some pretty mixed (ie. negative) feelings about cookielib. My inclination is that the best thing to do is for you to write a helper function that iterates over the cookiejar and does the search by name (this is how `RequestsCookieJar.get` works).

**Comment by kennethreitz** [comment]
I agree, mostly because there's a possible future were were we remove Cookielib entirely from the equation, and want to keep it as abstract as possible.

**Comment by kennethreitz** [comment]
Thanks for the suggestion, though, @lordjabez! ✨🍰✨

**Comment by lordjabez** [comment]
A consideration for the future, however you decide to manage cookies, is the ability to inspect all cookie attributes, not just the value. This is a common use case for me writing automated tests to ensure web servers are doing the right things with their session cookies.

And thank _you_ for a fantastic library.
