### ISSUE TITLE
Urllib3 ConnectionError exception passing through requests API

### ISSUE THREAD

**Issue by aJetHorn** [requests/requests#4147]
I am using Requests Version: 2.11.1 catching all request exceptions like this:

except requests.exceptions.RequestException as e:
          logger.debug("%s", str(e))

However, this does not catch a NewConnectionError thrown by requests.packages.urllib3.connection.HTTPConnection

The full error statement is: 

ConnectionError: HTTPConnectionPool(host='REDACTED', port=27001): Max retries exceeded with url: /REDACTED (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x6bf5a50>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',))

Based off [https://github.com/requests/requests/issues/1572](https://github.com/requests/requests/issues/1572), it appears that all urllib3 exceptions should be caught by requests.exceptions.RequestException and that this falls into the category of an exception leak.

Full trace: 

Traceback (most recent call last):
 ...
 File "REDACTED/app/process.py", line 399, in REDACTED
   r = requests.post(url, data=json.dumps(payload), headers=headers)
 File "/usr/lib/python2.7/site-packages/requests/api.py", line 110, in post
   return request('post', url, data=data, json=json, **kwargs)
 File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
   return session.request(method=method, url=url, **kwargs)
 File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
   resp = self.send(prep, **send_kwargs)
 File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
   r = adapter.send(request, **kwargs)
 File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
   raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='REDACTED', port=27000): Max retries exceeded with url: REDACTED (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x6bf5a50>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',))

**Comment by nateprewitt** [comment]
Hey @aJetHorn, it looks like this is a `ConnectionError` wrapping a `NewConnectionError` in your traceback. The `ConnectionError` inherits from `RequestsException`, so it should be caught.  Do you have an example domain you're experiencing this on?

This is the repro I used to test this:

```python
import requests

try:
    requests.get('https://not_a_real_domain.com')
except requests.exceptions.RequestException as e:
    print('exception caught', e)
```

It is a slightly different underlying error message, but the same type of Exception object.

**Comment by aJetHorn** [comment]
@nateprewitt I just realized that the environment where I was running this had not been updated to handle all exceptions (the try catch wasn't what I mistakenly stated above). Sorry about that.

**Comment by nateprewitt** [comment]
No worries, glad you got it sorted 😊

**Comment by jbauson** [comment]
@aJetHorn how did you exactly solved this issue? I am having the same problem.
