### ISSUE TITLE
http response is not decoded when encoding is missing from the response header, even if decode_unicode is set

### ISSUE THREAD

**Issue by mx237** [requests/requests#4148]
Platform: Win7 Pro SP1
Python: 3.6.1 64 bit
package:
requests==2.17.3
requests-file==1.4.2
requests-ftp==0.3.1
urllib3==1.21.1

When I try to request [http://www.google.com/finance/historical?q=NASDAQ%3AAAPL&startdate=Jun+1%2C+2017&enddate=Jun+2%2C+2017&output=csv](http://www.google.com/finance/historical?q=NASDAQ%3AAAPL&startdate=Jun+1%2C+2017&enddate=Jun+2%2C+2017&output=csv), the http response has no encoding info. However, the response is utf-8 encoded with utf-8 BOM.

Even if I set `decode_unicode=True` in `iter_content`, it does not try to decode the content and simply gives the raw bytes.

I wonder if this is a designed feature or could you add a feature to peek the few bytes in the beginning and try to guess the encoding from BOM when `decode_unicode` is set and the encoding is not available?

Thank you very much!

**Comment by Lukasa** [comment]
This behaviour of `iter_content` is unfortunately well-known: see #3574 for a PR that fixed this issue as reported in #3359 and #3481.  Unfortunately, to resolve it we have to turn this into an error condition, which is a breaking change and so this change is not making it into the v2 series: it'll land in v3.

To work around the problem, you can set the encoding yourself via `response.encoding`:

```python
response.encoding = 'utf-8'
```

Sorry we can't do more to help!

**Comment by mongarneb** [comment]
hola

**Comment by mongarneb** [comment]
hola

**Comment by mongarneb** [comment]
prueba de json
