### ISSUE TITLE
Cannot find reference 'urllib3' in packages.py

### ISSUE THREAD

**Issue by arthur17** [requests/requests#4149]
**Summary**.

Can not find urllib3 when using latest `PyCharm` and `requests` from versions 2.17.1 to 2.17.3

**What you expected.**

Expected `urllib3` to be found on `packages.py`

**What happened instead.**

![image](https://user-images.githubusercontent.com/26851112/26999613-a60370ce-4d63-11e7-8e2a-9f5261b7e667.png)

**Steps to reproduce**

+ Open (or create) any project in PyCharm
+ You can use the systems Python or a virtualenv
+ Install requests 2.17.3 (by using pip on terminal or by going to project interpreter settings)
+ Try to import urllib3
  + `from requests.packages.urllib3.exceptions import InsecureRequestWarning`

Maybe it has something to do with db076c098e962b5096f6b0c77d69b80396228464?

**System Information**

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.3"
  },
  "platform": {
    "release": "4.4.0-79-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.17.3"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": false
}
```

**Comment by Lukasa** [comment]
Hrm. So PyCharm is wrong here: this path does exist. But it's added dynamically, which may cause PyCharm some problems. I recommend opening a bug report with PyCharm.

**Comment by malavancs** [comment]
Copy the urllib3 folder into the package. because it doesn't install it dependency itself.

**Comment by rakesh2k10** [comment]
try installing urllib3 and then.
from urllib3.exceptions import InsecureRequestWarning
