### ISSUE TITLE
Multiple values in a single param as list

### ISSUE THREAD

**Issue by mayukh18** [requests/requests#4155]
I don't know if this has already been discussed earlier.

### What happens now

`GET "https://graph.facebook.com/v2.6/USER_ID?fields=first_name,last_name,gender&access_token=PAGE_ACCESS_TOKEN"`

is done with the help using requests by

`r = requests.get('https://graph.facebook.com/v2.6/' + USER_ID, params={
                'fields': 'first_name,last_name,gender',
                'access_token': PAGE_ACCESS_TOKEN )})`

### Preferred way of doing it

`r = requests.get('https://graph.facebook.com/v2.6/' + USER_ID, params={
                'fields': [ 'first_name', 'last_name', 'gender'],
                'access_token': PAGE_ACCESS_TOKEN )})`

I feel this will be a more pythonic way to do it if that is even a word. When I was working on it I found the existing solution not so user friendly. I would love to take this up and contribute.

**Comment by Lukasa** [comment]
Thanks for your enthusiasm! Unfortunately there is no standard for handling a list of values, and multiple possible ways to represent them. For this reason Requests largely remains neutral on them: if you pass us a list, we'll just encode them all separately. Given that we have a pre-existing behaviour for this syntax, I don't think we can accept this kind of change.
