### ISSUE TITLE
http2 protocol support?

### ISSUE THREAD

**Issue by kgk** [requests/requests#4156]
Some servers are moving  http2 for better performance.   
  
What would it take to have that in the requests library?

**Comment by kennethreitz** [comment]
In the works!

**Comment by kennethreitz** [comment]
ETA: 1.5 years-ish.

**Comment by Lukasa** [comment]
The TL;DR here is that HTTP/2 is appallingly unpleasant to work with from synchronous codebases like Requests. This means to add support requires substantial architectural changes.
