### ISSUE TITLE
    with requests.get(url, stream=True) as r AttributeError('__exit__',)

### ISSUE THREAD

**Issue by beruhan** [requests/requests#4157]
I read the python-requests doc,[http://docs.python-requests.org/en/master/user/advanced/#body-content-workflow](url),I run the example`with requests.get('http://httpbin.org/get', stream=True) as r:
    pass`,I get the exception 'AttributeError('__exit__',)',is the example left closing clause?

**Comment by Lukasa** [comment]
Sorry, no: that feature is going to be released today.
