### ISSUE TITLE
requests 2.18.0  installation with easy-install 

### ISSUE THREAD

**Issue by papachoco** [requests/requests#4159]
Summary.
For legacy (easy-install / buildout) installations the egg and / or source for requests 2.18.0 is not being pick up. Not sure if this an issue with pypi since the source is listed

e.g.

easy_install-2.7 -U requests==2.18.0
Searching for requests==2.18.0
Reading https://pypi.python.org/simple/requests/
No local packages or working download links found for requests==2.18.0
error: Could not find suitable distribution for Requirement.parse('requests==2.18.0')

Thanks

Carlos

**Comment by Lukasa** [comment]
This seems like it's an issue with PyPI caching. @dstufft?

**Comment by papachoco** [comment]
pip works fine

**Comment by sigmavirus24** [comment]
This isn't an issue with Requests. The source distribution is on PyPI: https://pypi.org/project/requests/2.18.0/#files

I genuinely think this is an issue with setuptools and this hasn't ben updated in over a month. I'm closing this.
