### ISSUE TITLE
Content-Length header issue

### ISSUE THREAD

**Issue by Lsup27** [requests/requests#4161]
I have used remove property for the header property Content-Length as I dont want to have the response from the backend truncated. But curious enough when I call the API, sometimes the content-length property is removed and sometimes it is not. Why is this behavior observed. I included the remove property line after the call is made to backend and we get the response.

**Comment by Lukasa** [comment]
Can you show me some sample code and what you expect to see, vs what you actually see?

**Comment by sigmavirus24** [comment]
This hasn't been updated in well over a month. Without further detail, there's nothing we can do. I'm closing this for now but if you have the extra detail that can help us help you, then we'll reopen it.
