### ISSUE TITLE
can't POST

### ISSUE THREAD

**Issue by ash73** [requests/requests#4163]
Trying to use python requests to http post.
r = requests.post(address, data=payload)
r.url only shows the url, not the payload.
My php page is returning an error, but I can't see the full url passed to it.
How do I inspect the WHOLE url posted to the web server to debug it?

Whereas
r = requests.get(...)
r.url returns the entire url including the payload.

TIA.

**Comment by Lukasa** [comment]
In requests, `data` *always* adds data to the request body, and `params` always adds data to the request URL. If you want data in the URL you *must* use `params`, and if you want it in the body you *must* use `data`. This is unrelated to the request verb you're using.

**Comment by ash73** [comment]
Many thanks - resolved.
