### ISSUE TITLE
Unable to trigger a Jenkins build remotely with a file parameter using python requests

### ISSUE THREAD

**Issue by ankuagar** [requests/requests#4166]
I was trying to trigger a Jenkins build remotely with a file parameter using python requests

## Expected Result

I was expecting the remote job to be triggered with the contents of file.log saved in ${WORKSPACE}/files/abc.zip

## Actual Result
This code triggers a build. 

## What happened instead.
But the file /some/file/path/file.log is not posted to the Jenkins job.
The contents are not available in ${WORKSPACE}/files/abc.zip

## Reproduction Steps

```
python
import requests
url = 'myurl/buildWithParameters'
data = {'Jenkins-Crumb': '8f4d0320c0982763098571789b2b65ec', 'token': 'mytoken'}
filepath='/some/file/path/file.log'
files = {'file': ('files/abc.zip', open(filepath, 'rb')) }
r = requests.post(url, data=data, files=files)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.3"
  },
  "cryptography": {
    "version": "1.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.10"
  },
  "platform": {
    "release": "16.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010006f",
    "version": "17.0.0"
  },
  "requests": {
    "version": "2.17.3"
  },
  "system_ssl": {
    "version": "9081df"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Lukasa** [comment]
Do you have some indication of what the format of a successful request should be? It's hard to debug this without knowing that success looks like.

**Comment by ankuagar** [comment]
@Lukasa No sorry, I don't have format of a successful request.

**Comment by Lukasa** [comment]
In that case we can't really help you: if we don't know what you're trying to produce, we can't tell you how to use Requests to do it. Sorry!
