### ISSUE TITLE
Make alternate json libraries a hook to replace builtin json.

### ISSUE THREAD

**Issue by Dude-X** [requests/requests#4169]
Currently, in the `_compat.py` module, if you have simplejson installed, it will use that over the standard built-in json.

This works fine in Python 2, since simplejson is typically faster than the built in json package, and it is more 'correct' in handling JSON.

However, in Python 3, simplejson is slower than the built in json package especially for smaller json payloads, which is probably a typical use case with the requests library. Even though simplejson handles various JSON strings better than the built in JSON, those cases are not typical.

I would like to see a hook that allows a user to opt to use a alternate JSON library so that a user can specify if they want to use rapidjson, ujson, simpleson for the `response.json()` decoding.

**Comment by Lukasa** [comment]
The 3.0 release of Requests will remove the use of simplejson in favour of the stdlib module. Until that time, however, we cannot safely remove the option to use simplejson, as it would potentially represent a subtle backward-incompatible dependency change.

I don't really see any reason to allow more general hooking of JSON libraries: ultimately, additional JSON features are not really a thing I think we need to support.

Thanks for your report!

**Comment by SharpEdgeMarshall** [comment]
What's the breaking change?

**Comment by isaulv** [comment]
@SharpEdgeMarshall replacing the dependency on simplejson in https://github.com/psf/requests/blob/bbc3d43522bcb1363050557655508d66bfebcfcf/requests/compat.py#L28

I still think you should be able to replace the JSON library used.
