### ISSUE TITLE
sessions.py merge_setting(...)

### ISSUE THREAD

**Issue by gfplk** [requests/requests#4177]
Hello, my head HTTP request is sent, although is ordered, but this is out of order, the anti spider detection target site to request the head not in the same order will ban off request. After finally put the code here watching, actually can bypass anti crawler mechanism.

 你好，我发送http请求时的头部，虽然是有序的，但是这里是顺序被打乱，目标网站的反爬虫检测到请求头的顺序不一样就会ban掉请求. 最后把这里的代码注视之后，居然可以绕过反爬虫机制。

   # merged_setting = dict_class(to_key_val_list(session_setting))
   # merged_setting.update(to_key_val_list(request_setting))

**Comment by Lukasa** [comment]
Requests does not provide any ability to mandate ordering of HTTP headers. If that's a thing you need to do you'll need to drop down to a lower-level library.
