### ISSUE TITLE
RFE: partial_updates 

### ISSUE THREAD

**Issue by sergiomb2** [requests/requests#4181]
http://docs.python-requests.org/en/master/api/  already have it

**Comment by sigmavirus24** [comment]
Hi @sergiomb2,

Thanks for opening an issue. There's very little detail here about what issues or enhancements you are seeing or would like to see. As such, I'm closing this until that detail presents itself in one way or another.

Cheers,
Ian

**Comment by sergiomb2** [comment]
OK , link  [1] fooled me because only show (...) HTTP request types: PUT, DELETE, HEAD and OPTIONS , should also refer to patch method ... 

[1]
http://docs.python-requests.org/en/master/user/quickstart/#make-a-request

**Comment by StewPoll** [comment]
You can use any method verb you want with requests.

http://docs.python-requests.org/en/master/user/advanced/#custom-verbs
