### ISSUE TITLE
Allow hooking (de)compression

### ISSUE THREAD

**Issue by KOLANICH** [requests/requests#4184]
I have searched the repo for strings "gzip", "zlib" and have not found this packages imported. It seems that (de)compression is done implicitly somewhere. It poses some problems, for example if I want to add support of some compression/decompression algo like brotli.

## Expected Result

There should be a dict mapping compression algo name from http headers to (de)compresssion function.

## Actual Result

I have not found such one.

**Comment by Lukasa** [comment]
I don't think there is any need for this. I think it'll be sufficient to wrap the `read` function in the response object to achieve this goal.
