### ISSUE TITLE
Sometimes it happens, What can I sove this? Thanks a lot.

### ISSUE THREAD

**Issue by liangrengongzuoshi** [requests/requests#4189]
HTTPConnectionPool(host='xxx', port=xxx): Max retries exceeded with url: /Upload/Processing.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f79f9c9c1d0>: Failed to establish a new connection: [Errno 113] No route to host',))
Traceback (most recent call last):
  File "/data/apps/browser_9090/UuwiseUtil.py", line 131, in uploadPic
    resp = requests.post("http://" + self.UPLOAD_SERVER + "/Upload/Processing.aspx", data=data , files=files, headers=headers)
  File "/home/python27/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/python27/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/python27/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/python27/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/python27/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='xxx', port=xxx): Max retries exceeded with url: /Upload/Processing.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f79f9c9c1d0>: Failed to establish a new connection: [Errno 113] No route to host',))

**Comment by Lukasa** [comment]
This error is systemic: it means that when we attempted to connect to the IP address returned by DNS, the operating system told us it didn't know how to get there. This is not really a thing we can fix: when you get this error, you should just retry.

**Comment by liangrengongzuoshi** [comment]
Thanks for your answer.

It just happens sometimes.
And sometimes It throws exceptions below, Whether it is related to HTTP persistent connection？

ConnectionError: HTTPConnectionPool(host='xxx', port=xxx): Max retries exceeded with url: xxx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2f225a1b50>: Failed to establish a new connection: [Errno 111] Connection refused',))

Thanks~

**Comment by Lukasa** [comment]
It's not related to the persistent connections: that's caused by the remote peer refusing a TCP connection when we attempt to connect to it.

**Comment by liangrengongzuoshi** [comment]
OK, I got it , thanks a lot.
