### ISSUE TITLE
requests 2.18.1 with proxies throw SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

### ISSUE THREAD

**Issue by chen2aaron** [requests/requests#4193]
Hi,
When I use requests 2.18.1 with proxies, it throw SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

## Scenario 1

Debian GNU/Linux 8
Python 3.6.1
OpenSSL 1.0.1t 

pip list:

certifi (2017.4.17)
cryptography (2.0)
ndg-httpsclient (0.4.2)
pip (9.0.1)
pyasn1 (0.2.3)
pycparser (2.18)
pyldap (2.4.35.1)
pyOpenSSL (17.1.0)
PySocks (1.6.7)
requests (2.18.1)
requests-toolbelt (0.8.0)
setuptools (36.0.1)
six (1.10.0)
urllib3 (1.21.1)

My code:
```
import requests
proxies={'http':'socks5://127.0.0.1:8388', 'https': 'socks5://127.0.0.1:8388'}
r=requests.get('https://twitter.com',proxies=proxies)
```

Error message:
```
  File "/venv/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

```

When I degrade requests=2.11.1
The error gone.

## Scenario 2

MacOS Sierra
Python 3.6.1
OpenSSL 1.0.2l 

pip list:
The same as above

It also return the same error message 

And also when I degrade requests=2.11.1
The error gone.

I want to know what the reason is, help me~ thanks

**Comment by Lukasa** [comment]
This is almost certainly because we removed 3DES from our default cipher suite list. Try following the steps [in this blog post](https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/) to see if that resolves your issue.

**Comment by chen2aaron** [comment]
Thanks, it resolved my problem
