### ISSUE TITLE
new relase of requests since urllib3 dep was bumped to 1.22

### ISSUE THREAD

**Issue by papachoco** [requests/requests#4197]
Could we get a new release of requests that uses urllib3 >=1.22 as dependency. Latest released version of requests has urllib3<1.22,>=1.21.1

Thanks

Carlos

**Comment by Lukasa** [comment]
See #4196. A new release is planned.

**Comment by dmtucker** [comment]
@Lukasa Is there a time frame on that release? Just looking for a ballpark, if possible.

**Comment by Lukasa** [comment]
@dmtucker Yeah, there is: early next week, realistically. We try to release on Tuesdays or Wednesdays to allow ops teams time to roll out releases (for boring compliance reasons some places have to take manual steps to handle updates of critical dependencies like us), so expect next Tuesday.

**Comment by dmtucker** [comment]
Perfect, thank you!
