### ISSUE TITLE
Cookies lost after redirect

### ISSUE THREAD

**Issue by HynekBlaha** [requests/requests#4200]
After redirect, the JSESSIONID cookie is lost.

## Expected Result
Status code: 200
Cookies: 
**JSESSIONID=91D71FBD2086F8FD1968001E6EECC9E5 for jizdenky.regiojet.cz,** 
currency=CZK for jizdenky.regiojet.cz
locale=cs for jizdenky.regiojet.cz

Status code: 302
Cookies: 
**JSESSIONID=91D71FBD2086F8FD1968001E6EECC9E5 for jizdenky.regiojet.cz,** 
currency=CZK for jizdenky.regiojet.cz
locale=cs for jizdenky.regiojet.cz

## Actual Result

Status code: 200
Cookies: 
currency=CZK for jizdenky.regiojet.cz
locale=cs for jizdenky.regiojet.cz

Status code: 302
Cookies: 
**JSESSIONID=91D71FBD2086F8FD1968001E6EECC9E5 for jizdenky.regiojet.cz,** 
currency=CZK for jizdenky.regiojet.cz
locale=cs for jizdenky.regiojet.cz

## Reproduction Steps

```python
import requests

        # Without redirect I get session id cookie
        with requests.Session() as s:
            s = s.get("https://jizdenky.regiojet.cz/Login", allow_redirects=False)
            print("Status code: {0}".format(s.status_code))
            print("Cookies: {0}".format(s.cookies))

        # With redirect I don't get session id cookie
        with requests.Session() as s:
            s = s.get("https://jizdenky.regiojet.cz/Login")
            print("Status code: {0}".format(s.status_code))
            print("Cookies: {0}".format(s.cookies))
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.8.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.1"
  },
  "platform": {
    "release": "16.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "100020bf",
    "version": "17.0.0"
  },
  "requests": {
    "version": "2.18.1"
  },
  "system_ssl": {
    "version": "100020cf"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
@HynekBlaha why did you close this?

**Comment by HynekBlaha** [comment]
My mistake. Didn't read doc enough. 
requests.cookies return cookies of the last response. 
Cookie was already used in the second request header. Everything is ok.
