### ISSUE TITLE
request not return in time

### ISSUE THREAD

**Issue by zjbzju** [requests/requests#4202]
I'm using request('POST', url, data=data) to access a 4 layer SLB. I found that some of requests delayed for about 2s. 

The tcp packets (dumped using tcpdump) shows that the packets are really received from SLB, but request doesn't returned to the caller. Does anyone have any idea about it?

BTW: my requests lib version is 2.12.4

**Comment by sigmavirus24** [comment]
@zjbzju could you provide more information, including the operating system, whether or not TLS is involved, what versions of openssl you have installed and are using, what you mean by `4 layer SLB`, and perhaps even the `tcpdump` itself.

**Comment by sigmavirus24** [comment]
Closing since no new information has been supplied to provide additional assistance.
