### ISSUE TITLE
requests is asking for urllib3 1.21.1, when 1.22 is on pypi

### ISSUE THREAD

**Issue by mtdeguzis** [requests/requests#4203]
Summary.

## Expected Result

requests is asking for urllib3 1.21.1, when 1.22 is on pypi. If pip/setuptools pulls the latest version of urllib3, you will not be able to run setup.py here.

## Actual Result

```'
Error: Couldn't find a distribution for 'urllib3<1.22,>=1.21.1'
```

## Reproduction Steps

* install latest urllib3
* run setup.py

**Comment by Lukasa** [comment]
A new release is coming tomorrow to resolve this.
