### ISSUE TITLE
Requests not working with Mac osx 10.11 Python-3 

### ISSUE THREAD

**Issue by paul93065** [requests/requests#4205]
Environment is Max OS-X 10.11, fully updated.
Python 3.6.2
Requests:
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
urllib3<1.23,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
 idna<2.6,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages 
certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages

Any get requests called from Python3 fails:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
More detail in attached file.
[Python3Requests.txt](https://github.com/requests/requests/files/1177297/Python3Requests.txt)

**Comment by Lukasa** [comment]
This seems to be a problem with your Python installation. It appears that this would happen with any TLS connection. How did you get your Python 3?

**Comment by paul93065** [comment]
Hello Lukasa,
Installed a package from Python.org
https://www.python.org/downloads/release/python-362/
The problem seems particular to OSX 10-11. Works OK on 10.10, same package install for Python 3.
I have to use Python 3 as I'm also using PyQt5 which only works on P3

**Comment by Lukasa** [comment]
Ok, I think this makes this a bug with your Python. You may need to report this to the python-dev team at bugs.python.org.

**Comment by paul93065** [comment]
Ok Thanks!
