### ISSUE TITLE
`requests.exceptions.*` do not inherit from Python's own specific exceptions.

### ISSUE THREAD

**Issue by StyXman** [requests/requests#4208]
Several `Exceptions` in https://github.com/requests/requests/blob/master/requests/exceptions.py inherit (indirectly) from `IOError`, but not from other Python exception. Two I can easily see are `ConnectionError` (see https://docs.python.org/3/library/exceptions.html#ConnectionError) and `TimeoutError`. 

It might make sense to inherit from those too. If you think it doesn't, just close the Issue.

**Comment by Lukasa** [comment]
I don't think it does at this time; while we're keeping compatibility across Python 2 and 3 it is probably not worth attempting to build complex exception hierarchies on different versions. For now, I think it's fine as-is. 

Thanks for the suggestion!
