### ISSUE TITLE
SSLError -> ConnectionError in 2.18.2: intended?

### ISSUE THREAD

**Issue by simon-weber** [requests/requests#4209]
My dev builds started failing after 2.18.2 was released (they purposefully run on the latest releases to flush out problems). They work on 2.18.1.

It looks like the cause is a minor breaking change: in at least my particular situation, an SSLError has changed to ConnectionError.

I can update my tests to look for ConnectionError instead, but I figured I'd check first to see if this behavior is intended.

## Expected Result

Getting `https://wrong.host.badssl.com` raises SSLError.

## Actual Result

Getting `https://wrong.host.badssl.com` raises ConnectionError, mentioning SSLError as the cause.

## Reproduction Steps

```
# starting with 2.18.1...
$ python -c 'import requests; requests.get("https://wrong.host.badssl.com")'
Traceback (most recent call last):
...
requests.exceptions.SSLError: hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'

$ pip install --upgrade requests
Collecting requests
...
Successfully installed requests-2.18.2 urllib3-1.22

$ python -c 'import requests; requests.get("https://wrong.host.badssl.com")'
Traceback (most recent call last):
...
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wrong.host.badssl.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'",),))
```

In case it's helpful, here's an example build: https://travis-ci.org/simon-weber/gmusicapi/jobs/248191438.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": "1.4"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.11"
  }, 
  "platform": {
    "release": "4.4.2ph+", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "1000204f", 
    "version": "16.0.0"
  }, 
  "requests": {
    "version": "2.18.2"
  }, 
  "system_ssl": {
    "version": "1000207f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": true
}
```

**Comment by Lukasa** [comment]
Hrm, this breaking change happened because we made urllib3 retry on `SSLError`. In this case I think we need to add some custom code to Requests to make this work a bit better, namely by throwing SSLError again. Good catch!

**Comment by simon-weber** [comment]
Thanks!
