### ISSUE TITLE
multiline header should be supported!

### ISSUE THREAD

**Issue by dotpot** [requests/requests#4216]
Summary.
2.11 version introduced this change:
- Reject header values that contain leading whitespace or newline characters to
reduce risk of header smuggling.

BUT, as per standard https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2 It whould be possible to have multiline headers.

f.ex. I need to attach a certificate via request header (currently I just mock the header validation method).

## Expected Result
support multiline header.

## Actual Result
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: X-CERTIFICATE

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Lukasa** [comment]
Multiline headers *should not* be supported. RFC 2616 is not the HTTP specification anymore: the relevant one is RFC 7230. 

[Here](https://tools.ietf.org/html/rfc7230#section-3.2.4) is the relevant part:

> Historically, HTTP header field values could be extended over multiple lines by preceding each extra line with at least one space or horizontal tab (obs-fold).  This specification deprecates such line folding except within the message/http media type (Section 8.3.1).  A sender MUST NOT generate a message that includes line folding (i.e., that has any field-value that contains a match to the obs-fold rule) unless the message is intended for packaging within the message/http media type.

There is no plan to add this support. Even if we did, the new line characters are not semantic in the header and get stripped for processing, so they're ill-suited to your use case. You need to come up with a different method of sending that cert.
