### ISSUE TITLE
support idna 2.6

### ISSUE THREAD

**Issue by cjw296** [requests/requests#4222]
idna 2.6 has been released, so the constraint in setup.py is now blowing up:

```
pkg_resources.ContextualVersionConflict: (idna 2.6 (.../ve/lib/python2.7/site-packages), Requirement.parse('idna<2.6,>=2.5'), set(['requests']))
```

**Comment by Lukasa** [comment]
Hang on, why is that constraint exploding? 2.5 should satisfy the requirement.

**Comment by cjw296** [comment]
My guess something is installing it earlier in the build chain, and pip isn't clever enough to downgrade to 2.5 once 2.6 is installed.

Is there a problem with 2.6 that makes it backwards incompatible?

**Comment by Lukasa** [comment]
We don't know at this time: we began with very tight pins because we only unvendored the package a few months ago and so didn't want to run the risk of accidental breakage. We need to get a feel for what the actual compatibility structure is here.

In the short term, you can resolve your problem by using `requirements.txt` or similar to pin the `idna` version. In the longer term, we can aim to get a Requests patch that widens the pin.

**Comment by cjw296** [comment]
Thanks for the quick turnaround!

**Comment by amalakar** [comment]
Is there any plan for releasing a new version with this fix? That would be really helpful.

**Comment by Lukasa** [comment]
Yes, next week.

**Comment by lasote** [comment]
The same is starting to happen with idna 2.7 ~~because cryptography requires idna 2.7~~
I still don't know why pip is resolving idna 2.7, cryptography is not requiring 2.7

**Comment by danielpza** [comment]
I have a similar issue but with version 2.10:

```
error: idna 2.10 is installed but idna<2.9,>=2.5 is required by {'requests'}
```

**Comment by eitimittal** [comment]
> I have a similar issue but with version 2.10:
> 
> ```
> error: idna 2.10 is installed but idna<2.9,>=2.5 is required by {'requests'}
> ```
Me too, have you found a way out of it?

**Comment by eitimittal** [comment]
> I have a similar issue but with version 2.10:
> 
> ```
> error: idna 2.10 is installed but idna<2.9,>=2.5 is required by {'requests'}
> ```

Me too, getting the same error while deploying my project on scrapy cloud. Have you found a solution yet?
Error:
requests 2.25.1 has requirement idna<3,>=2.5, but you have idna 2.1.
Warning: Pip checks failed, please fix the conflicts.
{"message": "Dependencies check exit code: 1", "details": "Pip checks failed, please fix the conflicts", "error": "requirements_error"}
{"status": "error", "message": "Requirements error"}
