### ISSUE TITLE
Please support idna 2.6

### ISSUE THREAD

**Issue by stephanema** [requests/requests#4228]
Today I updated idna to 2.6 then I tried to install requests 2.18.3 and got an
error that dna must be <2.6.

Would be nice it you support the actual idna package,
thanks.

System: python 3.6.2 64 bit on windows7 64 bit

**Comment by Lukasa** [comment]
*Please* check recent issues. You'll find that two have been opened before you, both saying that we have updated the pin in the current master and will be releasing an update next week.

**Comment by stephanema** [comment]
Oops sorry, I didn't realize it (I use seldomly the github issues pages)
