### ISSUE TITLE
Please bump certifi to 2017.7.27.1

### ISSUE THREAD

**Issue by mtdeguzis** [requests/requests#4230]
Cannot build requests via pip/buildout/easy_install due to old specified certifi

## Expected Result

Buildout succeeds

## Actual Result

```
Got pykerberos 1.1.14.
Picked: pykerberos = 1.1.14
Getting required 'certifi>=2017.4.17'
  required by requests 2.18.3.
We have no distributions for certifi that satisfies 'certifi>=2017.4.17'.
```

## Reproduction Steps

Build requests via pip/pypi fetches

See: https://pypi.python.org/pypi/certifi

**Comment by Lukasa** [comment]
This bug report makes no sense. Our certifi requirement specifies only a *minimum* version. You should be able to install alongside any newer certifi without difficulty.
