### ISSUE TITLE
Posting Multiselect Forms

### ISSUE THREAD

**Issue by kianhean** [requests/requests#4232]
Please help me. I am trying to automate a post from a form. The multiselect portion is throwing me off. the below doesnt work. quite sure the way i am posting the mutliselect portion ('session_id') is wrong 

## Expected Result

Expected this to work

![expect](https://user-images.githubusercontent.com/5037305/29161100-7afff488-7de7-11e7-8f21-fc407e1cf9e0.PNG)

    payload2 = {'from_date': '2017-08-17', 'fac_id': '10', 
                'par_fac_id': '1', 'book_purpose': '0', 'session_id': ['50']}
    p2 = s.post(new_url, data=payload2)

session_id comes from a multiselect form.

## Actual Result

The request command was not accepted by the server

**Comment by kianhean** [comment]
i found the answer!

Sorry about that please close.

payload2 = {'from_date': '2017-08-17', 'fac_id': '10', 
            'par_fac_id': '1', 'book_purpose': '0', 'session_id[]': ['50']}

**Comment by Lukasa** [comment]
Well done finding the answer!

**Comment by sigmavirus24** [comment]
The [toolbelt](/requests/toolbelt) also provides a function to do this for you. Glad you found the answer on your own though. 🎉

**Comment by kianhean** [comment]
Thanks all. Somehow it wasn't that easy to find
