### ISSUE TITLE
Add header name to InvalidHeader exception message

### ISSUE THREAD

**Issue by lsmithso** [requests/requests#4239]
requests.get('http://example.com', headers={'foo': 1})
requests.exceptions.InvalidHeader: Header value 1 must be of type str or bytes, not <class 'int'>

It would be good to add the name of the bad header to make it easier
to track this down in large bodies of code. Something like:

requests.exceptions.InvalidHeader: Header foo value 1 must be of type str or bytes, not <class 'int'>

Thanks.

Summary.

## Expected Result

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).e

**Comment by Lukasa** [comment]
Agreed, this seems like a useful enhancement.

**Comment by mgasvoda** [comment]
I'd like to help on this one if that's alright, I can have a pull request in shortly.

**Comment by lsmithso** [comment]
Hi: Please be my guest.

mgasvoda writes:
 > I'd like to help on this one if that's alright, I can have a pull request in shortly.
 > 
 > -- 
 > You are receiving this because you authored the thread.
 > Reply to this email directly or view it on GitHub:
 > https://github.com/requests/requests/issues/4239#issuecomment-321900563

-- 
Les Smithson
