### ISSUE TITLE
.get params is ignored if there is a double slash in the url

### ISSUE THREAD

**Issue by robertlayton** [requests/requests#4242]
Summary.

The behaviour doesn't seem to be consistent everywhere, but when I run the following with Python 3 / requests 2.14-2, params is ignored in the double-slash case:

```python
import requests

response = requests.get("https://erikberg.com/nba/results/atlanta-hawks.json", params={"season": "2014"}, verify=False)
print("No double slashes", response.url)

response2 = requests.get("https://erikberg.com//nba/results/atlanta-hawks.json", params={"season": "2014"}, verify=False)
print("With double slashes", response2.url)
```

## Expected Result

`response2.url` should be the same as `response.url`:

No double slashes https://erikberg.com/nba/results/atlanta-hawks.json?season=2014
With double slashes https://erikberg.com/nba/results/atlanta-hawks.json?season=2014

## Actual Result

`response2.url` was the raw url, with no params attached to it:

No double slashes https://erikberg.com/nba/results/atlanta-hawks.json?season=2014
With double slashes https://erikberg.com/nba/results/atlanta-hawks.json

## Reproduction Steps

```python
import requests

response = requests.get("https://erikberg.com/nba/results/atlanta-hawks.json", params={"season": "2014"}, verify=False)
print("No double slashes", response.url)

response2 = requests.get("https://erikberg.com//nba/results/atlanta-hawks.json", params={"season": "2014"}, verify=False)
print("With double slashes", response2.url)

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.8.1"
  },
  "idna": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.1"
  },
  "platform": {
    "release": "3.18.0-14875-g438cb8ab27c6",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "100020bf",
    "version": "17.0.0"
  },
  "requests": {
    "version": "2.18.3"
  },
  "system_ssl": {
    "version": "100020cf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

**Comment by Lukasa** [comment]
Did you say this happens with Requests 2.14? Why does your help output identify the Requests version as 2.18.3?

**Comment by MichaelAnckaert** [comment]
The case above seems to be very specific, testing with any other url that has a double slash in it seems to work. 

    >>> response = requests.get("https://www.sinax.be/blog", params={"season": "2014"})
    >>> response.url
    'https://www.sinax.be/blog/?season=2014'
    >>> response = requests.get("https://www.sinax.be//blog", params={"season": "2014"})
    >>> response.url
    'https://www.sinax.be/blog/?season=2014'


Note: reproduced with requests version 2.18.4

**Comment by Jesse-Bakker** [comment]
This is not an issue with requests, but with the website. 
What happens is that the site redirects the url `https://erikberg.com//nba/results/atlanta-hawks.json?season=2014` to `https://erikberg.com/nba/results/atlanta-hawks.json`.

**Comment by kennethreitz** [comment]
Indeed, check `response.history` for more information.

**Comment by robertlayton** [comment]
Thanks for investigating and sorry for the hassle!
