### ISSUE TITLE
requests-http-signature

### ISSUE THREAD

**Issue by kislyuk** [requests/requests#4249]
I have published a new PyPI module, https://github.com/kislyuk/requests-http-signature, to implement the IETF draft for HTTP signatures (https://tools.ietf.org/html/draft-cavage-http-signatures-07). This draft RFC formalizes the use of symmetric (HMAC-SHA1, HMAC-SHA256) and asymmetric (RSA-SHA256, ECDSA-SHA256) message signing in HTTP.

Is there interest in bringing this module under the requests organization?

**Comment by Lukasa** [comment]
Very nice work! For the moment I think it would be best to keep it separate; this ensures we don't bottleneck on the limited resources of the Requests team. However, if there is significant uptake and you no longer have the resources to do solo maintainership please let us know and we'll re-evaluate.

**Comment by kislyuk** [comment]
For reference, here is an issue tracking HTTP Signatures standard finalization: https://github.com/w3c-dvcg/http-signatures/issues/1

**Comment by kennethreitz** [comment]
We should have a document in our docs for modules like this

**Comment by kennethreitz** [comment]
https://github.com/requests/requests/issues/4267
