### ISSUE TITLE
Error with relative url

### ISSUE THREAD

**Issue by marcoshipe** [requests/requests#4250]
I have a problem with a specific relative URL, but I suppose it's not the only one.
When i do:
`print(requests.get('http://www.resultados.gob.ar/escrutinio/dat99/../../javascript/mun.js')`

## Expected Result

The content of the js

## Actual Result

> b'File not found."'

## Reproduction Steps

```python
import requests
print(requests.get('http://www.resultados.gob.ar/escrutinio/dat99/../../javascript/mun.js').content)
```

## Other info
With other links in the same web, it not happened, for example:
`print(requests.get('http://www.resultados.gob.ar/escrutinio/dat99/../dat01/DDN01001A.htm').content)`

If i do it with no relative path:
`print(requests.get('http://www.resultados.gob.ar/javascript/mun.js').content`
is ok either

And in firefox or chrome the same relative url is ok too

So i think it can be the '.js' at the end in combination with relative urls?

## System Information
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.2"
  },
  "platform": {
    "release": "4.10.0-32-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by Lukasa** [comment]
Yeah, it's currently the case that Requests does not clean up relative URLs. This is not planned to change in the short term: eventually we'll want to add a dependency on a proper URL handling module in urllib3, but until that work gets done we can't resolve this. 

If you're interested in doing that work please open an issue on urllib3 and we can discuss steps forward.
