### ISSUE TITLE
Configuration to follow redirect method after http redirect

### ISSUE THREAD

**Issue by raja-gola** [requests/requests#4251]
Summary.
Basically HTTP 301 redirection replaces POST method with a GET.
More Info: https://softwareengineering.stackexchange.com/questions/99894/why-doesnt-http-have-post-redirect
Need an config option in python requests to override this behavior and follow redirect method after http redirection.

Thanks
Raja

**Comment by Lukasa** [comment]
For overriding our redirect logic we have a coarse grained switch: `allow_redirecte`, which can be set to `False`. Failing that, more modern versions of Requests have a `Session.rebuild_method` method that can be overridden to change the behaviour to get what you're looking for. 

There is no plan to add an additional config option for this behaviour.
