### ISSUE TITLE
Git Clone Fails

### ISSUE THREAD

**Issue by evanshauser** [requests/requests#4254]
The repository does not clone, due to a bad commit. Let me know if I can do anything more to help!

## Expected Result

The repository should be cloned successfully with the command:

```
git clone git@github.com:requests/requests.git
```

## Actual Result

I get this message:

```
Cloning into 'requests'...
remote: Counting objects: 20967, done.
remote: Compressing objects: 100% (25/25), done.
error: object 5e6ecdad9f69b1ff789a17733b8edc6fd7091bd8: badTimezone: invalid author/committer line - bad time zone
fatal: Error in object
fatal: index-pack failed
```

## Reproduction Steps

run:

```
git clone git@github.com:requests/requests.git
```

**Comment by Lukasa** [comment]
Thanks for the report. This is a known problem: see #3088, #3008, and #2690 for previous discussions. The problem can be easily resolved on your end either by performing a shallow clone (if you don't need the history) or turning off the fsck timestamp check. This cannot be fixed without rewriting our history and causing *way* more problems that way than by just letting it sit.

**Comment by sigmavirus24** [comment]
Please, search open **and** closed issues before opening new ones in the future, @evanshauser
