### ISSUE TITLE
Requesting the ability to globally override the CA bundle path

### ISSUE THREAD

**Issue by wise0wl** [requests/requests#4257]
Currently, requests.certs.where() provides the path to the CA bundle by means of the certifi library.  While this is fine it presents issues for developers who are using third party libraries requiring the requests library in situations where they need to use a internal or self signed CA.

A method prescribing a global override for this CA bundle path as a first pass would be extremely helpful.  This method could be as easy as setting an environment variable, ie. CA_PATH=/path/to/ca/bundle.crt

**Comment by Lukasa** [comment]
Such an environment variable already exists: `REQUESTS_CA_BUNDLE`. I hope that helps!
