### ISSUE TITLE
tests are broken

### ISSUE THREAD

**Issue by ofek** [requests/requests#4259]
Specifically, this hangs https://github.com/requests/requests/blob/5dcbdb50fc9652cbeffeec22a21d1196e938bfca/tests/test_requests.py#L151

It can be seen in #4258 https://travis-ci.org/requests/requests/jobs/268764155

This occurs locally for me as well.

**Comment by kennethreitz** [comment]
I'm loving these new GitHub line previews.

**Comment by kennethreitz** [comment]
So fancy!

**Comment by Lukasa** [comment]
See #4261.
