### ISSUE TITLE
A problem with proxies parameters

### ISSUE THREAD

**Issue by SongJee** [requests/requests#4266]
I have a problem about proxies, when I was using ip agent
`requests.get('http://1212.ip138.com/ic.asp', headers=headers,proxies=pro, timeout=9)`
How can i know if I succeed to use the ip agent, sometimes the result from the url is my own ip instead of the ip in proxies.Does that means the ip in proxies is useless?
Thx for your reply.

**Comment by Lukasa** [comment]
Without seeing how your proxies are configured I have no idea if that will work or not.

**Comment by nateprewitt** [comment]
Given that we haven't seen in additional information to help debug this, I'm going to close this out. Feel free to ping if you have more information @SongJee.
