### ISSUE TITLE
Document Community Extensions

### ISSUE THREAD

**Issue by kennethreitz** [requests/requests#4267]
Exceptional:

- https://github.com/requests/toolbelt
- https://github.com/ionrock/cachecontrol

Note-worthy:

- https://github.com/kislyuk/requests-http-signature
- https://github.com/ross/requests-futures
- https://pypi.python.org/pypi/requests-mock
- https://vcrpy.readthedocs.io/en/latest/
- https://pypi.python.org/pypi/requests-cache

Participation award:

- https://github.com/twisted/treq (maybe https://pypi.python.org/pypi/requests-twisted/0.1.1 instead?)
- https://github.com/getsentry/responses (maybe not mention)
- https://httpie.org

Let's list others.

**Comment by sigmavirus24** [comment]
I would say `cachecontrol` falls under `Exceptional`. `responses` isn't an extension and if it is then there are far better ones out there.

**Comment by kennethreitz** [comment]
@sigmavirus24 thanks for the feedback :)

**Comment by kennethreitz** [comment]
updated

**Comment by vhawk19** [comment]
@kennethreitz  i would like to work on this. Should they be documented in the ReadMe.md file?

**Comment by sigmavirus24** [comment]
I think these are already done, actually, @vhawk19 http://docs.python-requests.org/en/latest/community/recommended/
