### ISSUE TITLE
Handling Multiple Sessions with requests.Session()

### ISSUE THREAD

**Issue by Seykotron** [requests/requests#4269]
Hello, Im trying to make multiple Sessions at once, I need to login multiple users into my webpage, but when instantiating requests.Session() it seems like the session is shared, and if I call requests.Session() again there I have the same cookies and the same headers that I stored in the previus object.

Sorry for my english, Im Spanish

Thank you!

**Comment by Lukasa** [comment]
The `Session` object is not shared: it's a class object, it cannot be shared. Can you provide some sample code that reproduces the issue?

**Comment by Seykotron** [comment]
Wow so fast Lukasa! Thank you for answering, I solved my problen not using Session, instead getting the cookiejar and store it into my class variable.

Anyway My code was like the next one:

```python
class User:
    def __init__(self,username, password,session=None):
        self.username = username
        self.password = password
        self.session= session or requests.Session()
    def login(self):
        result = self.session.post( "url", data={"username":self.username, "password": self.password} )
        print( "%s: %s" % (self.username,result.text) )

if __name__ == "__main__":
    u = User( "pepe", "asdf" )
    u.login()
    u2 = User("juan", "asdf" )
    u2.login()
```

And it the first time return the data concerning the user "pepe", but the second time, it returns two times the data concerning "juan".

I dont know if I explain myself :/ my english are very bad :P 

Anyway I solve my problem using cookiejar :) 

Very Very thank you anyway :D

**Comment by Lukasa** [comment]
Happy to be of some service! I'm glad you solved your problem. :smile:

**Comment by Seykotron** [comment]
I found the error, I was instantiatting the logger twice xD :P haha! :)
