### ISSUE TITLE
Requests tries to resolve `user:pass@host` on OS X

### ISSUE THREAD

**Issue by mattbennett** [requests/requests#4275]
If you have proxy bypass settings, requests tries to resolve the hostname before stripping credentials from the URL.

It looks like this happens because the [proxy bypass](https://github.com/requests/requests/blob/4bda7b66e7ece5be51b459edd046a70915b4792c/requests/utils.py#L78) logic is called before [urldefragauth](https://github.com/requests/requests/blob/b9638ec7be9134786e28684ca17f3d161297ac5e/requests/utils.py#L879) strips the credentials from the URL.

## Expected Result

Should not try to resolve an invalid hostname.

## Actual Result

DNS resolution for `user:pass@host` is made:

![screenshot 2017-09-05 11 04 11](https://user-images.githubusercontent.com/107611/30056277-0279af7a-922a-11e7-9223-ef66b5bd2af6.png)

## Reproduction Steps

On OS X with proxy bypass hosts configured:

![screenshot 2017-09-04 18 08 46](https://user-images.githubusercontent.com/107611/30056416-864198b8-922a-11e7-9448-f2e702c95927.png)

```python
import requests
requests.get('http://user:pass@localhost')
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.10"
  },
  "platform": {
    "release": "15.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020cf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by Lukasa** [comment]
So this seems to be an issue with macOS specifically, and in particular how it handles proxy bypass. We should probably strip the auth from the host before we bypass.
