### ISSUE TITLE
Bad name in the request: not a legal PLSQL identifer

### ISSUE THREAD

**Issue by Lolerla** [requests/requests#4289]
Hello guys, relatively new to python. Met with this error while trying to use request POST to extra information. Header and data are directly copied and paste from using google chrome when the POST is made. Couldn't identify any wrong with the formData. Am i missing out on something?

> import requests

> formData = {
>     'acadsem':'2017_1',
>     'r_course_yr':'ACC%3BGB%3B2%3BF',
>    ' r_subj_code':'Enter+Keywords+or+Course+Code',
>     'boption':'CLoad',
>     'semester':'1',
>     'acadsem':'2017_1'
>     }
> url = "'www.example.com/"
> 
> response  = requests.post(url, data = formData)
>    
> print(response.content)

**Comment by sigmavirus24** [comment]
You're passing urlencoded form data to our `data` parameter which will in turn urlencode it. You will want to decode `r_course_yr`'s value.

In the future, please use StackOverflow for questions of this type.
