### ISSUE TITLE
Still SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",) after enable 3DES

### ISSUE THREAD

**Issue by wmj1238** [requests/requests#4296]
Summary.
When I use requests to crawl a url ,the cmd always show me bad handshake,and after I refer other solution,it doesn't make sense.The real reason is that the module requests cann't support 3DES

## Expected Result

The requests support 3DES algorithm.
## Actual Result

For the url using 3DES,the requests module cann't work.

## Reproduction Steps

```
import requests
response=requests.get("https://supply.zte.com.cn/UI/Web/Application/kxscm/kxsup_manager/Portal/index.aspx ")```

## System Information
```
   Windows10 python3.6<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Lukasa** [comment]
This is intentional: 3DES is insecure for bulk data transfer, and so we disabled it to help protect our users. You can re-enable it for specific hosts as [shown here](https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/).
