### ISSUE TITLE
response(200) always need to wait for 120 seconds

### ISSUE THREAD

**Issue by etiaxie** [requests/requests#4300]
i use requests to send a HTTP request like this:
![image](https://user-images.githubusercontent.com/10825713/30731867-746a995c-9fa2-11e7-81d1-5b8ddd6e24bc.png)
and the response like this:
![image](https://user-images.githubusercontent.com/10825713/30731883-866ddd58-9fa2-11e7-90f7-99eea26bd2b8.png)
and i always need to wait for 120s to get the response

**Comment by Lukasa** [comment]
The remote server is sending a HTTP response with no Content-length or Transfer-encoding chunked. This means that the server is saying "the request body is complete when I close the connection". Requests is doing the right thing and waiting for that connection close before it returns. The server should set content-length.
