### ISSUE TITLE
Attempting to send struct packed binary data over requests

### ISSUE THREAD

**Issue by realoriginal** [requests/requests#4304]
I attempted to send struct-packed binary data over your lib, failed for me. I placed it in the cookie header, as what im doing requires it to be.

For some strange reason, it said connection refused

**Comment by sigmavirus24** [comment]
This does not seem to be a bug in requests, but instead a question better suited for [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests). Please instead direct this and all future questions there.
