### ISSUE TITLE
request.get params change

### ISSUE THREAD

**Issue by limTeTE** [requests/requests#4308]
I use` requests.get` to do some web scraping and one key of params, which shows below, changes strangely. 
Where is the "25" from? Does it come from the sys environment or language set? Thanks ~

## Expected Result

the `r.url` is
```
 'http://www.shufaziti.com/?char=%E7%BA%B5&size=96&forecolor=0&backcolor=0&radio=0'
```
## Actual Result

the `r.url` is 
```
'http://www.shufaziti.com/?char=%25E7%25BA%25B5&size=96&forecolor=0&backcolor=0&radio=0'
```
## Reproduction Steps

```python
import requests
web = "http://www.shufaziti.com/"
key = {"zong":"%E7%BA%B5", "xia":"%E4%B8%8B"}
shkey = {"char": key["zong"], "size": "96", "forecolor": "0",  "backcolor": "0", "radio": "0"}
r = requests.get(web, params=shkey)
```

## System Information
```
Windows10(64-bit)
Python 3.6.2 | Anaconda custom(64-bit)
Requests version: 2.14.2
```

**Comment by sigmavirus24** [comment]
When you specify `params=` we URL encode the parameters to ensure they're safe. You already have them url-encoded, however, so we're urlencoding the `%` signs as `%25` to make them urlsafe. I can't recall if we've changed this behaviour in newer versions (I think we merely ensure we don't encode something we've already encoded) but you can fix this now by unencoding those parameters yourself before passing them to us.

Cheers,
Ian

**Comment by kalinlau** [comment]
@sigmavirus24 Thanks, and btw how to unencoding by hand?

**Comment by sigmavirus24** [comment]
@limTeTE google `urlquote` and `unquote` with the version of Python you're using.
