### ISSUE TITLE
SSLError: SOCKSHTTPSConnectionPool(host='www.google.com', port=443)

### ISSUE THREAD

**Issue by wkatios** [requests/requests#4310]
Open a new issue is to facilitate the view, because   #4272 too long.
maybe it can help other people

we know uses socks5 need install 
`pip install requests[socks]`

when i use
`pip install --upgrade requests[socks]`

```
import reqeusts
proxies = {'http': 'socks5://127.0.0.1:1080', 'https': 'socks5://127.0.0.1:1080'}
r= requests.get(url,proxies=proxies)
```
failed

`SSLError: SOCKSHTTPSConnectionPool(host='www.google.com', port=443)......`

I use 
`pip install -U requests[socks]==2.12.0`

it works,not error infonation.

**Comment by JianPeng20** [comment]
I meet the same error today. Oddly, the error didn't appear when I setup the same programe tomorrow.

**Comment by sigmavirus24** [comment]
Please provide us with the output of

```
python -m requests.help
```

If that is unavailable on your version of Requests please provide some basic information about your system (Python version, operating system, etc).

**Comment by sigmavirus24** [comment]
See also https://github.com/requests/requests/issues/4272#issuecomment-345642450, try using `socks5h` instead of `socks5`

**Comment by nateprewitt** [comment]
This does appear to be related to incorrect use of the socks5 vs socks5h scheme. Since we haven't had a response to the requested information in a few months, I'm closing this out. Please feel free to reopen if you have more information. Thanks!

**Comment by Harrypotterrrr** [comment]
> See also [#4272 (comment)](https://github.com/psf/requests/issues/4272#issuecomment-345642450), try using `socks5h` instead of `socks5`

wow thanks!
