### ISSUE TITLE
Connecting from HTTPAdapter: Forbidden: Access is denied

### ISSUE THREAD

**Issue by edsonitk** [requests/requests#4312]
I'm trying to connect with certificate via HTTPAdapter, but the server always returns me error: 403 - Forbidden: Access is denied. This is the code:

```
class DESAdapter (HTTPAdapter):
    def __init __ (self, cert=None, key=None):
    
        self.cert_file = cert
        self.key_file = key
        super (DESAdapter, self) .__ init __ ()

    def init_poolmanager (self, connections, maxsize, block = False):
        self.poolmanager = poolmanager.PoolManager (
            num_pools = connections, maxsize = maxsize,
            block = block,
            cert_file = self.cert_file,
            key_file = self.key_file)

con = requests.Session ()
Adapter = DESAdapter (cert = certi, key = key)
con.mount (self.url, Adapter)
res = con.post ('url', data = 'xml_soap', verify = False, headers = 'header')
```

If you try without `HTTPAdapter()`, as the code below, then it works:

```
res = requests.post ('url', data = 'xml_soap', cert = (cert_path, key_path)
                            verify = False, headers = 'header')
```

**Comment by sigmavirus24** [comment]
Please provide us with the output of

```
python -m requests.help
```

If that is unavailable on your version of Requests please provide some basic information about your system (Python version, operating system, etc).

**Comment by edsonitk** [comment]
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.7.1"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.10"
  },
  "platform": {
    "release": "XP",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "100020af",
    "version": "16.2.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1000201f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}

**Comment by sireistwa** [comment]
Hi,
I am having the same problem with HTTPAdapter.
Forbidden: Access is denied

**Comment by sigmavirus24** [comment]
Hi there! Upon furthur review of this issue, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
