### ISSUE TITLE
In reponse, jQuery****({...});

### ISSUE THREAD

**Issue by kimyoungjin06** [requests/requests#4314]
Summary.

## Expected Result
I expected to return this form.

{"success":true,"code":"1000",...}

## Actual Result
I return this form with request.get()

jQuery1708155690935019391_1506579003758({"success":true,"code":"1000",...});
## Reproduction Steps

```python
url = 'https://apis.naver.com/commentBox/cbox/web_naver_list_jsonp.json?ticket=news&templateId=default_society&pool=cbox5&_callback=jQuery1708155690935019391_1506579003758&lang=ko&country=&objectId=news032%2C0002793071&categoryId=&pageSize=20&indexSize=10&groupId=&listType=OBJECT&page=1&initialize=true&userType=&useAltSort=true&replyPageSize=20&moveTo=&sort=favorite&includeAllStatus=true&_=1506579003809'

header = {
    "Referer": 'http://www.naver.com' # The referer means my access was from this referer. In this case, referer can be any site from naver
}
res = rq.get(url, headers = header)

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.9"
  },
  "idna": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.2"
  },
  "platform": {
    "release": "4.4.0-51-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "100020bf",
    "version": "17.2.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020cf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
@kimyoungjin06, the endpoint you're hitting seems to be returning exactly what you're asking for, a JSON dataset wrapped in a callback function (`jQuery1708155690935019391_1506579003758`) which you have declared in the URL parameters. You'll receive the same result if you perform this request with another tool like curl.

I'm closing this since it's not a Requests issue.
