### ISSUE TITLE
SSL Proxy Support

### ISSUE THREAD

**Issue by clusby** [requests/requests#4319]
When accessing HTTPS urls via an NTLM proxy, the get request fails with a request.exceptions.ProxyError

I believe this is because the hook to use requests-ntlm isn't dispatched when performing the SSL tunnel. That is, a socket error is thrown when I get a 407 in httplib._tunnel().

Are there any plans to support https queries using a proxy auth extension?

## Expected Result

HTTPS NTLM requests should authenticate on the proxy and get the external site.

## Actual Result

A request.exceptions.ProxyError is thrown

## Reproduction Steps

```python
import requests
from requests_ntlm import HttpNtlmAuth

session = requests.Session()
session.auth = HttpNtlmAuth(user, pass)
session.proxies = {'http': 'http://ntlm-proxy:8080', 'https': 'http://ntlm-proxy:8080'}
resp = session.get('https://httpbin.org/get')

# resp.status_code should = 200, however received 407
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.6"
  },
  "platform": {
    "release": "2008ServerR2",
    "system": "Windows",
  },
  "pyOpenSSL": {
    "openssl_version": "1010006f",
    "version": "17.0.0"
  },
  "requests": {
    "version": "2.17.3"
  },
  "system_ssl": {
    "version": "90819f"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": true
}
```

**Comment by Lukasa** [comment]
Requests-NTLM is a separate project from Requests: please raise this issue on that repository.

**Comment by clusby** [comment]
Sure - I think this may involve both projects though. 

The exception is thrown within sessions.py:
```python
# Send the request
r = adapter.send(request, **kwargs)
```

Within send(), the SSL tunnel is attempted - and reaches down into httplib._tunnel()
```python
def _tunnel(self):
    ...
    response = self.response_class(self.sock, strict = self.strict, method = self._method)
    (version, code, message) = response._read_status()
    
    if code != 200:
        self.close()
        raise socket.error("Tunnel connection failed: %d %s" % (code, message.strip)))
```
We would need the 407 handled here to handle custom authentication.
I think it would be an issue with ntlm, kerberos, etc, etc. tunnelling.

**Comment by Lukasa** [comment]
As a general rule no Requests sub-project handles authing on TLS tunnelling. This is ultimately because httplib simply doesn’t give us appropriate hooks to do so. 🙁

**Comment by clusby** [comment]
Yeh makes sense thanks @Lukasa . I'll take a look at monkeypatching or using pycurl instead. :-(

Does urllib3 v2 still have momentum?

**Comment by Lukasa** [comment]
Due to my job change it has less momentum than it did before. Hopefully I'll find some quiet time to take more of a run at it, or we'll decide to land it as-is.
