### ISSUE TITLE
Question: How to throttle bandwidth of a given REST call

### ISSUE THREAD

**Issue by paul-nelson-baker** [requests/requests#4330]
I'm transitively using Requests, by using [locustio](https://github.com/locustio/locust).

Basically, we're loadtesting a service that accepts file-uploads (pretty much just a vanilla POST request). We want to slow down the upload to resemble what a real user's bandwidth would look like. (For clarification, the machine that runs the test is high-powered to replicate a large number of users. This, however, has the trade off that a large file upload that a user normally performs takes seconds instead of minutes; which falsely tests the application we're hitting).

We're looking at systemically slowing the bandwidth of the machine itself to replicate what a user would see, but we want to know: is it possible to do this programmatically?

**Comment by sigmavirus24** [comment]
There is nothing built into requests to do this. Depending on how you're trying to upload files you can either implement a generator that sleeps the appropriate amount of time or a file-like object that sleeps the appropriate amount of time.

In the future, please ask questions on [StackOverflow](https://stackoverflow.com).

**Comment by nikole-dunixi** [comment]
@sigmavirus24 Thank you, and will do
