### ISSUE TITLE
Request blob:domain.com

### ISSUE THREAD

**Issue by SaadeMotion** [requests/requests#4334]
Summary.

## Expected Result

I want do download blob:domain.com files

## Actual Result

With Requests:
 `No connection adapters were found for 'blob:domain.com/aaaaa-bbbbbb-cccc'`
With python urllib2:
`<urlopen error unknown url type: blob>`

## Reproduction Steps

```python
import requests
requests.get('blob:domain.com/aaaaa-bbbbbb-cccc')
```

## System Information

    $ python -m requests.help

```
{                         
  "chardet": {            
    "version": "3.0.4"    
  },                      
  "cryptography": {       
    "version": ""         
  },                      
  "idna": {               
    "version": "2.6"      
  },                      
  "implementation": {     
    "name": "CPython",    
    "version": "2.7.14"   
  },                      
  "platform": {           
    "release": "10",      
    "system": "Windows"   
  },                      
  "pyOpenSSL": {          
    "openssl_version": "",
    "version": null       
  },                      
  "requests": {           
    "version": "2.18.4"   
  },                      
  "system_ssl": {         
    "version": "100020bf" 
  },                      
  "urllib3": {            
    "version": "1.22"     
  },                      
  "using_pyopenssl": false
}                         
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Lukasa** [comment]
Requests is a HTTP library, and so only supports HTTP schemed URLs. There will be no support added for other kinds.
