### ISSUE TITLE
ssl client certificate requests reponse status code is 400

### ISSUE THREAD

**Issue by hugoren** [requests/requests#4335]
Summary.
The server USES nginx to implement HTTPS
## Expected Result
ssl client certificate requests reponse status code is 400
What you expected.
Certificate request
## Actual Result
the nginx error is  21:unable to verify the first certificate
What happened instead.

## Reproduction Steps

```python
import requests
r = requests.get(url,
                 cert='0ea.pem'
                 )
print(r)
```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Lukasa** [comment]
Can you show us the contents of the .pem file please? Can you also provide the output of `python -m requests.help` as the template asked for?

**Comment by CipherChen** [comment]
From my test, I found that in ubuntu 14.04.3, this won't happened, but in ubuntu 16.04.1, 400 status code is replied when requesting HTTPS.
It's a clue, I haven't dig any deeper yet, but this may give you some hints.
