### ISSUE TITLE
Pylint can't import requests.packages.urllib3

### ISSUE THREAD

**Issue by shiftysymbol** [requests/requests#4336]
When I import anything from `requests.packages.urllib3`, `pylint` marks such lines as errors: `Unable to import '...' (import-error)`

## Reproduction Steps

```bash
virtualenv -p python3 test
source test/bin/activate

# taken from http://docs.python-requests.org/en/master/user/advanced/#example-specific-ssl-version
echo "from requests.packages.urllib3.poolmanager import PoolManager" > test.py

pip install requests==2.18.4
pip install pylint
pylint --errors-only test.py

************* Module test
E:  1, 0: Unable to import 'requests.packages.urllib3.poolmanager' (import-error)
```
This is only happening with requests>=2.16. Previous versions are fine.

I can see the same behaviour in Python 2.7 (I know, I know... :) )

## Expected Result

Ideally I would like `pylint` to be able to perform the import so it can use the collected information for further variable analysis.

That doesn't necessarily mean changing `requests`, I'm happy to change my code to solve this problem. For example importing "base" `urllib3` instead of the packaged one, although I don't know whether that has any consequences and is safe to do. I saw the comment in `packages.py` that the code is there for compatibility reasons but http://docs.python-requests.org is using it so I assumed that's still the canonical way.

Any recommendations/fixes?

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.3"
  },
  "platform": {
    "release": "4.10.0-35-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by Lukasa** [comment]
If you know that you’re using the most recent requests you can safely just use the base urllib3. That is my recommendation in this case.

**Comment by shiftysymbol** [comment]
Thanks for the recommendation! If it's official it might be worth updating the docs so users don't wonder about the packaged `urllib3`.

**Comment by nateprewitt** [comment]
@shiftysymbol, urllib3 is no longer packaged as of 2.16. We now have a file that points the namespace requests.packages.urllib3 to your currently installed version for backwards compatibility reasons.

**Comment by shiftysymbol** [comment]
Cheers @nateprewitt -- I simply wasn't sure how safe it was to use `urllib3` directly and whether it was the right thing to do since the docs don't mention it and examples still use the bundled `urllib3`. But then I saw comments in the source code so wanted to double check.
