### ISSUE TITLE
Issue with certs.where()

### ISSUE THREAD

**Issue by Downchuck** [requests/requests#4340]
I'm seeing a cascading failure from the certifi project with no particular way to override the behavior other than changing python code.

Would be nice to be able to at least supply an environment variable to override the CERTS path.

## Expected Result
A usable request object that validates over HTTPS.

## Actual Result

This is not a file, it's a location in a zip file
```
/tmp/spark-7b667869-6fa4-4a2d-af58-87f6218ce59f/userFiles-bc90eb3c-0796-4c83-844f-14333c8090b0/google-cloud-storage-py27-none-any.all.zip/certifi/cacert.pem
```
```
IOError: Could not find a suitable TLS CA certificate bundle, invalid path: /tmp/spark-7b667869-6fa4-4a2d-af58-87f6218ce59f/userFiles-bc90eb3c-0796-4c83-844f-14333c8090b0/google-cloud-storage-py27-none-any.all.zip/certifi/cacert.pem
```
## Reproduction Steps

Note, this is using PySpark

```python
sc.addPyFile("s3a://big-data-analytics-scratch-prod/project_mesoads/eggs/google-cloud-storage-py27-none-any.all.zip")

import requests
brokencrt = requests.utils.DEFAULT_CA_BUNDLE_PATH
print(brokencrt)
requests.get('https://google.com/')
```

## System Information
This is run via PySpark on Python 2.7 caused by certifi: https://github.com/certifi/certifi.io/issues/14

**Comment by Lukasa** [comment]
You can provide an environment variable: `REQUESTS_CA_BUNDLE`.
