### ISSUE TITLE
HTTP_PROXY/HTTPS_PROXY not used with urllib3

### ISSUE THREAD

**Issue by alexcchan** [requests/requests#4347]
It appears that environment variables `HTTP_PROXY` and `HTTPS_PROXY` as described here:

http://docs.python-requests.org/en/master/user/advanced/#proxies

are no longer effective, since requests uses urllib3 instead of urllib.

## Expected Result

```shell
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"

$ python
>>> import requests
>>> requests.get('http://example.org')
```

## Actual Result

`HTTP_PROXY` and `HTTPS_PROXY` not used.

## Reproduction Steps

```shell
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"

$ python
>>> import requests
>>> requests.get('http://example.org')
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": "2.1.1"
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.14"
  }, 
  "platform": {
    "release": "16.7.0", 
    "system": "Darwin"
  }, 
  "pyOpenSSL": {
    "openssl_version": "1010006f", 
    "version": "17.3.0"
  }, 
  "requests": {
    "version": "2.18.4"
  }, 
  "system_ssl": {
    "version": "100020cf"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Lukasa** [comment]
Request hasn’t used urllib in more than 5 years, and those environment variables have worked fine that entire time. What makes you think they don’t work?
