### ISSUE TITLE
TypeError: __str__ returned non-string (type Error)

### ISSUE THREAD

**Issue by PalashSharma15** [requests/requests#4348]
**Summary.**
I want to install arduino-sketch on my raspberry pi. I have python 3 and 2.7 already installed.
But while installing it with pip following error has been occurred...

## **Expected Result**
Successfully installed arduino-sketch
## **Actual Result**
/usr/local/bin/pip run on Mon Apr 10 02:00:33 2017
Downloading/unpacking arduino-sketch
  Getting page https://pypi.python.org/simple/arduino-sketch/
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundl$  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 694, in get_page
    req, link, "connection error: %s" % exc, url,
TypeError: __str__ returned non-string (type Error)

**Comment by PalashSharma15** [comment]
Okay guys I resolved the error.
The error was due to inaccurate date and time of Raspberry PI. To resolve date and time you can do this:

    sudo raspi-config
    Internationalization options
    Change Time Zone
    Select geographical area
    Select city or region
    Reboot your pi
OR you can manually correct time by:
sudo date -s "Mon Aug  12 20:14:11 UTC 2014"

**Comment by ghost** [comment]
@PalashSharma15  Since you have resolved the error, you can close this issue.

**Comment by PalashSharma15** [comment]
Thanks @lutzhorn and @nateprewitt..
I am a beginner to github and didn't checked out the close feature.
