### ISSUE TITLE
Postback woes

### ISSUE THREAD

**Issue by JohnCC330** [requests/requests#4351]
Summary.

When trying to simulate postBack messages in an ASP.NET system, I find that Requests quotes
spaces as '+', but the server seems to expect '%20'. I've ready quite a few posts on the 'net about this,
but no (more or less) elegant solution to solve this using Requests. I tried to convert quote the dict to a string 'manually' using `requests.utils.quote`, which works for the spaces, but this function does not quote '/', which seems to be expected by eg. `__VIEWSTATE`.

## Expected Result
A possibility to specify POST operations with %20 quoting

## Actual Result

POST is quoting with '+'

## Reproduction Steps

s = requests.session()
...
        testdata = {"name": "MARIA    "}

        self.s.post(LAST_MOV,
                    data = testdata)
...
Logged from wireshark:

(POST header mostly removed)
Content-Type: application/x-www-form-urlencoded
name=MARIA++++

## System Information

requests 2.13.0
python 3.6.0
Slackware 14 current

**Comment by ghost** [comment]
The [HTML RFC](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) says:

> Space characters are replaced by '+', and then reserved characters are escaped as described in [RFC1738], section 2.2: Non-alphanumeric characters are replaced by `%HH', a percent sign and two hexadecimal digits representing the ASCII code of the character.

So Requests is doing the right thing.

**Comment by sigmavirus24** [comment]
@lutzhorn I don't believe @JohnCC330 is requesting we change the behaviour here. I believe they're looking for help. That said, there's no explicit ask and this is not a Q&A forum.

A short answer, is to URL encode the data yourself using the stdlib.

```py
>>> urllib.parse.urlencode({b'name': b'MARIA    '}, quote_via=urllib.parse.quote)
'name=MARIA%20%20%20%20'
```

If you then pass that to us, e.g.,

```py
data = urllib.parse.urlencode({b'name': b'MARIA    '}, quote_via=urllib.parse.quote)
requests.post(LAST_MOV, data=data, headers={'Content-Type
: 'application/x-www-form-urlencoded'})
```

That should achieve what you want. Either way, the server you're talking to is not specification compliant (as @lutzhorn already mentioned) so your best bet is to handle the data yourself.

In the future, please direct all questions to [StackOverflow](https://stackoverflow.com)
