### ISSUE TITLE
POST with files and timeout does both?

### ISSUE THREAD

**Issue by arski** [requests/requests#4357]
Hi, im making a requests.post call with sometimes large files object and a 5s timeout. Im observing that even if the call does indeed raise a timeout exception, the full file still ends up being sent.. Somehow.

Is this intentional or are there any nuances to using timeout with files?

**Comment by Lukasa** [comment]
A timeout is a complex thing. In this case, the timeout is applied *per socket operation*. That means each send, regardless of how much data, and each read. 

In this case you are likely timing out on the read. That will lead to the behaviour you’re describing. 

If you want a total timeout you can arrange it, but it’s definitely tricky.

**Comment by arski** [comment]
Hi, so just to be clear, if uploading the file actually takes minutes, but the request is constantly sending sone data, would the timeout trigger, or does it see that data is being sent, so all is good?

**Comment by Lukasa** [comment]
So long as at least one byte reaches the wire per timeout interval, it would think all is good.
