### ISSUE TITLE
On Windows, getting wrong proxy settings from Windows registry

### ISSUE THREAD

**Issue by mingyuan-xia** [requests/requests#4373]
For some windows machines (not all), a confusing Windows registry key type (`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings \ ProxyEnable`) fails the following code in `requests/requests/utils.py`.

```
            proxyEnable = winreg.QueryValueEx(internetSettings,
                                              'ProxyEnable')[0]
            proxyOverride = winreg.QueryValueEx(internetSettings,
                                                'ProxyOverride')[0]
```
The case is if proxyEnable is a string , everything is fine. But `ProxyEnable` could be `REG_SZ` on some Windows machines (no idea why, but it happens). After user deletes this key or set if to `REG_DWORD 0x00000000(0)`, things get right. But I believe better type checks in requests will help.

First found: https://stackoverflow.com/questions/46260169/python-locationvalueerror-no-host-specified
Aggregated discussion: https://github.com/conda/conda/issues/3962

## Expected Result

Type checks. no failure for  `REG_SZ` values.

**Comment by Lukasa** [comment]
I'd be happy to merge a patch that resolves this issue.

**Comment by mingyuan-xia** [comment]
PR: https://github.com/requests/requests/pull/4377

**Comment by nehaljwani** [comment]
@mingyuan-xia Could you please open a PR with that patch? I'd really love to see that get fixed in the next release of requests.

**Comment by mingyuan-xia** [comment]
https://github.com/requests/requests/pull/4377
