### ISSUE TITLE
pyinstaller make a exe file which contain requests run failed on no requests' windows

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [requests/requests#4374]
Help me, I just being crazy....
My Pyinstaller version is 3.2.1, Python 2.7.13 and I make a exe which contain requests. But it can not run on other's windows whose without requests.
So, which version should I try?

**Comment by Lukasa** [comment]
I'm afraid this is an issue with PyInstaller, not Requests: we can't really help you with PyInstaller. You'll need to take this up with the developers of PyInstaller.
