### ISSUE TITLE
Handle HTTPDigestAuth requests that return stale=true

### ISSUE THREAD

**Issue by greeny88** [requests/requests#4375]
I'm using the requests library to communicate with a Wildfly management API. In one specific environment, I am getting sporadic 401 responses that include in the 'WWW-Authenticate' the 'stale=true' flag. My understanding of the spec on this header is that the server sees that the authentication is valid but the nonce is old so it sends a new nonce with the stale flag to signal that it wants you to try again with the newly returned nonce. 

My question is how do I do that with requests? It seems that if I can find a way to build the Authorization header I could manage sending the response myself. However, ideally, I would like to set a limit on the number of times that request would retry this with the new nonce but I don't see that this is an option. In fact, it appears it is currently limited to the 2 attempts (the original 401 and the following response). 

How do I go about handling this?

**Comment by Lukasa** [comment]
So the Requests standard Digest Handler does not handle any of this, so you'll need to write a custom auth handler. This is very straightforward, and you can use the DigestAuth handler in the repository as a jumping off point: take that code and make the edits you need.
