### ISSUE TITLE
How can I get session storage variable in Python requests library?

### ISSUE THREAD

**Issue by willowTank** [requests/requests#4383]
I want to get session storage variable when I call any url.
Best Regards

here is my code
```

> self.session = requests.Session()
> self.session.mount('https://', HTTPAdapter(max_retries=4))
> resp = self.session.get("https://m.betclic.it/sport/sportList/")

```
this is session storage when I visit this site
![uta](https://user-images.githubusercontent.com/24641385/32818822-82fd67e6-ca00-11e7-890b-9bdf2cfc88e2.png)

**Comment by sigmavirus24** [comment]
This isn't a bug or feature request and is therefore better suited to a question and answer site like [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests).
