### ISSUE TITLE
not able to extract key:value from Json 

### ISSUE THREAD

**Issue by rishi-pal** [requests/requests#4385]
I am able to get whole json data but not able to get specific key:values from json data (url). Have someone seen this issue ?

## Expected Result
Specific Key:Value Pair i.e ( ID : 123456)

What you expected.
I want to extract key-value from json data

## Actual Result
Getting below error

print (data["id"])
Traceback (most recent call last):
File "", line 1, in 
KeyError: 'id'
What happened instead.

## Reproduction Steps <code>

import urllib, json
import requests
from requests.auth import HTTPBasicAuth
url = requests.get('http://ac-infinibox10.com/api/rest/pools', auth=HTTPBasicAuth('test', 'test'))
data = url.json()

print(data) ###### this works

print (data['id']) ###### this does not works
==================
System information:
Python 2.7
RHEL 7

**Comment by adsahay** [comment]
Hi - can you print output of `print(data)` ?

**Comment by rishi-pal** [comment]
{u'metadata': {u'ready': True, u'number_of_objects': 3, u'pages_total': 1, u'page': 1, u'page_size': 50}, u'result': [{u'volumes_count': 1, u'updated_at': 1487594704819, u'max_extend': -1, u'allocated_physical_space': 10000007168, u'free_virtual_space': 99990000369664, u'id': 4880, u'reserved_capacity': 107374313472, u'filesystems_count': 0, u'ssd_enabled': True, u'snapshots_count': 0, u'state': u'NORMAL', u'free_physical_space': 69990000099328, u'entities_count': 1, u'owners': [], u'capacity_savings': 0, u'name': u'AMDC-IBOX04_AIX_Storage_Pool', u'virtual_capacity': 100000000376832, u'created_at': 1487594704819, u'filesystem_snapshots_count': 0, u'compression_enabled': True, u'physical_capacity_warning': 90, u'physical_capacity': 70000000106496, u'physical_capacity_critical': 95}, {u'volumes_count': 28, u'updated_at': 1508346569350, u'max_extend': -1, u'allocated_physical_space': 111404476229632, u'free_virtual_space': 78739426377728, u'id': 15285, u'reserved_capacity': 107374313472, u'filesystems_count': 0, u'ssd_enabled': True, u'snapshots_count': 0, u'state': u'NORMAL', u'free_physical_space': 88595524130816, u'entities_count': 28, u'owners': [],

**Comment by adsahay** [comment]
Try posting it in a code block - it has been clipped here.

**Comment by rishi-pal** [comment]
import urllib, json


import requests
from requests.auth import HTTPBasicAuth
url = requests.get('http://ac-infinibox10.com/api/rest/pools', auth=HTTPBasicAuth('test', 'test'))
data = url.json()
print(data)

print (data['id'])

**Comment by adsahay** [comment]
I feel your dictionary structure might be different from what you're expecting.

You can try: `print(data.keys())` - perhaps you need to access the `id` key at a different level.

**Comment by rishi-pal** [comment]
Thanks for you quick reply on the issue. I am new to python and need to write script to fetch set of information from json data.

I tried below command and I m getting output. How can I extract a specific data like free_physical_space=free_physical_space from json data ?

>>> print(data.keys())
[u'metadata', u'result', u'error']

**Comment by adsahay** [comment]
Maybe something like this:

```
for result in data['result']:
    print(result['free_physical_space'])
```

Please close this issue as it is not really a `requests` bug.

**Comment by rishi-pal** [comment]
Thank you so much!  It worked.
Closing the issue.
