### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './README.rst'

### ISSUE THREAD

**Issue by lvallejou85** [requests/requests#4388]
Summary.

## Expected Result

pip install request
Installed OK

## Actual Result

pip install request
Collecting request
  Using cached request-0.0.13.tar.gz
Collecting get (from request)
  Using cached get-0.0.21.tar.gz
Collecting post (from request)
  Using cached post-0.0.13.tar.gz
Collecting setupfiles (from request)
  Using cached setupfiles-0.0.50.tar.gz
Collecting query_string (from get->request)
  Using cached query_string-0.0.12.tar.gz
Collecting public (from query_string->get->request)
  Using cached public-0.0.41.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bex9djjl/public/setup.py", line 28, in <module>
        setup_cfg_data = read_configuration(path)
      File "/tmp/pip-build-bex9djjl/public/setup.py", line 23, in read_configuration
        val = open(val).read()
    FileNotFoundError: [Errno 2] No such file or directory: './README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bex9djjl/public/

What happened instead.

Library installation failed

## Reproduction Steps

```python
pip install request
```

## System Information

    $ python -m requests.help

```
No module named requests.help
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).
![selection_999 1555](https://user-images.githubusercontent.com/30954037/32990180-bca9465a-ccf2-11e7-8025-55fa1a7d985d.png)

![image](https://user-images.githubusercontent.com/30954037/32990178-b2fb6b88-ccf2-11e7-8882-71dcc56747e2.png)

**Comment by nateprewitt** [comment]
@lvallejou85 it looks like you're missing the final "s" in the package name in your install command. It should be `pip install requests`.
