### ISSUE TITLE
Quickstart guide is missing section on cookies.

### ISSUE THREAD

**Issue by eliothxchan** [requests/requests#4393]
The quickstart guide has a section for cookies in the table of contents, but there isn't actually anything there.

http://docs.python-requests.org/en/master/user/quickstart/#cookies

**Comment by nateprewitt** [comment]
@eliotxchan, is this happening consistently on page refreshes and across different browsers? I can access that page fine on multiple devices.

If it still isn't showing up, there's either a network or browser issue somewhere on your end.

**Comment by drpoggi** [comment]
Additionally, you can find the section on cookies here: https://github.com/requests/requests/blob/master/docs/user/quickstart.rst#cookies

**Comment by eliothxchan** [comment]
Was actually my ad blocker blocking that. Very odd.
