### ISSUE TITLE
Get error "requests.exceptions.ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))"

### ISSUE THREAD

**Issue by thanhmimi** [requests/requests#4395]
Summary.
With python 2.7.10, I got this error but it's ok with python 3.6. I tried to ask a co-worker to try my code with his computer, it's still work with python2.7.10. It's strange
## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.1.3"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.10"
  },
  "platform": {
    "release": "16.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "9081df",
    "version": "0.13.1"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "9081df"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Lukasa** [comment]
We need to know more about what’s happening here: can we get some sample code? All this means is that the remote server is closing the connection when we aren’t expecting it.

**Comment by sigmavirus24** [comment]
This has gone 5 days without information necessary to investigate anything. As such, I'm closing this. If you have the chance to provide us with more information, we may be able to reopen this and help investigate.
