### ISSUE TITLE
Could we set the request json's dump charset?

### ISSUE THREAD

**Issue by hsiunien** [requests/requests#4398]
As you know, I use the requests  post some data to the server, my JSON data is
```
{'name':'张三'} 
```
## Expected Result
origin json data,like {'name':'张三'}

But I catch the  package, it translated into 
## Actual Result
```
{'name':'\u5f20\u4e09'}
```
But the server couldn't recognize it.
## Reproduction Steps

```python
import requests
request.post('http://example.com/xxx',json={'name':'张三'})
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.2"
  },
  "platform": {
    "release": "16.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020df"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}

```
I trace the source code, I found requests call the json.dumps
in models.py at  about line 454,
```python 
        if not data and json is not None:
            # urllib3 requires a bytes-like body. Python 2's json.dumps
            # provides this natively, but Python 3 gives a Unicode string.
            content_type = 'application/json'
            body = complexjson.dumps(json)
            if not isinstance(body, bytes):
                body = body.encode('utf-8')

        is_stream = all([
            hasattr(data, '__iter__'),
            not isinstance(data, (basestring, list, tuple, collections.Mapping))
        ])
```
the dumps haven't any parameter, so how could I set the parameter ensure_ascii?

**Comment by sigmavirus24** [comment]
You can call `json.dumps` yourself to get that effect. We don't provide anything other than the 98% use case. This is an advanced use-case and we expect that you can do this yourself (including setting the `Content-Type`).

Cheers,
Ian

**Comment by schettino72** [comment]
@sigmavirus24 Could you please reconsider that? I am sure non-ascii data usage is well beyond 2%.

I could write a patch if you guys agree: i see 2 possible solutions adding a parameter `json_unicode` (where json dumps would be called with `ensure_ascii=False`, or an extra `json_ensure_ascii`.

**Comment by sigmavirus24** [comment]
@schettino72 quoting myself:

> This is an advanced use-case and we expect that you can do this yourself (including setting the Content-Type).

In other words:

```py
requests.request(method, url, data=json.dumps(...).encode(...), headers={'Content-Type': ...})
```

The API is in feature-freeze so we're not adding new keywords.
