### ISSUE TITLE
pandas.read_html(url)  

### ISSUE THREAD

**Issue by zhongyutech** [requests/requests#4399]
Summary.

## Expected Result

import pandas as pd
for i in range(1,10):
    url="https://myip.ms/browse/sites/{0}/ipID/23.227.38.0/ipIDii/23.227.38.255/sort/2/asc/1/".format(i)
    dfs=pd.read_html(url)
    data=dfs[13]
    select_index=data.index[data.index%2==0]
    jg=data.iloc[select_index,:7]
    jg.to_excel("d:\{}.xls".format(i))

## Actual Result

don't need one by one，get all！

What a wonder！

I hope you can try

**Comment by sigmavirus24** [comment]
I believe you've filed this against the wrong project. I don't see anything related to this project.
