### ISSUE TITLE
IndexError when handle http response

### ISSUE THREAD

**Issue by beruhan** [requests/requests#4400]
I receive a http response like this,
```
HTTP/1.1 200 OK
	Content-Type: application/octet-stream
	Content-Length: 89606
	Content-Disposition: attachment; filename="MB-500Ap_2009-01-12.cfg"
	Connection: close

Brickcom-50xA
OperationSetting.locale=auto
HostName.name=cam
ModuleInfo.DIDO_module=1
ModuleInfo.PIR_module=0
ModuleInfo.WLED=0
SensorFPSSetting.fps=0
ModuleInfo.AUTOIRIS_module=0
ModuleInfo.IRCUT_module=0
ModuleInfo.IRLED_module=0
ModuleInfo.lightsensor=0
ModuleInfo.EXPOSURE_module=0
ModuleInfo.MDNS_module=0
ModuleInfo.PTZ_module=1
ModuleInfo.MSN_module=0
ModuleInfo.WIFI_module=0
ModuleInfo.watchDog_module=0
ModuleInfo.sdcard_module=1
ModuleInfo.usbstorage_module=0
ModuleInfo.sambamount_module=0
ModuleInfo.QoS=0
ModuleInfo.shutter_speed=0
ModuleInfo.discovery_internet=1
ModuleInfo.POE_module=
ModuleInfo.audio_record=1
```
it throws exceptions.IndexError, but I use chrome visit the same url,It has not error

**Comment by sigmavirus24** [comment]
Please provide the traceback for the IndexError you receive or a URL that we can use to reproduce this.

**Comment by sigmavirus24** [comment]
We also need the output from `python -m requests.help` or failing that `python -c 'import requests; print(requests.__version__)'`

**Comment by beruhan** [comment]
`python -m requests.help` output is
 `{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.1.1"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.14"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010006f",
    "version": "17.3.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}`
traceback output is:
```File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 617, in urlopen
    **response_kw)
  File "C:\Python27\lib\site-packages\urllib3\response.py", line 456, in from_httplib
    headers = HTTPHeaderDict.from_httplib(headers)
  File "C:\Python27\lib\site-packages\urllib3\_collections.py", line 312, in from_httplib
```
 I can provide a test url, http://193.92.77.225/configfile.dump,username and password is admin,basic auth.thanks a lot!

**Comment by sigmavirus24** [comment]
That's not a complete traceback. I don't see the IndexError in that output

**Comment by sigmavirus24** [comment]
I was able to reproduce this. It's a bug in how urllib3 handles headers that start with `' '` or `'\t'` (which these headers do.

**Comment by sigmavirus24** [comment]
All of the headers in this response start with `'\t'` and so https://github.com/shazow/urllib3/blob/ead61e0fd4f386339d78baf766f9188832ddead3/urllib3/_collections.py#L312 fails because `headers` is `[]` and `headers[-1]` generates an IndexError. It's unclear to me what was being handled by that in https://github.com/shazow/urllib3/commit/ed15c4ab9d64e280ea38b5be24c61a0ae3dfbe81

**Comment by Lukasa** [comment]
The headers in this response *may not* start with `\t`. `\t` is reserved explicitly for continuation lines, which these are not. This is simply a malformed HTTP response, and it's not really reasonable to try to parse it correctly.
