### ISSUE TITLE
Find cause of status code 0

### ISSUE THREAD

**Issue by grillorafael** [requests/requests#4401]
Hi All,

I'm trying to debug why sometimes my requests fail (Doing some perf test through `locust.io`) but I can't find the cause. My nginx logs have no error attached and what I see is requests giving status code 0.

I thought it could be timeout but I timed the request and I see <1sec.

Is there a way for me to find out why I'm getting this behavior? 

I'm basically getting `status_code==0` but I can't find a reason to that.

I'm using python 2.7 and locust to run the perf test

**Comment by sigmavirus24** [comment]
I believe we pull the status code [here](https://github.com/requests/requests/blob/d1fb1a29ab949223d8d64797e0fcc9a7d2690483/requests/adapters.py#L267) which means fundamentally this is a urllib3 bug. Requests defaults the status code to `None` but has specific handling for [this case](https://github.com/requests/requests/blob/d1fb1a29ab949223d8d64797e0fcc9a7d2690483/requests/models.py#L820). That aside, is this a non-exceptional case? I've never seen a status code of 0 for a non-exceptional case.

**Comment by grillorafael** [comment]
I see. And do you know any way for me to debug the reason why urllib3 is failing to do something?

**Comment by sigmavirus24** [comment]
Looking at `response.raw` would be a good place to start. You didn't really answer my question though: Is the response object you're receiving coming from an exception that's been handled?

**Comment by grillorafael** [comment]
I believe so.

This is the line:
https://github.com/locustio/locust/blob/a4c377efc7914e8d90701d9226a5cd843859b790/locust/clients.py#L161

**Comment by sigmavirus24** [comment]
Did you notice https://github.com/locustio/locust/blob/a4c377efc7914e8d90701d9226a5cd843859b790/locust/clients.py#L164 ?

**Comment by Lukasa** [comment]
Closing as a downstream bug.
