### ISSUE TITLE
requests.get() always pumps out errors in my Spyder3.2.4

### ISSUE THREAD

**Issue by gfkdcadet** [requests/requests#4403]
Summary.

I was trying to get data from a website by using requests module in my spyder3.2.4.
I used requests.get() to realize the goal.
It worked well. But, recentely, when I used requests.get(), spyder would pump out errors.
Really confusing.

What you expected.

## import requests
r = requests.get(url)
r.status_code

200

What happened instead.

**AttributeError: module 'requests' has no attribute 'get'**

```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and

 greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by gfkdcadet** [comment]
I have a screenshot of the problem. But I cannot upload it..... When I tried, it always told me that something went really wrong, and it cannnot process that file! 
pity....
help me..... The problem is abusing me .....

**Comment by nateprewitt** [comment]
@gfkdcadet, this is almost certainly an issue with you having a file name "requests.py" in your project that is causing namespace conflicts.

If not, please either open an issue on Stackoverflow or you can email me at the email in my profile. I'm going to close this out since it's not a defect with Requests.

**Comment by gfkdcadet** [comment]
Sorry for my ignorance. Yes, as u said, it is the problem of the inproper file name "requests.py", which caused namespace conflicts.@nateprewitt
