### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

### ISSUE THREAD

**Issue by munaAchyuta** [requests/requests#4406]
i am facing `requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)` issue.
i am using python 

> v2.7.13

 , requests 

> v2.7.0.

my service is started with https using bottle-paste. i have created certificates using openssl. for server-side i am using **.pem** and from client-side i am using **.pkcs12**. 
and my service using **OpenSSL** . i am using **sslcontext** to start service `SSL.Context(SSL.SSLv23_METHOD).`
and as you guys know requests module using ssl.
**same service can hit from java , postman** with using client certificates( .pkcs12 ). not sure why is it failing here ? can any one help me here ??

**Comment by tiran** [comment]
Python's ssl module does not support PKCS12 files. You have to extract the PKCS12 and dump the key and cert to disk. You may also need to dump the CA and intermediate chain.

Something like this should do the trick. ``cert.pem`` contains key, cert and maybe chain.

```
$ openssl pkcs12 -in file.p12 -out client.pem -chain -nodes
```

**Comment by sigmavirus24** [comment]
Thanks for that @tiran. I think this should help you understand why your having trouble @munaAchyuta. Cheers!

**Comment by munaAchyuta** [comment]
Thanks @tiran for your solution. Yes it solved my issue. Thanks for responding.
