### ISSUE TITLE
Requests doesn't respect socket default timeout ( socket.setdefaulttimeout() )

### ISSUE THREAD

**Issue by farin** [requests/requests#4416]
urllib3 and Requests has different semantic when handling unspecified timeout (which means no keyword arg given)

## Actual Result

**urllib3** 
- when timeout is None -> no timeout
- when timeout is not given -> internal _Default objects is used which leads to `socket.getdefaulttimeout()`
see https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L373

**requests**
both None and not specified timeout is handled in same way. urllib3 `Timeout` object is created
with None values -> no timeout at all while `socket.getdefaulttimeout()` is ignored.
see https://github.com/requests/requests/blob/master/requests/adapters.py#L431
timeout arg is always passed into underlaying urllib3

## Expected Result

I think it should be better handle it same as urllib3. When timeout is not specified on request level then don't replace it with infinite timeout but just pass unspecified to timeout to urllib3

## System Information

reported on requests version 2.18.4

**Comment by Lukasa** [comment]
Thanks, this is a known issue and should be resolved in 3.0.
