### ISSUE TITLE
chardet is licensed under LGPL

### ISSUE THREAD

**Issue by asieira** [requests/requests#4417]
`chardet` is a dependency of `requests` and is licensed under the LGPL 2.1.

Aren't GPL and LGPL components incompatible with the Apache 2.0 license used by `requests`, as per https://www.apache.org/legal/resolved.html#category-x and https://www.apache.org/licenses/GPL-compatibility.html?

**Comment by sigmavirus24** [comment]
@asieira it really depends on how you interpret the language.

First, you're linking to a section titled: `Which licenses may NOT be included within Apache products?` I believe that means projects developed specifically by the ASF not under the Apache License.

LGPL might cause license issues if we were modifying chardet and including that in Requests. That would affect our licensing.

**Comment by johnthagen** [comment]
FWIW, in case anyone else finds this closed issue, https://github.com/psf/requests/issues/4848#issuecomment-544558645 lists an MIT licensed alternative to `chardet`.
