### ISSUE TITLE
Add a new argument to a request that allows people to always keep the same method after a redirect

### ISSUE THREAD

**Issue by jakegt1** [requests/requests#4418]
Hi, i'm sorry if this is written incorrectly - unsure if feature requests are really allowed, so if they're not just simply delete the issue.

A small annoyance i've found which isn't a problem specifically with requests is when a webserver uses a 302/301 redirect when they should be using a 307 or a 308. This happens a lot with common webservers as more and more websites have http -> https redirects.

This can be a problem when doing anything that isn't a GET request, as request's resolve_redirects code will change the request method when the webserver isn't using the correct http status code (or is trying to preserver backwards compatibility.

My suggestion is to add an argument to a request that allows people to not rebuild the method in the case of redirects.

I have written the code (and test) for it if anybody is interested to look at it.

**Comment by Lukasa** [comment]
Thanks, but Requests isn’t accepting additional keyword arguments at this time. Disabling redirect resolution or overriding some of the methods on `Session` that handle redirects can get you what you want.

**Comment by jakegt1** [comment]
I do know it's fixable via disabling redirect resolution, it's just a bit of a pain to work with. 

Thanks though, wasn't sure what was allowed to be added and what wasn't..
