### ISSUE TITLE
requests.exceptions.ProxyError: HTTPSConnectionPool: Failed to establish a new connection

### ISSUE THREAD

**Issue by vThinkBeyondVM** [requests/requests#4419]
Last week I started exploring requests library for invoking REST APIs, it was working fine, I was able to make calls as expected but today when I run the same python script, it fails with below error. Please help. 

My OS: Ubuntu 16.04
Python: Python 2.7.12
requests library version: 2.18.1

Traceback (most recent call last):
  File "restfilters.py", line 15, in <module>
    vcsession = vcrest.get_vc_session(vcip,"Administrator","password")
  File "/home/vmware/vcrest.py", line 19, in get_vc_session
    s.post('https://'+vcip+'/rest/com/vmware/cis/session',auth=(username,password))
  File "/home/vmware/.local/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/vmware/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vmware/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/vmware/.local/lib/python2.7/site-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='10.192.64.32', port=443): Max retries exceeded with url: /rest/com/vmware/cis/session (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa16ac2c7d0>: Failed to establish a new connection: [Errno 113] No route to host',)))

**Comment by sigmavirus24** [comment]
We literally cannot connect to the proxy you've configured. It's unreachable. This is a network configuration error, not a requests error.

**Comment by vThinkBeyondVM** [comment]
Ok @sigmavirus24 ,  I did check network connectivity between the server I am invoking the REST API and the VM from where I am running python script, it was pinging fine but it is giving same error as reported. I am not getting how to go ahead for troubleshooting this further. Earlier same setup worked fine. Any help would be really appreciated.

**Comment by sigmavirus24** [comment]
@vThinkBeyondVM The problem exists in that there is a proxy sitting somewhere between Requests and the server you wish to connect to. We cannot connect to the proxy. You have configured the proxy. If you need help debugging that further, please ask your specific questions on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests) since this is not a defect (or bug) in Requests.

**Comment by oghabetanha** [comment]
raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetErr
