### ISSUE TITLE
Making a post to a server on localhost is slow

### ISSUE THREAD

**Issue by JesseAldridge** [requests/requests#4426]
Question posted here:  https://stackoverflow.com/questions/47766158/why-is-python-requests-to-localhost-slow

Basically I have a trival server running locally.  When I use requests to do a post to it it takes a few seconds to respond.

## Expected Result

A sub-second response

## Actual Result

A pause of a few seconds before a response

## Reproduction Steps

See code shared on https://stackoverflow.com/questions/47766158/why-is-python-requests-to-localhost-slow

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.8.1"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.10"
  },
  "platform": {
    "release": "17.2.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010005f",
    "version": "17.0.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "20000000"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

**Comment by JesseAldridge** [comment]
Ah nevermind.  Issue resolved instantly.  Got to love Stackoverflow.

**Comment by szabolcsdombi** [comment]
I want to know why this happens.
Can anyone help?

I was able to make a **100x** speedup changing `"localhost"` to `"127.0.0.1"`.

**Comment by sigmavirus24** [comment]
@cprogrammer1994 we use DNS in the case when we're not given an IP Address. localhost is plenty fast for me, but my `/etc/hosts` isn't a disaster as was described in the StackOverflow comment above. I suggest you read that question and perhaps fix up your developer environment.

**Comment by szabolcsdombi** [comment]
@sigmavirus24 thanks for the fast reply! My hosts file contains a single row (I am on windows). Unfortunately I have a lot of virtual network interfaces that could cause the problem.

- Running `ptime nslookup localhost` takes `0.05` to `0.15` seconds
- It takes exactly 1 second to run a `request.get(...)` using `"localhost"`

**Comment by szabolcsdombi** [comment]
It is clearly not a `requests` bug!

The following snippet is slow too:

```py
import urllib.request
urllib.request.urlopen('http://localhost:80').read()
```
