### ISSUE TITLE
What's the meaning of the homepage image?

### ISSUE THREAD

**Issue by lightning-zgc** [requests/requests#4429]
What's the meaning of this:
![68747470733a2f2f6661726d352e737461746963666c69636b722e636f6d2f343331372f33353139383338363337345f313933396166336465365f6b5f642e6a7067](https://user-images.githubusercontent.com/16239566/34022048-f8ea84be-e177-11e7-863b-c8ee5f79fab4.jpeg)

**Comment by ghost** [comment]
A butterfly at the waterline?

**Comment by nateprewitt** [comment]
Hey @lightning-zgc, the photos you see throughout the Requests docs are taken by Kenneth Reitz. You'll find things like this in most of the documentation for projects he started, and it's mostly there for aesthetic purposes. Hopefully that helps answer your question!

For future reference, we prefer to keep the issue tracker limited to tickets around defects in Requests. Email or social media may be a better avenue for questions like these.
