### ISSUE TITLE
Cookies lost during multiple redirects

### ISSUE THREAD

**Issue by batzel** [requests/requests#4430]
Cookies are lost when set by sites returning redirects.

Example:
r=requests.get('http://hostA/url1')
where url gives multiple redirects, possibly multiple sites.
e.g. hostA/url1 -> 302 -> hostB/url2 -> 302 -> HostC/url3

Expectation: 
r.cookies would have all the cookies set by hostA, hostB, and hostC

Actual Result:
r.cookies contains only the cookies set by the hostC. The others are lost. 

Further example from real-world scenario:
$ python3
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r=requests.get('redactedurl')
>>> r.history
[<Response [302]>, <Response [302]>, <Response [302]>, <Response [302]>]
>>> len(r.cookies)
1
>>> 

-----

>>> r=requests.get('redactedurl', allow_redirects=False)
>>> r.cookies
<RequestsCookieJar[]>
>>> c=r.cookies
>>> r.status_code
302
>>> r=requests.get(r.headers.get('location'), allow_redirects=False, cookies=c)
>>> r.status_code
302
>>> c.update(r.cookies)
>>> r=requests.get(r.headers.get('location'), allow_redirects=False, cookies=c)
...
>>> r.status_code
200
>>> c.update(r.cookies)
>>> len(c)
3

## System Information
```
$ python3 -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.1.4"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.1"
  },
  "platform": {
    "release": "17.3.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010007f",
    "version": "17.5.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

**Comment by Lukasa** [comment]
`r.cookies` contains only the cookies set by the most recent response. Use a `Session` and collect the cookies from `Session.cookies`.
