### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by H0nus** [requests/requests#4432]
How i can avoid url encoding into a post parameter?
like:
username=not encoded data&password=not encoded data&login=True

i tried with:
`config={'encode_uri': False}`
but it doen't work anymore

**Comment by ghost** [comment]
Why don't you want the parameter to be URL encoded? Every server should be able to decode this.

**Comment by sigmavirus24** [comment]
This is not a forum for questions and answers. The place to ask questions for technical help is [StackOverflow](https://stackoverflow.com). Please redirect your discussion there.
