### ISSUE TITLE
How to use this library and Android for picture transmission

### ISSUE THREAD

**Issue by shede1988** [requests/requests#4433]
Summary.

## Expected Result

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by ghost** [comment]
What do you mean by 'picture transmission'?

**Comment by sigmavirus24** [comment]
This is not a forum for questions and answers. The place to ask questions for technical help is [StackOverflow](https://stackoverflow.com). Please redirect your discussion there.
