### ISSUE TITLE
request blocked when i try to request an offline server

### ISSUE THREAD

**Issue by hiwjcn** [requests/requests#4435]
i wrote a program with requests to wake up my site.
when i deploy my site,the server can't response.
then i saw the requests blocked forever , can't continue next requst again.
i have no log,just an appearance

**Comment by sigmavirus24** [comment]
Please provide us with the output of

```
python -m requests.help
```

If that is unavailable on your version of Requests please provide some basic information about your system (Python version, operating system, etc).
