### ISSUE TITLE
Proxy doesn't work for https connections

### ISSUE THREAD

**Issue by a-wakeel** [requests/requests#4440]
Summary.
The requests proxies do work for the **http** connections but not for **https** connections. I tried to find a solution to this problem but could not find any satisfied answer. Here is the sample test code:

```python
import requests

proxy = {
'http': 'http://user:pass@ip:http-port',
'https': 'http://user:pass@ip:https-port'
}

res = requests.get('https://somesite', proxies=proxy)
print(res.text)
```
## Expected Result
It should return the page content by establishing a connection as it does in case of **http** request.

## Actual Result
I got this error upon using https request:

```bash
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.com', port=
443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to
proxy.', error('Invalid response from tunnel request',)))
```
## Reproduction Steps

```python
import requests

proxy = {
'http': 'http://user:pass@ip:http-port',
'https': 'http://user:pass@ip:https-port'
}

res = requests.get('https://somesite', proxies=proxy)
print(res.text)
```

## System Information
I'm using this code on **Windows Operating System**.

**Comment by ghost** [comment]
It seems to work now, my bad !
Just found the solution here [Socks Support](https://github.com/requests/requests/pull/478)

**Comment by radiumtall** [comment]
+1 requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /search?source=hp&ei=h45CXayCH_eVr7wPmoahuAU&q=inurl:id=1 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个
现有的连接。', None, 10054, None)))
