### ISSUE TITLE
Download file with Chinese charactor, the Response headers filename is incorrect, not cn, but messy code. 

### ISSUE THREAD

**Issue by truelovesdu** [requests/requests#4444]
When I log infos,
logging.debug("@@@###:%s" % response.headers)
The output is as below:
@@@###:{'Server': 'openresty', 'Date': 'Tue, 02 Jan 2018 03:02:52 GMT', 'Content-Type': 'application/octet-stream;charset=utf8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Disposition': ';filename="æµ\x8bè¯\x95ç\x8e¯å¢\x83ä¿¡æ\x81¯.xlsx"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'}
U can see the filename is messy.

**Comment by sigmavirus24** [comment]
Please provide us with the output of

```
python -m requests.help
```

If that is unavailable on your version of Requests please provide some basic information about your system (Python version, operating system, etc).
