### ISSUE TITLE
SSL certificate/key not working but same certificate/key works with curl

### ISSUE THREAD

**Issue by sheilacheng** [requests/requests#4449]
Summary.
SSL certificate/key not working but same certificate/key works with curl

## Expected Result
certificate/key verifies properly

## Actual Result
SSLError: HTTPSConnectionPool(host='app.domain.com', port=443): Max retries exceeded with url: /p1/p2/p3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

## Reproduction Steps
This works:
&nbsp;&nbsp;&nbsp;      curl -X POST -v -s -k --key client.key --cert client.crt   <blah blah ....>
<br>
This does not and gives the above error.
&nbsp;&nbsp;&nbsp;      cert_file_path = '/path-to-certfile/cert.pem'
&nbsp;&nbsp;&nbsp;      key_file_path = '/path-to-keyfile/key.pem'
&nbsp;&nbsp;&nbsp;      cert = (cert_file_path, key_file_path)
&nbsp;&nbsp;&nbsp;      requests.post(url, data=payload, cert=cert)
<br>
The client.key and client.crt are actually both in pem format (ascii readable). The server uses Nginx. I found some references about missing intermediate certificates but I'm not sure how to fix it on the server or add it to my client (just to see it work!).
<br>
```python
import requests

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.0.3"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.3"
  },
  "platform": {
    "release": "16.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "100020cf",
    "version": "17.2.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020cf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

`curl -k` (a.k.a, `curl --insecure`) means do not verify the server's certificate when performing the TLS connection. `cert` in `requests` is equivalent to the `--cert` and `--key` parameters but Requests will still try to perform certificate validation. That means that you probably want to also pass `verify=False` to requests.

**Comment by sheilacheng** [comment]
To follow up, I have the issue described in this post.
https://stackoverflow.com/questions/42538930/ssl-error-with-python-requests-despite-up-to-date-dependencies

The fix is just to concatenate all the certs (including intermediate ones) into a single cert file and stick it on the cert directly on the server. If you are the client and can't fix the server, just use the test cert in the post.
