### ISSUE TITLE
How about the error:Max retries exceeded with url

### ISSUE THREAD

**Issue by bigpangl** [requests/requests#4450]
## error code

```python

Traceback (most recent call last):
  File "F:/github/about_googlemap/about_googlemap/test_internet.py", line 12, in <module>
    url='https://www.google.com.hk/')
  File "F:\github\about_googlemap\venv\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "F:\github\about_googlemap\venv\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\github\about_googlemap\venv\lib\site-packages\requests\sessions.py", line 523, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\github\about_googlemap\venv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "F:\github\about_googlemap\venv\lib\site-packages\requests\adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.google.com.hk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005BFBEB8>: Failed to establish a new connection: [Errno 10060] ',))

```

## about the environment

- windows 10 Home Edition

- python 2.7+ 64

- requests 2.16.0 (I run the code in a virtualenv env)

- the place : china. I use shadowsocks , and I can google search by Chrome

## python code

```python
import requests

response = requests.get(
    url='https://www.google.com.hk/')
print response
```

## process

I try to use googlemaps , a python library, which may rely requests? 

And I over the wall by shadowsocks. I can view google and search by google with chrome. And I can direct get api  json data by view 'https://maps.googleapis.com/maps/api/distancematrix/json?origins=Vancouver+BC|Seattle&destinations=San+Francisco|Victoria+BC&key=[my_project_key]' with chrome .

But when I use requests library such as `requests.get()`, It shows the error above(ps: when I use googlemaps, error also  come out, almost the same), I tried to find some solution from github, and I change the version of requests to 2.16.0, but error not go away. Also I see some setting should be in code,such as timeout?  But it seems no use for me this time.

En, the time, between I run the code and the error finally print out, about 20s.

Also , my classmate, had no get the error, we do almost the same steps, but he tells me,he can print the response correctly.

## question

- First I want to know , how  does this error come?
    It comes from my setting or the internet outside? 

- Second, I want to solve the error, what may I do to keep error away?
   This is I expect.

## otherthings

Did I put out more information to you ?  If need, tell me please and I would try to give you more information.

Thank you

**Comment by sethmlarson** [comment]
You might need to make requests aware of your proxy. I suggest reading and following the examples shown in [Advanced Usage - Proxies](http://docs.python-requests.org/en/master/user/advanced/#socks) section of our documentation.

Make sure you have Socks support installed:
`python -m pip install requests[socks]`

And then define your proxies like this:

```python
proxies = {
    'http': 'socks5://[USER]:[PASS]@[HOST]:[PORT]',
    'https': 'socks5://[USER]:[PASS]@[HOST]:[PORT]'
}
r = requests.get(url, proxies=proxies)
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by lanhao945** [comment]
Sorry, I  get a wrong use of issue. Thank you very much.

**Comment by lanhao945** [comment]
sorry I am late when I see the email. But I had see it in the github. I had solved this problme. This error comes from the proxy, I should change the style pac to global variable.
Thank you very much!

At 2018-01-06 23:18:52, "Seth M. Larson" <notifications@github.com> wrote:


You might need to make requests aware of your proxy. I suggest reading and following the examples shown in Advanced Usage - Proxies section of our documentation.
