### ISSUE TITLE
Requests now ignores system installed CA certs

### ISSUE THREAD

**Issue by james-portman** [requests/requests#4463]
(I know about REQUESTS_CA_BUNDLE etc)
Requests now ignores system installed CA certs and causes SSL errors when visiting https addresses which use a custom/system installed CA.

Requests is used by a number of other applications, so it is not always straightforward to set environment variable, nor do I think it should be necessary.
There are a load of other tools that respect the system installed CA certs such as wget, curl...
Why have you made this change?
Can there be a discussion about reverting the behaviour?
Could you do something else like load in the system CAs then use your other method on top?
(is it certifi?)

## Expected Result

Visiting a https url for which I have the CA cert installed system wide should work.

## Actual Result

An SSL error.

## Reproduction Steps

```python
import requests
requests.get('https://some_url')
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": "2.1.4"
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.14"
  }, 
  "platform": {
    "release": "4.13.0-16-lowlatency", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "1010007f", 
    "version": "17.3.0"
  }, 
  "requests": {
    "version": "2.18.4"
  }, 
  "system_ssl": {
    "version": "1000207f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": true
}

```

**Comment by sigmavirus24** [comment]
> Requests now ignores system installed CA certs

Requests installed via pip *never* observed system-installed CA certs (except maybe in the very early 0.x days). If you're installing Requests via your system package manager, then it's likely that they've broken their patching for CA certs and this needs to be reported there.
