### ISSUE TITLE
Fail to access cookies

### ISSUE THREAD

**Issue by Napator** [requests/requests#4469]
Hello,

I've made a simple test to try to acces cookies via httpbin, as shown in th "quicksart" page of the documentation.

Is it a bug of the module, or something in don't get ?

Thank you for your answers.

## Expected Result

Expected handle of the cookie.

## Actual Result

{
  "cookies": {
    "test": "test"
  }
}

Traceback (most recent call last):
  File "Test-webanim.py", line 9, in <module>
    r1.cookies['test']
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 293, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 351, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='test', domain=None, path=None"

## Reproduction Steps

```python
import requests

payload = {'test':'test'}
r1 = requests.get('https://httpbin.org/cookies/set', params = payload)
print(r1.text)
a =requests.utils.dict_from_cookiejar(r1.cookies)
r1.cookies['test']

```

## System Information

    $ python -m requests.help

{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "4.4.0-109-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}

**Comment by nateprewitt** [comment]
Hey @Napator, this is the documented functionality of both the httpbin.org/cookies endpoint and Requests. You are sending cookies to the server, and it's returning a json document containing what it received. The `cookies` attribute tells you what cookies the server set, for which you would use the httpbin.org/cookies/set endpoint. Also please note that requests are stateless, so you'll need to use a `Session` to maintain cookies across calls or redirects.

In the future, please ask questions about how to use Requests on [StackOverflow](https://stackoverflow.com/). We use the ticket tracker to track defects in Requests and ~1200 people get paged everytime there's an update here. Thanks!
