### ISSUE TITLE
requests use https proxies problem

### ISSUE THREAD

**Issue by super5hunz1** [requests/requests#4471]
Summary.

i have a problem about proxies
use requests https proxies can't work.
but i use urllib is work.

thank for u reply :+1: 
## Expected Result

What you expected.

## Actual Result

111.183.228.184:43841
C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)

HTTPSConnectionPool(host='om.qq.com', port=443): Max retries exceeded with url: /userAuth/index (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown
protocol (_ssl.c:777)'),))

## Reproduction Steps

```python
import os
import ssl
import time
import requests
from pprint import pprint

s = requests.session()
s.keep_alive = False

http_proxies_api = 'http://www.thisismyapi.com/http/'
https_proxies_api = 'http://www.thisismyapi.com/https/'
base_url = 'https://om.qq.com/'
check_ip_url = 'http://2017.ip138.com/ic.asp'

def requests_proxies():
    proxies_ip = s.get(https_proxies_api).text
    proxies_ip = proxies_ip.strip()
    print (proxies_ip)

    try:
        try_connect = s.get(base_url, proxies={'https': proxies_ip}, verify=False)
        try_connect.encoding = 'gbk'
        print (try_connect.headers)
    except Exception as err:
        print (err)


for i in range(10):
    time.sleep(2)
    requests_proxies()
```

## System Information

    $ python -m requests.help

```
C:\Users\DreamPython>python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.3"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}

C:\Users\DreamPython>

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by super5hunz1** [comment]
i try get https://om.qq.com/somethingfiles
this is work.
but https://om.qq.com/ can't work. i don't know why =v=

**Comment by nateprewitt** [comment]
@super5hunz1 This seems to strongly point to something incorrectly configured on the server. It appears you're being redirected so some kind of auth service which is trying to negotiate an "unknown" SSL protocol. The fact that some pages work while others don't, and the SSL implementation being used is either outdated, or not SSL, supports this too.

If you can reproduce this on multiple domains or come up with a more specific repro, feel free to reopen. I currently am unable to reproduce this with the information given at the moment though. Thanks for the report!
