### ISSUE TITLE
interrupt request from main thread

### ISSUE THREAD

**Issue by lonnyzhang423** [requests/requests#4475]
How to interrupt an ongoing request in response to signal.SIGINT from main thread?
```
requests.get(url)
```
The code above running in a child thread. I expect the request return or raise an exception immediately once the main thread catch `KeyboardException`.
How to do that? 
Thanks in advance.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by lonnyzhang423** [comment]
Thanks for your advice.
