### ISSUE TITLE
Connection aborted , while uploading files over 10GB

### ISSUE THREAD

**Issue by kpputhiyattil** [requests/requests#4479]
Summary.
When I try to upload a file more than 5GB, connection error occurs, saying the connection is aborted.
ProtocolError('Connection aborted.', error("(-1, 'Unexpected EOF')",))
## Expected Result
File should be uploaded
What you expected.

## Actual Result
Exception occurs
ProtocolError('Connection aborted.', error("(-1, 'Unexpected EOF')",))
What happened instead.

## Reproduction Steps

```python
            request_obj = APIServices.HttpReq.getInstance()
            e = encoder.MultipartEncoder(fields={'backupfile':(os.path.basename(backupfile.encode('unicode-escape')),open(r"D:\\Movies\\Aruvi\\www.TamilRockers.st - Aruvi (2017)[1080p HQ HD - AVC - MP4 - 5.5GB - Tamil].mp4","rb") )})
            m = encoder.MultipartEncoderMonitor(e)
            m._read = m.read
            m.read = lambda size: m._read(1024)
            headers = {'Accept': 'application/json, text/javascript, */*; q=0.01',
                            'Accept-Encoding': 'gzip, deflate, br',
                            'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6','Connection': 'keep-alive','Content-Type': m.content_type}
            uploadObj = BackupResponse.upload_files()
        response = APIResponse.Response(uploadObj)
        
          response_obj = request_obj.upload_reqPost(url=urls, calling_obj=response, params=payload,data=m,contentType=m.content_type)
```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hey @kpputhiyattil, this appears to be a request for assistance. We reserve issues on the tracker for a defect in Requests, and suggest using [StackOverflow](https://stackoverflow.com) for usability questions. Also given none of the code provided is clearly related to Requests there’s nothing we can investigate.
