### ISSUE TITLE
[Question] Is there in built tracer(distributed tracing) available with request module?

### ISSUE THREAD

**Issue by falu2010** [requests/requests#4483]
Summary.
I am trying to implement distributed tracing with python request client but I could not find any example  is there a default support in requests? Also, I don't want to use flask.
## Expected Result

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
