### ISSUE TITLE
ChunkedEncodingError when receive response

### ISSUE THREAD

**Issue by etiaxie** [requests/requests#4484]
python version:python 2.7.10
requests version:2.11.1
my http request looks like this: 
![1](https://user-images.githubusercontent.com/10825713/35427455-7a156ee4-02a4-11e8-8494-7a354284cc10.jpg)
response like this:
![2](https://user-images.githubusercontent.com/10825713/35427460-84a9ad02-02a4-11e8-9fb9-527fa4c68d63.jpg)
then will get the exception:
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 476, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 629, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 679, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(10054, '')", error(10054, ''))

**Comment by sigmavirus24** [comment]
There is not enough information here to assist you. Further this appears to be the server closing the connection before our underlying HTTP library expects you to. As a result, there's no bug in requests. If you have a question, please use [StackOverflow](https://stackoverflow.com)
