### ISSUE TITLE
 SubjectAltNameWarning

### ISSUE THREAD

**Issue by Davidrjx** [requests/requests#4487]
Summary.

## Expected Result
drop this warning

## Actual Result

during every request, the warning outputs console.

## Reproduction Steps

```python
import requests
requests.get('url',verify=cert_file_path)
```

## System Information

    $ python -m requests.help
![1_2018129185059](https://user-images.githubusercontent.com/4284791/35506774-72760774-0525-11e8-84b1-48e95befacc5.png)

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
@Davidrjx this warning is there to warn you that the certificate you're using either doesn't either doesn't have a SubjectAltName field or the names defined in the field don't match the presenting server. This is a safety feature of urllib3 that is surfaced through Requests, so it's not directly part of our codebase.

I don't see this changing anytime in the near future, so I'm going to close this out. I would suggest getting the certificate you're using fixed if possible, either yourself or by contacting the service owner. If you *MUST* use that certificate, you can find instructions for disabling warnings on StackOverflow, but I'm not going to promote those here. Thanks for the inquiry!

**Comment by Davidrjx** [comment]
@nateprewitt ok, thanks for your reply ,but i used common name in my ca file. as you said now , it is only possible to disable this warning.

**Comment by nateprewitt** [comment]
@Davidrjx, just to be clear, Common Name without a Subject Alt Name hasn't been compliant with spec for almost 18 years ([RFC2818](https://tools.ietf.org/html/rfc2818)). Both Chrome and Firefox have both dropped support for it and there's really not a reason to not have the field. There have been a [number of security issues](https://crypto.stanford.edu/~dabo/pubs/abstracts/ssl-client-bugs.html) around Common Name validation in the past which is part of why it's no longer supported.

If this is a self-signed cert, it's [not difficult to add SAN information to it](https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl/43860138#43860138).

**Comment by Davidrjx** [comment]
@nateprewitt got it,thanks very much
