### ISSUE TITLE
sending file with POST the whole file gets read before sending

### ISSUE THREAD

**Issue by ddor254** [requests/requests#4491]
Summary.

When sending file in requests with : 

f = open("blabla.pdf")
requests.post('http://localhost:9999',data=f)

the Whole file gets read before the request goes out, should not that be that the requests get sent with chunks - meaning a number of POST requests until the file gets ended??

i mean - when the requests library decide to "cut" and send the request?
it is the same in generator which send a lot of data

what is the maximum size of the request that being supported?

## Expected Result
several post requests 
What you expected.

## Actual Result
one big post request
What happened instead.

## Reproduction Steps

```python
import requests

f = open("blabla.pdf")
requests.post('http://localhost:9999',data=f)

```

## System Information
requests==2.5.1
python 2.7.3

**Comment by nateprewitt** [comment]
@ddor254 it sounds like you’re looking for information around multi-part encoding files for large data transfer. You can find information on that [here](http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file) in the docs.

If you have further questions, please open an issue on [StackOverflow](https://stackoverflow.com) with the Python-Requests tag and we can follow up there. We prefer to keep this issue tracker reserved for defects in Requests.

**Comment by ddor254** [comment]
o.k thank you for the quick response and help.
