### ISSUE TITLE
Deprecation Warning on Python 3.7 beta

### ISSUE THREAD

**Issue by csabella** [requests/requests#4494]
~/requests/models.py:170: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(hook, collections.Callable):

I created a venv in Python 3.7 and got the warning when using pip.

**Comment by nateprewitt** [comment]
Thanks for the report @csabella, we’re just starting to test against 3.7 so there’s likely some of these that haven’t been caught yet. This should be relatively simple to fix, so we can make sure this is adjusted before 3.7 is officially released.

**Comment by nateprewitt** [comment]
Resolved in #4501.
