### ISSUE TITLE
InvalidSchema should be InvalidScheme

### ISSUE THREAD

**Issue by kurtbrose** [requests/requests#4495]
Summary.

## Expected Result

If requests cannot determine what *scheme* a URL has it should report this clearly.

## Actual Result
```
InvalidSchema at /scrapyd/start-job/
No connection adapters were found for 'localhost:6800/schedule.json'
```

There is no such thing as a URL "schema". 

https://tools.ietf.org/html/rfc3986
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

The words "schema" and "scheme" are distinct.  "Schema" is the singular of "schemata".  The plural of "scheme" is "schemes" or "schemas". (https://english.stackexchange.com/questions/9232/plural-of-scheme)  Given that SQL uses the word schema this is an extremely confusing error message.

**Comment by nateprewitt** [comment]
Hey @kurtbrose, thanks for pointing this out. We’ve actually already patched this in #2961 but in the 3.0.0 branch due to this being a breaking change. The corrected naming will be available once the Requests team is ready to proceed with releasing 3.0.0.
