### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool

### ISSUE THREAD

**Issue by mehtajaghvi** [requests/requests#4512]
Summary.

## Expected Result
I am expecting the connection to be established with port 4000
What you expected.

## Actual Result

What happened instead.
File "/home/bl3-rqir-150-fi/inspection/url.py", line 20, in trigger_camera
    trigger_data = requests.get(self.url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4000): Max retries exceeded with url: /trigger_something/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa0100dea90>: Failed to establish a new connection: [Errno 111] Connection refused',))

## Reproduction Steps
It is not happening all the times, I am doing a httpPost to localport:4000. Multiple posts are done to this port but they are not simultaneous. 
```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.12"
  }, 
  "platform": {
    "release": "4.13.0-32-generic", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.18.4"
  }, 
  "system_ssl": {
    "version": "1000207f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": false
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Without knowing what your actually doing, there's nothing we can do to help.

For example, if you're using a single-threaded server locally that can only handle one connection at a time and sending multiple requests to it simultaneously, of course you'll see this.

Since this seems to not actually be a Requests bug but instead a request for help, I'm closing this. Please use [StackOverflow](https://stackoverflow.com) for questions and support needs. This project reserves the issue tracker for defects and feature improvements.
