### ISSUE TITLE
Hooks aren't called each time with retrying

### ISSUE THREAD

**Issue by Brett55** [requests/requests#4514]
Summary.

Hooks aren't called on each retry, only at the end of retrying

requests==2.18.4
requests-oauthlib==0.8.0

Is this intended functionality, how do I get a hook called on each retry? Here is my code 

```
retries = Retry(total=2,
                backoff_factor=0.1,
                status_forcelist=[404],
                raise_on_status=False
                )

self.gbdx_connection.mount(self.root_url, HTTPAdapter(max_retries=retries))

self.gbdx_connection.hooks['response'].append(refresh_token)
```

**Comment by sigmavirus24** [comment]
Using the `Retry` object means you're interacting with `urllib3`. Hooks are handled only in Requests. There's no plan to make hooks fire on retries inside of urllib3 when urllib3 doesn't have the concept of hooks.

**Comment by Brett55** [comment]
@sigmavirus24 doh that makes sense
