### ISSUE TITLE
python3 requests “freezes” but urllib.request.urlopen does not?

### ISSUE THREAD

**Issue by OlafEichstaedt** [requests/requests#4517]
For a certain website, results.get will not return a result but urllib.request.urlopen will. There is no error message (unless a timeout limit is set for the call), the control is simply not returned to the calling frame.

Is this a bug or some hidden feature I have failed to grasp yet?
Does it happen only for me or can other users reproduce the same result with the mentioned url?
Do you have any suggestions how to debug/investigate this further to make the report more useful?

## Expected Result

I expected to get the same result/behavior both on the Windows and the Linux machine,.

## Actual Result

(1) for a certain website, requests.get will return a result on Windows, but it "freezes" on Linux. When I say "freezes" it means that control is not returned to the calling frame.
(2) urllib.request.urlopen works for the website on both Windows and Linux

## Reproduction Steps
```
import requests
import time

time1 = time.time()
response=requests.get('https://www.tagheuer.com/en/watches/tag-heuer-carrera-calibre-5-automatic-watch-39-mm-war211a-ba0782')
time2 = time.time()
print(response.status_code)
print(time2-time1)
```
On the Windows system, the requests takes about 0.68s, on the Linux machine it takes forever.
On the Linux system, the following works:
```
 from urllib.request import urlopen
 import time
 url='https://www.tagheuer.com/en/watches/tag-heuer-carrera-calibre-5-automatic-watch-39-mm-war211a-ba0782'
 time1 = time.time()
 f = urlopen(url)
 myfile = f.read()
 time2 = time.time()
 print(f.status)
 print(time2-time1)
```
and returns status 200 after about 0.23 seconds.

## System Information from "python -m requests.help"
**Linux System**
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "4.4.0-112-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```
**Windows System**
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.0.3"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.3"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "100020cf",
    "version": "17.2.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

**Comment by hk-mars** [comment]
Hi @OlafEichstaedt:

Your issue did not happen on Mac OS(unix), below is my testing result:
##
>>> import requests
>>> import time
>>> 
>>> time1 = time.time()
>>> response=requests.get('https://www.tagheuer.com/en/watches/tag-heuer-carrera-calibre-5-automatic-watch-39-mm-war211a-ba0782')
>>> time2 = time.time()
>>> print(response.status_code)
200
>>> print(time2-time1)
1.2897861003875732
##

I think maybe it's your linux system is not stable and I suggest you dig deeply the requests.get() API.

**Comment by sigmavirus24** [comment]
There are also several differences in the output you provided from `python -m requests.help`.

On linux here is my information:

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.4"
  },
  "platform": {
    "release": "4.14.14-300.fc27.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1010007f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

And your requests version does not hang. This definitely supports @hk-mars' suspicion that your Linux system is the problem here.

If you need further help figuring that out, this is not the place. This is a defect tracker.
