### ISSUE TITLE
cannot load requests at all

### ISSUE THREAD

**Issue by rzvn2600** [requests/requests#4521]
Summary.

not working 

## Expected Result

able to lead requests and use it
## Actual Result

cannot use it due to the following error message:

Traceback (most recent call last):
  File "/Users/testing/Python/string.py", line 4, in <module>
    import requests
  File "/Library/Python/2.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Library/Python/2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Library/Python/2.7/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/Library/Python/2.7/site-packages/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/Library/Python/2.7/site-packages/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Library/Python/2.7/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1241, in <module>
    import ssl
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 90, in <module>
    import textwrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/textwrap.py", line 10, in <module>
    import string, re
  File "/Users/testing/Python/string.py", line 13, in <module>
    urlFile = requests.get(url)
AttributeError: 'module' object has no attribute 'get'
[Finished in 0.1s with exit code 1]
[shell_cmd: python -u "/Users/testing/Python/string.py"]
[dir: /Users/testing/Python]
[path: /Users/testing/bin:/usr/local/homebrew/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/testing/bin]
## Reproduction Steps

installing with pip and pip3:

Requirement already satisfied: requests in /Library/Python/2.7/site-packages
Requirement already satisfied: idna<2.7,>=2.5 in /Library/Python/2.7/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Python/2.7/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests)

----

Requirement already satisfied: requests in /usr/local/homebrew/lib/python3.6/site-packages
Requirement already satisfied: idna<2.6,>=2.5 in /usr/local/homebrew/lib/python3.6/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/homebrew/lib/python3.6/site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/homebrew/lib/python3.6/site-packages (from requests)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /usr/local/homebrew/lib/python3.6/site-packages (from requests)

```python
#! /usr/bin/env python3

import json
import requests

class JSONObject:
    def __init__(self, d):
        self.__dict__ = d


# for testing, this url has the appropriate data formats
url="https://raw.githubusercontent.com/kovidgoyal/build-calibre/master/scripts/sources.json"
urlFile = requests.get(url)
print('URL Return Code: ', urlFile.status_code)
print('Content Type:    ', urlFile.headers["content-type"])

#json_data = urlFile.json   # NOT WORKING
#data = json.loads(urlFile.content.decode('utf-8')) #WORKS
data = requests.get(url).json() #WORKS

### Print "name" and "unix-->filename" from json data
#for key, value in json_data.iteritems():
# something???
#   print("%s: %s", name, filename)

### later - store in python list and process

count = 3   # for testing just print first 3
for key, value in data.items():
    print('key: {}, value: {}'.format(key, value))
    count -= 1
    if count == 0:
        break

```

## System Information

{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.1.4"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.10"
  },
  "platform": {
    "release": "16.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "9081df",
    "version": "0.13.1"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "9081df"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hi @rzvn2600, this is almost certainly a result of you having a file named `requests.py` somewhere in your project or path. Since this is a request for help and not a defect in Requests, we’d ask that any follow up on this be moved to [StackOverflow](https://stackoverflow.com). Thanks!

**Comment by nateprewitt** [comment]
Correction this is your `string.py` file in the path noted in the stacktrace causing issues.

**Comment by rzvn2600** [comment]
wow, didn't see this, thanks @nateprewitt
