### ISSUE TITLE
why conversion  `sys.modules` to list??

### ISSUE THREAD

**Issue by wsqy** [requests/requests#4523]
why conversion  `sys.modules` to list??
https://github.com/requests/requests/blob/master/requests/packages.py#L10

**Comment by nateprewitt** [comment]
Hey @wsqy, thanks for the question. I don't know if there is a specific reason `sys.modules` was cast as a list other than to ensure it's iterable. It's likely something that slipped through during code review.

**Comment by sigmavirus24** [comment]
If we didn't, we'd end up modifying the object we're iterating and Python 3 would blow up. That's not idea. We also likely don't want to touch the items we are inserting into sys.modules.

This is not the place for questions of this type.
