### ISSUE TITLE
I would like to contribute.

### ISSUE THREAD

**Issue by RatanShreshtha** [requests/requests#4524]
Hey I have requests and I really love that and I would like to contribute and I think one way by which I can contribute is by type annotating the code base if this is something that I should do please help in getting started.

**Comment by nateprewitt** [comment]
Hi @RatanShreshtha, thanks so much for reaching out about contributing! We've reviewed interest in adding type annotations directly in the Requests codebase, and [decided against it in the past](https://github.com/requests/requests/issues/3855#issuecomment-277931774). I think that is probably still the case now, but I'd highly encourage you to keep an eye out for other opportunities to contribute.

**Comment by sigmavirus24** [comment]
@nateprewitt I believe @kennethreitz wants to annotate the library for v3.0.0. I think he even has a branch where he's starting that work.

**Comment by RatanShreshtha** [comment]
@sigmavirus24 How can I get started then?

**Comment by kennethreitz** [comment]
check out https://github.com/requests/requests/tree/threedotoh
