### ISSUE TITLE
Question about requests and cacert.pem

### ISSUE THREAD

**Issue by prabcs** [requests/requests#4527]
Since version 2.12.3, there have been a bunch of awesome changes done to requests till v 2.18.4.
But, 1 thing that has changed considerably is that the `cacert.pem` that used to come packaged with 2.12.3 is not available now. Hence, the alternate option is to use [`certifi.where()`](https://pypi.python.org/pypi/certifi) to find the `cacert.pem`.

But, a lot of libraries were written based on 2.12.3 and not all of them have caught up to the changes made till 2.184, especially finding the right `cacert.pem` leading to this error -
```python
 IOError: Could not find a suitable TLS CA certificate bundle, invalid path: /<path>/virtualenv/lib/python2.7/site-packages/requests/cacert.pem
```

One way to get around this problem is to fix those libraries. Few (but not all) examples -
1. https://github.com/simple-salesforce/simple-salesforce/
2. https://github.com/john-kurkowski/tldextract

This also means all those libraries should be fixed/upgraded to using the latest version of requests. https://github.com/simple-salesforce/simple-salesforce/pull/228 is an attempt in that direction. But, this may not be scalable.

But, is it somehow possible to make the libraries using the older versions of requests agnostic of the changes to requests. Something like backward compatibility. This will greatly help people using those libraries.

What does the contributor community think of this ? Maybe there could be better ways of solving backward compatibility ?
Thanks !

**Comment by sigmavirus24** [comment]
`requests.certs.where()` has always existed. In more recent versions it's just `certifi.where` imported into that namespace.
