### ISSUE TITLE
getting an Attribute Error while testing api using python

### ISSUE THREAD

**Issue by makwanaparth94** [requests/requests#4529]
hey i am facing the same isuues but not able to get where i am facing attribute errors:

[self.token= 'ywlGaT0X44WGEps98WDN8xyFMmJgfGTehKxT5heiq_A7yqa_xwM9z6s2ouB1R7LprEYaTtXoILzx713kYhvoOxQrPLsRuvEAhnHfpc0sRonNXRYJgD91P8c2_mJJJ58MYs2TiMCEXlByG2ODRrb9e5OA35l74HXAegMabFJE7GnLX_4ZCxD2EygFP8LKqamdfao66QXAmXW60nwWYOF7g3bPdQNH3eK2siY9yODd_pFJ2IpLxBiadEFvAWZj5Y'

self.headers = {'content-type': 'application/json',
'Authorization': 'token {}'.format(self.token)}

](url)getting an error like +1
def test_api_get(self):
# A get request (json example):

      response = requests.get(self.myurl, headers=self.header)

E AttributeError: 'CL_API' object has no attribute 'header'

Please give me some inputs on it

**Comment by nateprewitt** [comment]
Hi @makwanaparth94, this is an issue in your code and your use of `self`. Whatever class you’re calling this with does not have a headers attribute.

For future reference, this ticket tracker is reserved for reporting defects in Requests. Please direct any inquiries for help to [StackOverflow](https://stackoverflow.com) with the Python-Requests tag. Thanks!
