### ISSUE TITLE
Please update docs to reflect that using the json kwarg in requests results in Content-Type being set to application/json

### ISSUE THREAD

**Issue by lorenmh** [requests/requests#4538]
Wanted to make sure that the Content-Type was set to application/json when the json kwarg is used `requests.post(..., json=some_data)`, but could not find this anywhere in the documentation.

## Expected Result
Expected to find at least a short one sentence blurb about this in the documentation

**Comment by kennethreitz** [comment]
Pull requests accepted :)

**Comment by saraislet** [comment]
I'll update this!
