### ISSUE TITLE
Text nodes are cut

### ISSUE THREAD

**Issue by Soaku** [requests/requests#4540]
On one of html files I requested to a website, some html text nodes were cut.

I don't understand why is this happening, mostly because requests is not only for HTML requests right? It doesn't parse HTML. And I didn't have the problem earlier.

## Expected Result

when requested with Chrome I got 
```
<div class="thread"><a href="thread?id=272021&thread_page=1" class="mbtn mb2 attached "><img src="http://144.76.127.94/view/image/icons/chatattached_read.png" class="icon" /> [Arch][Beta] Eriah 73</a></div><div class="thread"><a href="thread?id=272286&thread_page=1" class="mbtn mb2 attached "><img src="http://144.76.127.94/view/image/icons/chatattached_read.png" class="icon" /> Modyfikacje do Sargonii</a></div><div class="thread"><a href="thread?id=272295&thread_page=1" class="mbtn mb2 attached "><img src="http://144.76.127.94/view/image/icons/chatattached_read.png" class="icon" /> [Beta] Profile Borumus</a></div>
```

Note the text nodes: `[Arch][Beta] Eriah 73`, `Modyfikacje do Sargonii`, `[Beta] Profile Borumus`

## Actual Result

Requests (both `.text` and `.content`) returned
```
<div class="thread"><a href="thread?id=272021&thread_page=1" class="mbtn mb2 attached "><img src="http://144.76.127.94/view/image/icons/chatattached.png" class="icon" /> [Arch][Beta] Eria...</a></div><div class="thread"><a href="thread?id=272286&thread_page=1" class="mbtn mb2 attached "><img src="http://144.76.127.94/view/image/icons/chatattached.png" class="icon" /> Modyfikacje do Sa...</a></div><div class="thread"><a href="thread?id=272295&thread_page=1" class="mbtn mb2 attached "><img src="http://144.76.127.94/view/image/icons/chatattached.png" class="icon" /> [Beta] Profile Bo...</a></div>
```

Note the text nodes: `[Arch][Beta] Eria...`, `Modyfikacje do Sa...`, `[Beta] Profile Bo...`

## Reproduction Steps

This script works, just note that you need first to create an account ("start game" button), otherwise game won't let you access any content. If you login in Chrome and request the url, you'll get the expected, uncut result. If you run the code below, printed result will have cut text nodes.

```python
import requests

session = requests.Session()
session.post('http://mrush.pl/login', {"name":"NICKNAME", "password":"PASSWORD"})
r = session.get("http://mrush.pl/threads?id=8993&page=1")
print(r.text)
```

## System Information

PyCharm, Windows 10, Python 3.6 with

Package | Version | Latest
-- | -- | --
certifi | 2018.1.18 | 2018.1.18
chardet | 3.0.4 | 3.0.4
colorama | 0.3.9 | 0.3.9
cssselect | 1.0.3 | 1.0.3
idna | 2.6 | 2.6
lxml | 4.1.1 | 4.1.1
pip | 9.0.1 | 9.0.1
pyquery | 1.4.0 | 1.4.0
requests | 2.18.4 | 2.18.4
setuptools | 28.8.0 | 38.5.2
urllib3 | 1.22 | 1.22

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

It's entirely likely that you need to use a different `User-Agent` header to get back the information you need. The server may be trying to stop scrapers.

**Comment by ArthaTi** [comment]
This is not a request for help and this has nothing to do with me. ~~All my debugs and checks shown that it's an issue of requests.~~

And knowing the developers of the game, they are too lazy to introduce such security. But I'll try.

Hmm... That is weird, the only page they protected against scraping is `threads`, nothing else... Changing `user-agent` worked.

**Comment by nateprewitt** [comment]
@Soaku as @Sigmavirus24 has said, this has to be something on the server side. Requests does no modification of inline content, so the fact you’re still receiving all results but the values are changing means the server is choosing to do something different.

The suggested `User-Agent` change will likely work and if you need further assistance, please open a question on StackOverflow. Thanks!

**Comment by ArthaTi** [comment]
@nateprewitt Your reply was a bit late, because I've already figured out the solution, as said in my previous post
