### ISSUE TITLE
socks5 not work for session proxies property

### ISSUE THREAD

**Issue by dust8** [requests/requests#4548]
this is not work,
```python
import requests

sess = requests.session()
proxy = 'socks5://1.1.1.1:9994'
sess.proxies = {'http': proxy, 'https': proxy}

res = sess.get('https://httpbin.org/ip', verify=False)
print(res.text)
```

but this is ok
```python
import requests

sess = requests.session()
proxy = 'socks5://1.1.1.1:9994'
proxies = {'http': proxy, 'https': proxy}

res = sess.get('https://httpbin.org/ip', verify=False,proxies=proxies)
print(res.text)
```
if requests that use socks5 too many，many port in  TIME_WAIT,how to fix it?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
