### ISSUE TITLE
[RFC for 3.0] Make `verify=False` less desireable for users

### ISSUE THREAD

**Issue by t-8ch** [requests/requests#4549]
Maybe we could use the opportunity of breaking with things in 3.0 to nag users about reverting many users behaviour of specifying `verify=False` and squelching the resulting warnings by default.

One way would be to introduce a new warning or putting `verify=False` into eternal deprecation mode.

Pros:

* May lead users to adapt their code to be more secure

Cons:

* Will probably lead to more tickets here and questions on SO
* Could be interpreted as a intentional breaking existing stuff, ill meaning
* Could lead users to inhibit all `DeprecationWarning`s by default

I am actually not completely convinced this is worth the hassle to be honest, but think it is worthy of a discussion.
(Counting a short "The heck?! no way!" as a discussion here)

Cc @sigmavirus24 @Lukasa @kennethreitz

**Comment by kennethreitz** [comment]
I intend to have no change here, personally.

**Comment by kennethreitz** [comment]
I think there are legitimate reasons to verify=False (sometimes you just legitimately don't care), and we shouldn't disempower those use cases.
