### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by Everfighting** [requests/requests#4559]
How can I deal with this error?
requests.exceptions.ConnectionError: HTTPConnectionPool(host='cloud.ocrsdk.com', port=80): Max retries exceeded with url getTaskStatus?taskId=5d9d39a9-4cd2-4528-aeeb-a1d84cc342c7 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc0f230320>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by Jackzhangpan** [comment]
@Everfighting  I encountered the same problem, how did you solve it ？
