### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by le9i0nx** [requests/requests#4563]
In the documentation it is written that so it is possible to make a request, but there is an exception.
I first tested it on version 2.12.4.
And then checked on the latest available (2.18.4).

http://docs.python-requests.org/en/stable/user/quickstart/#post-a-multipart-encoded-file

## Expected Result

Running the query

## Actual Result

TypeError: request() got an unexpected keyword argument 'file'

## Reproduction Steps

```python
import requests

payload = {"param_1": "value_1", "param_2": "value_2"}
files = {
                'json': (None, json.dumps(payload), 'application/json'),
                'file': ('log', "11" )
}
post = requests.post(API_HOST+API_URL, file=files)
print(post.content)
```

## System Information

    $ python -m requests.help

```
root@5cf05c9a3e78:/app# python3 -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.3"
  },
  "platform": {
    "release": "4.9.0-6-amd64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1010006f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by le9i0nx** [comment]
excuse me. I was inattentive

**Comment by madamadami** [comment]
I ran into the same issue — could you tell, how you worked it out?

**Comment by madamadami** [comment]
Argh, got it: the keyword is 'files', not 'file'.
