### ISSUE TITLE
Requests and urllib3 giving "bad handshake: SysCallError(-1, 'Unexpected EOF')" in a proxied environment  on a non standard port

### ISSUE THREAD

**Issue by tjs24** [requests/requests#4566]
Summary.

Are urllib3 and/or requests modules facing problems when it comes to accessing HTTP(S) service(s) on non standard ports?

## Expected Result

>python
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>import requests
>>requests.get('https://somehost.com:8443', verify=False)

InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<Response [200]>

This is what is expected

## Actual Result

What happened instead.
![image](https://user-images.githubusercontent.com/12440040/38110490-b96329ce-3350-11e8-803f-9dc3dd4220f9.png)

I have referenced these blogs:
https://www.bountysource.com/issues/30782175-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol-_ssl-c-645

https://github.com/requests/requests/issues/4272

>pip freeze
asn1crypto==0.24.0
astroid==1.6.2
attrdict==2.0.0
cachetools==2.0.1
certifi==2017.7.27.1
cffi==1.11.5
chardet==3.0.4
colorama==0.3.9
cryptography==2.1.4
future==0.16.0
idna==2.6
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
ndg-httpsclient==0.4.4
pefile==2017.11.5
pika==0.10.0
prompt-toolkit==1.0.15
protobuf==3.4.0
pyasn1==0.4.2
pycparser==2.18
Pygments==2.2.0
pylint==1.8.3
pyOpenSSL==17.5.0
python-dateutil==2.6.1
PyYAML==3.12
requests==2.18.4
six==1.11.0
urllib3==1.22
wcwidth==0.1.7
wrapt==1.10.11

>openssl version
OpenSSL 1.0.2k  26 Jan 2017

>python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2d 9 Jul 2015

## System Information

    > python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.1.4"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.0"
  },
  "platform": {
    "release": "",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010007f",
    "version": "17.5.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1000204f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

Any help would be appreciated.

**Comment by tjs24** [comment]
@Lukasa i have tried solutions on your other blogs i mentioned above and none of them worked. I just wanted a bit more guidance.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

`Unexpected EOF` means your server is closing the connection while we're trying to perform the TLS handshake. That's not a requests bug. For help with that, go to StackOverflow.
