### ISSUE TITLE
Default data should be dict, not list

### ISSUE THREAD

**Issue by kalaomer** [requests/requests#4574]
https://github.com/requests/requests/blob/e4fc3539b43416f9e9ba6837d73b1b7392d4b242/requests/models.py#L223

In request class, empty data should be dict, not list.

**Comment by sigmavirus24** [comment]
What makes you think that?

**Comment by nateprewitt** [comment]
Since we haven’t had a response and the issue is unclear I’m going to close this for now. @kalaomer feel free to reopen this with more information if you feel there’s still an issue.
