### ISSUE TITLE
docstring inconsistent with requests.api.post

### ISSUE THREAD

**Issue by YannLuo** [requests/requests#4578]
I run the `pytest tests` and find `requests.api.post` receive `data` whose type is `list_iterator`, which is inconsistent with its docstring.

## Expected Result

modify docstring of `requests.api.post` to `:param data: (optional) Dictionary (will be form-encoded), bytes,list_iterator,or file-like object to send in the body of the :class:Request.`

## Actual Result

what the docstring shows.

## Reproduction Steps

the test case is in `requests/tests/test_lowlevel.py::test_chunked_upload`, which `data` is a `iter` and passed to `requests.api.post`.

```python
import requests
def test_chunked_upload():
    """can safely send generators"""
    close_server = threading.Event()
    server = Server.basic_response_server(wait_to_close_event=close_server)
    data = iter([b'a', b'b', b'c'])

    with server as (host, port):
        url = 'http://{0}:{1}/'.format(host, port)
        r = requests.post(url, data=data, stream=True)
        close_server.set()  # release server block

    assert r.status_code == 200
    assert r.request.headers['Transfer-Encoding'] == 'chunked'
```

## System Information

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.2.2"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.5"
  },
  "platform": {
    "release": "17.5.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010008f",
    "version": "17.5.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020ef"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

**Comment by nateprewitt** [comment]
Hi @YannLuo,

Requests will take an iterable object containing bytes for the data param which is noted in [the documentation](http://docs.python-requests.org/en/master/user/advanced/#chunk-encoded-requests). We could specify in the docstring that bytes iterables work here too, but it's a more verbose explanation than proposed. I'm not sure is necessary given that bytes is specified and the specific case of chunked-encoding is defined in the docs which is what these iterators are used for.

**Comment by sigmavirus24** [comment]
I tend to agree with @nateprewitt

**Comment by nateprewitt** [comment]
It looks like we have consensus among the maintainers. It’s likely best to expose this to people specifically looking to use chunked transfer-encoding which the documentation handles. I’m going to close this since there doesn’t appear to be anything actionable, but feel free to let us know if you feel we’re missing something. Thanks!
