### ISSUE TITLE
Unable to install tensorflow 

### ISSUE THREAD

**Issue by dafinest** [requests/requests#4607]
Summary.

## Expected Result

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by dafinest** [comment]
pip install tensorflow
Collecting tensorflow
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001B1FCB5A160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))': /simple/tensorflow/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001B1FCB5A6D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))': /simple/tensorflow/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001B1FCB5A438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))': /simple/tensorflow/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001B1FCB5AA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))': /simple/tensorflow/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001B1FCB5AD30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))': /simple/tensorflow/
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Comment by sigmavirus24** [comment]
Can you share why you've filed this here? It seems that your proxy settings are incorrect.

**Comment by dafinest** [comment]
thank you for getting back....it seems l had put a proxy in my environment
that was hindering me from  installing tensorflow

**Comment by nateprewitt** [comment]
Thanks for the response @dafinest. Since it sounds like this was a configuration issue and is unrelated to Requests, I’m going to close this out.
