### ISSUE TITLE
AppVeyor builds failing on master

### ISSUE THREAD

**Issue by Stevoisiak** [requests/requests#4617]
For the past month, all pull requests to `master` have been [failing to build on AppVeyor](https://ci.appveyor.com/project/kennethreitz/requests/history).

From what I can tell, the build [started failing sometime around March 8th](https://ci.appveyor.com/project/kennethreitz/requests/build/1.0.383).

Commit https://github.com/requests/requests/commit/8f3f022c54db7c8348c84c079dfe7f7c354f1062 may have fixed the issue in the `3.0` branch, but the fix does not seem to have been merged to `master`.

## Expected Result

Pull requests should report a successful build.

## Actual Result

All pull requests report a build status of failure.

## Reproduction Steps

1. Submit a pull request to `master`.
2. Wait for AppVeyor to finish building
3. [Check the build status](https://github.com/requests/requests/pull/4616).

**Comment by nateprewitt** [comment]
Hi @Stevoisiak, thanks for reporting this. We have a solution to address this in #4620.

**Comment by Stevoisiak** [comment]
@nateprewitt This issue is [still occurring](https://github.com/requests/requests/pull/4616) after the merge of #4620.

**Comment by Stevoisiak** [comment]
@nateprewitt This seems to have fixed Appveyor, but now it looks like [Travis CI builds](https://github.com/requests/requests/pull/4616) may be failing.

**Comment by nateprewitt** [comment]
@Stevoisiak, yes, we're aware. This is an issue with the recent release of Flask 1.0.1 which broke some pieces of the testing infrastructure due to external dependencies. It's currently being tracked in requests/httpbin#442.

**Comment by Stevoisiak** [comment]
@nateprewitt Thank you for the update. Closing this as resolved by #4620.
