### ISSUE TITLE
Booleans in form data are being incorrectly encoded in post requests

### ISSUE THREAD

**Issue by dteh** [requests/requests#4628]
When sending form data, values which are booleans are encoded as "True" and "False" as opposed to "true" and "false". This is because of the urllib.parse.urlencode function.
Perhaps it is non standard to pass a boolean as form data, but I think this is non obvious to regular users. Maybe it should raise an exception or perform a conversion to lowercase.
 
## Expected Result
```
>>> data = {"key": True, "key2": "true"}
>>> req = requests.post("http://www.google.com", data=data)
>>> req.request.body
'key=true&key2=true'
```
## Actual Result
```
>>> data = {"key": True, "key2": "true"}
>>> req = requests.post("http://www.google.com", data=data)
>>> req.request.body
'key=True&key2=true'
```

## Reproduction Steps

Pass a dictionary with a key/value pair with a boolean value to the data param of a post.

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates. I'm not going to go find the duplicates right now. Given all of the possible representations of "True" on the internet, we can't really just pick one. Further, we rely on the stdlib to provide the serialization for this particular content type so we don't even do this directly. You should be thinking about how you want to pre-process the data you send. Feeding everything into requests and expecting it to magic its way to what you want isn't reasonable.
