### ISSUE TITLE
Content-Length is not correct while sending post request

### ISSUE THREAD

**Issue by zhanglue** [requests/requests#4653]
Hello~
I find the "REAL" CL, by 'tcpdump' the server host, is not according to the 'body data'.
The type of data is serialized protobuf string, and I have specified it in headers as "'Content-type': 'application/x-protobuf'".

Known point:
1. Content-Length(ab. CL) will be replaced even if it is specified in "headers".
2. CL can be set arbitrarily by Session.

After times of failed trying, I send the same PB string by 'httplib' instead, which works well.
Comparing the data dumped by tcpdumps, it seems like that data server received has been modified by 'requests' , while 'httplib' did not, even if the string dumped is not human readable.

So I found I did it in a wrong way, the point is how to send bytes string by 'requests' but how to set CL.
Right?

**Comment by zhanglue** [comment]
I tired another way to send data in post: 
```
...
files = {
        'field_A': (
            'fileName_A', 
            open('./pbFile.data', 'rb'),
            'application/x-protobuf', 
            )
        }
response = requests.post(url, headers = headers, files=files)
```
It does not work either.

**Comment by sigmavirus24** [comment]
Please provide us with the output of

```
python -m requests.help
```

If that is unavailable on your version of Requests please provide some basic information about your system (Python version, operating system, etc).

We also need a complete example to reproduce with

**Comment by zhanglue** [comment]
Sorry, I missed the env, and can't reproduce again......
