### ISSUE TITLE
Requests to groupon 403 response

### ISSUE THREAD

**Issue by GinVlad** [requests/requests#4656]
`import requests as re
headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
}

r = re.Session()
print r.get('https://www.groupon.com/signup?ref=https%3A%2F%2Fwww.groupon.com%2Fmyaccount', headers=headers)`

I receive 403 response. How to pass it

**Comment by nateprewitt** [comment]
Hi @GinVlad, this looks like a request for help. As per our issue tracker guidelines, requests for help should be directed to [StackOverflow](https://stackoverflow.com). You can use the `python-requests` tag to better surface the question. Thanks!
