### ISSUE TITLE
KeyError: 'csrf' or 'csrftoken' on python3 with osx

### ISSUE THREAD

**Issue by hamadberlin** [requests/requests#4662]
hey folks,

tying to run this command with python3:

#update csrf token for the first time
		sess.headers.update({'X-CSRFToken' : sess.get('https://www.instagram.com/accounts/login').cookies.get_dict()['csrf']})

or

#update csrf token for the first time
		sess.headers.update({'X-CSRFToken' : sess.get('https://www.instagram.com/accounts/login').cookies.get_dict()['csrftoken']})

i changed it many times but it wont work... even not with url 'www.instagram.com'

Result:
[*] Loading proxies
[*] Proxy: <Proxy IE 0.19s [HTTP: Transparent, HTTPS] 54.36.31.204:3128>
[*] 43113 passwords loaded successfully
Traceback (most recent call last):
  File "hackinsta.py", line 178, in <module>
    bruteforce.login()
  File "hackinsta.py", line 128, in login
    sess.headers.update({'X-CSRFToken' : sess.get('https://www.instagram.com/accounts/login').cookies.get_dict()['csrf']})
KeyError: 'csrf'

how can i fix that?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by Thilip00** [comment]
![Screenshot_2020-06-15-21-55-17-097_com termux](https://user-images.githubusercontent.com/66963067/84682209-f15ffc00-af52-11ea-9d3c-78b7bded9f57.jpg)
How to solve this..?? Pls help me

**Comment by Rajarv7** [comment]
> hey folks,
> 
> tying to run this command with python3:
> 
> #update csrf token for the first time
> sess.headers.update({'X-CSRFToken' : sess.get('[https://www.instagram.com/accounts/login').cookies.get_dict()['csrf']}](https://www.instagram.com/accounts/login').cookies.get_dict()%5B'csrf'%5D%7D))
> 
> or
> 
> #update csrf token for the first time
> sess.headers.update({'X-CSRFToken' : sess.get('[https://www.instagram.com/accounts/login').cookies.get_dict()['csrftoken']}](https://www.instagram.com/accounts/login').cookies.get_dict()%5B'csrftoken'%5D%7D))
> 
> i changed it many times but it wont work... even not with url 'www.instagram.com'
> 
> Result:
> [_] Loading proxies [_] Proxy: <Proxy IE 0.19s [HTTP: Transparent, HTTPS] 54.36.31.204:3128>
> [*] 43113 passwords loaded successfully
> Traceback (most recent call last):
> File "hackinsta.py", line 178, in 
> bruteforce.login()
> File "hackinsta.py", line 128, in login
> sess.headers.update({'X-CSRFToken' : sess.get('[https://www.instagram.com/accounts/login').cookies.get_dict()['csrf']}](https://www.instagram.com/accounts/login').cookies.get_dict()%5B'csrf'%5D%7D))
> KeyError: 'csrf'
> 
> how can i fix that?

**Comment by harricxbyte** [comment]
> ![Screenshot_2020-06-15-21-55-17-097_com termux](https://user-images.githubusercontent.com/66963067/84682209-f15ffc00-af52-11ea-9d3c-78b7bded9f57.jpg)
> How to solve this..?? Pls help me

Hey, send me your Instagram ID I'll explain it their

**Comment by sethmlarson** [comment]
Please find another place to have this discussion.
