### ISSUE TITLE
requests package issue in pip10 version

### ISSUE THREAD

**Issue by felsen** [requests/requests#4663]
When I try to uninstall requests package using pip10, below error I am getting.

Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by sigmavirus24** [comment]
That's interesting given that requests uses [setuptools](https://github.com/requests/requests/blob/00fd4c8eb4ac0fd7b8f8d76bbf15ab06351c052c/setup.py#L10) and has for years now. It sounds like the version of requests you have must be incredibly old.

**Comment by felsen** [comment]
Yes, It works in the latest version of requests==2.18.4.
