### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by janitabose** [requests/requests#4666]
i get this error every time i try to extract tweets. Can anyone please help:

ConnectionError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000205A1A33DA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
