### ISSUE TITLE
idna version pin does not allow version 2.7

### ISSUE THREAD

**Issue by jakul** [requests/requests#4681]
`idna` have just released 2.7. `requests` is pinned to `idna>=2.5,<2.7`

https://github.com/requests/requests/blob/d1aeb7ea8cec833e61ea390a6c19ef8b7ac3e4e7/setup.py#L53

Can the pin be updated to allow v2.7?

**Comment by nateprewitt** [comment]
Hi @jakul, this is addressed (generally, replace "urllib3" with "idna") in https://github.com/requests/requests/issues/4673#issuecomment-395069592. We'll update our version pins in the next release of Requests (which will likely be this week). Thanks for letting us know!

**Comment by prometheanfire** [comment]
hitting it in openstack as well now.

http://logs.openstack.org/40/574140/2/check/requirements-tox-py27-check-uc/7a0ed61/job-output.txt.gz#_2018-06-11_17_06_11_715280

**Comment by nateprewitt** [comment]
Alright, 2.19.0 is out the door! Closing this out since it should be resolved now.
