### ISSUE TITLE
Multiple POST requests, second request gets a 404 error code

### ISSUE THREAD

**Issue by nwadeit** [requests/requests#4691]
Hello, I am new to python and am having this same issue. I am trying to authenticate to a website that redirects you to a security question after the initial login. Both the initial login and subsequent page use the same "action URL" and on the second post request I am receiving a 404, here is my code, any help would be greatly appreciated:

```python
from bs4 import BeautifulSoup as bs
import requests
import time
sources = ["https://www.dandh.com/v4/view?pageReq=dhMainNS"]
req = requests.Session()


def login():
    authentication_url = "https://www.dandh.com/v4/dh"

    header = {"user-agent": "Mozilla/5.0 (Windows NT 10.0; rv:60.0) Gecko/20100101 Firefox/60.0"}

    payload = {"Login": "12345",
               "PW": "12345",
               "Request": "Login"}

    payload2 = {"securityAnswer": "12345",
                "Request": "postForm"}

    req.post(authentication_url, data=payload, headers=header)

    time.sleep(3)

    req.post(authentication_url, data=payload2, headers=header)

    time.sleep(3)
   

def print_object(sources):
    for url in sources:
        soup_object = bs(req.get(url).text, "html.parser")
        print(soup_object.get_text())


def main():
    login()
    print_object(sources)

main()
```

**Comment by nateprewitt** [comment]
Hi @mwadiet,

This looks like it’s a request for help rather than a report of a defect in Requests. What you’re describing is a behavior of the server which isn’t related to Requests. If you open a question on [StackOverflow](https://stackoverflow.com), you should be able to get some guidance on how to approach the problem.

Thanks!

**Comment by nwadeit** [comment]
I appreciate the response, i only posted it on their because there was a previous post that the developers acknowledged as a bug in requests. Where doing a get or post would return a 200 status code and then a 404 immediately after on the second request

**Comment by sigmavirus24** [comment]
Nope. It was never acknowledged as a bug. That was a thing we were tracking and found a work around for with the specific service. This is likely a problem with the service you're talking to
