### ISSUE TITLE
Backslash char in Unicode encoded characters becomes a double backslash

### ISSUE THREAD

**Issue by ringods** [requests/requests#4693]
We have an application which returns JSON responses. In such a response document, some string values could have encoded Unicode characters like `\u003C` (<) or `\u003E` (>). But `requests` seems to "process" this return value.

## Expected Result

Simplified version of my response JSON:

```
{ "key": "\u003CSome Text Here\u003E" }
```

## Actual Result

```
{ "key": "\\u003CSome Text Here\\u003E" }
```

The single backslash becomes a double backslash. I don't have this with plain `curl` or the Insomnia Mac REST client app.

## Reproduction Steps

Set up an nginx server serving document `encoded.json` with content:

```json
{
    "key": "\u003CSome text here\u003E"
}
```

Instructions:
```
$ docker pull nginx
$ docker run --name json-server -p:8080:80 -v `pwd`:/usr/share/nginx/html:ro -d nginx
```

In a Python shell:

```python
>>> import requests
>>> r = requests.Session()
>>> response = r.get('http://localhost:8080/encoded.json')
>>> response.headers
{'Server': 'nginx/1.15.0', 'Date': 'Tue, 19 Jun 2018 08:21:05 GMT', 'Content-Type': 'application/json', 'Content-Length': '44', 'Last-Modified': 'Tue, 19 Jun 2018 08:07:58 GMT', 'Connection': 'keep-alive', 'ETag': '"5b28b9de-2c"', 'Accept-Ranges': 'bytes'}
>>> response.encoding
>>> response.content
b'{\n    "key": "\\u003CSome text here\\u003E"\n}\n'
>>> response.text
'{\n    "key": "\\u003CSome text here\\u003E"\n}\n'
```

Note that `response.encoding` is not set.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.4"
  },
  "platform": {
    "release": "17.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "100020ff"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": false
}
```

Also doesn't work with urllib 1.22 and requests 2.18.4.

**Comment by AndCycle** [comment]
well, that's not requests's fault, that's because you `print` it out, python escape that if you print it.
just write the content to file and you will get what you want.

**Comment by ringods** [comment]
@AndCycle thanks for putting me on the right track.

First of all, I find it very confusing that Python prints the double escaped version. This put me on the wrong track.

But eventually, I am using `response.content.decode('unicode-escape')` as my solution. `response.text` does not perform this type of decoding it seems.
