### ISSUE TITLE
Getting size of performed request

### ISSUE THREAD

**Issue by pbaranski** [requests/requests#4694]
I want to find out what is the size of performed request - is it possible in requests library?

## Expected Result

in my dreams:

```
response.request.size()
```

## Actual Result

not apply

## Reproduction Steps

What I should consider manually computing this value. Header, querystring, body (if apply)?
Does below cod reflect bytes sent to server

```
sys.getsizeof(response.request)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.5"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}

```

**Comment by nateprewitt** [comment]
Hi @pbaranski,

Requests is in a feature freeze, so I don't know if we'd introduce a `size()` method to the `Request` object.

If your definition of "size" is bytes sent over the wire, I'm not sure that `sys.getsizeof(response.request)` expresses that. You can find the definition/layout of an http message in [RFC7230 section 3](https://tools.ietf.org/html/rfc7230#section-3). This is what will be sent when you issue the Request. A rough outline is:

```
GET /path/to/my/resource HTTP/1.1\r\n
Accept: */*\r\n
Content-Type: text/plain\r\n
Content-Length: 43\r\n
Connection: keep-alive\r\n
User-Agent: MyUserAgent1.2.3\r\n
\r\n
Dear Server,

I hate your stinking guts...
```

That should be 193 bytes across the wire including the request line, headers, and uncompressed body. There are a few different ways you could slice this depending on what you're trying to measure, but this is the general idea.

If you have further questions, let's move this to [StackOverflow](https://stackoverflow.com) with the `python-requests` tag. We typically reserve the github tracker for reports about defects in Requests. Thanks!

**Comment by pbaranski** [comment]
@nateprewitt Thanks for answer, is partially explains what I was after. Before i posted question here I made SO question what is available here  [https://stackoverflow.com/questions/50908813/python-requests-figuring-out-request-full-size](https://stackoverflow.com/questions/50908813/python-requests-figuring-out-request-full-size ) . I will try to post findings from your response to SO thread.
Cheers
