### ISSUE TITLE
Documentation for response.json() wrong

### ISSUE THREAD

**Issue by l0rb** [requests/requests#4695]
## Summary

When calling response.json() on a response where the content is not valid json a JSONDecodeError bubbles up from the json library, although the documentation claims a ValueError should occur for that

## Expected Result

ValueError

## Actual Result

JSONDecodeError

## Reproduction Steps

```python
import requests

response = requests.Response()
response.json()
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.3"
  },
  "platform": {
    "release": "4.9.0-6-amd64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1010006f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @l0rb,

`JSONDecodeError` is a subclass of `ValueError`. It will be returned by the `json` module response in Python3 in some cases, but doesn't exist in Python2. For code compatible across both versions, or Python 3 code that's compatible in all cases, you'd want to be excepting the `ValueError`.
