### ISSUE TITLE
response.json() is failing enconding for non ascii characters

### ISSUE THREAD

**Issue by maufonfa** [requests/requests#4702]
Summary.
I'm executing a simple GET request with a list of data. But the .json() fails because there's a non ascii character and it can't encode it.

## Expected Result

[
  {
    "key": "value"
  }
]

## Actual Result
*** UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 329: ordinal not in range(128)

## Reproduction Steps

Try to pass this type of character (In this case is the "ü") in a request and then try to convert the response to json using response.json() 

```python
import requests

response = requests.request("GET", ulr, headers=headers)
response.json()
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "3.10.0-327.13.1.el7.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "1000114f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Requests uses the standard `json` library. Your alternative here is to do

```py
json.loads(response.text)
```

That should exhibit exactly the same problem. This is not a bug in requests. Note that the `json()` method on a `Response` allows you to pass in extra keyword arguments. Those correspond to arguments one might pass to `json.loads()`.
