### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ikrambennasrbennasr** [requests/requests#4714]
Hello ; please i run this code :

import json
import requests
url = "http://add_server"
data = json.dumps({'sl':5.84,'sw':3.0,'pl':3.75,'pw':1.1})
r = requests.post(url,data)
print(r.json)

and i get this error : 
<bound method Response.json of <Response [500]>>
 

and when i run this code : 
import json
from pprint import pprint
import requests
url = "http://add_server"
data = json.dumps({'sl':5.84,'sw':3.0,'pl':3.75,'pw':1.1})
r = requests.post(url,data)
pprint(r.json)

i get this error: 

JSONDecodeError Traceback (most recent call last)
in ()
4 data = json.dumps({'sl':5.84,'sw':3.0,'pl':3.75,'pw':1.1})
5 r = requests.post(url,data)
----> 6 print(r.json())

~/anaconda3/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
890 # used.
891 pass
--> 892 return complexjson.loads(self.text, **kwargs)
893
894 @property

~/anaconda3/lib/python3.6/json/init.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
352 parse_int is None and parse_float is None and
353 parse_constant is None and object_pairs_hook is None and not kw):
--> 354 return _default_decoder.decode(s)
355 if cls is None:
356 cls = JSONDecoder

~/anaconda3/lib/python3.6/json/decoder.py in decode(self, s, _w)
337
338 """
--> 339 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
340 end = _w(s, end).end()
341 if end != len(s):

~/anaconda3/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
355 obj, end = self.scan_once(s, idx)
356 except StopIteration as err:
--> 357 raise JSONDecodeError("Expecting value", s, err.value) from None
358 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any help please. Thanks

**Comment by Aguvster** [comment]
Hey, I'll address both of the problems.
1. You write `print(r.json)` but `r.json` is a method, so instead you should write `print(r.json())`.
2. I got a little confused with what's going on here, but the thing is that the response is not a valid json (HTTP status code of 500), therefore you can't access `r.json()`.
**I think an informative exception should be raised in this case.**

Try to get a response with the HTTP status code of 200 and see if it works.

**Comment by sigmavirus24** [comment]
>  I think an informative exception should be raised in this case.

What's more informative than `JSONDecodeError` meaning we literally can not decode any JSON from this.

A response with a status code of 500 may return valid JSON. It may not. It's up to the user to know whether that's the case and call `response.json()` accordingly. `response.json()` being called with reckless abandon is about as likely to work as the user doing `import json; json.loads(response.text)` with the same amount of though.
