### ISSUE TITLE
Getting response content starting with  b

### ISSUE THREAD

**Issue by shiveshabhishek** [requests/requests#4724]
Summary.
In output of content of a response , it is getting printed with starting as **b**
## Expected Result
No **b** at the starting of output
What you expected.
No **b** at the starting of output
## Actual Result
output without **b** at the beginning
What happened instead.
![image](https://user-images.githubusercontent.com/29581152/42371314-bbf171b2-812c-11e8-8eb6-cf48850c16e0.png)

## Reproduction Steps
Just print any output like : response.content
```python
import requests

```

## System Information

Linux Ubuntu 18.06
python version:3.6.5

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
You likely want `response.text` then if you don't want the content as raw bytes but instead as a string.

This is not a bug.

**Comment by shiveshabhishek** [comment]
ohh, i see.. I thought that it's showing improper response.
Thanks for correcting my issue @sigmavirus24
