### ISSUE TITLE
Header string values are changed to lower-case even though required to be case-sensitive by RFC-2017

### ISSUE THREAD

**Issue by klindt** [requests/requests#4729]
Summary.

To create a redirect resource within a Fedora4 Common repository (https://wiki.duraspace.org/display/FEDORA4x/RESTful+HTTP+API#RESTfulHTTPAPI-external-content) you'll have to use a PUT header involving  Content-Type header "message/external-body" (defined in  https://tools.ietf.org/html/rfc2017).
Request changes the character case of the Content-Type header "message/external-body". The URL Parameters must be send in upper-case form but request changes it to lower-case.

## Expected Result

Header will be send as _stated_:
{'Content-Type': 'message/external-body; access-type=URL; URL="http://example.com"'}

## Actual Result

The string "URL=" in the header has been changed to "url=":
_Server Response_

Invalid Content Type message/external-body;access-type=URL;url="http://example.com"

## Reproduction Steps

```python
import requests

 headers = {  
  'Content-Type': 'message/external-body; access-type=URL; URL="http://example.com"' 
 }


```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "4.4.0-124-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": false
}

```

**Comment by nateprewitt** [comment]
Hi @klindt,

I don't believe this is the product of Requests. We shouldn't be doing any mutating of the header values, only keys which is allowable for normalization.

Here's a simple repro showing we maintain the casing:
```python
import requests

headers = {
    'Content-Type': 'message/external-body; access-type=URL; URL="http://example.com"'
}
r = requests.get('https://httpbin.org/get', headers=headers)
print(r.json()['headers']['Content-Type'])
```

My guess would be that you either have a proxy between you and your target server which is manipulating the request, or something else in your code base is tampering with the values. Without other information pointing towards a defect in Requests, I don't know if we can go much further here.
