### ISSUE TITLE
Why does Python not use the system certs?

### ISSUE THREAD

**Issue by mark0978** [requests/requests#4734]
I've seen https://github.com/requests/requests/issues/4463 but I'm wondering why the system level certs are not used.  I know it has "never" done it, but why?  Is the problem related to supporting multiple platforms, or is there another reason?

I've just run into a problem where the IT dept was doing a MITM on their workers, and had loaded a cert that Chrome was using.  I could export that cert and put it in a linux vm pretty easily and fix CURL, but putting that same cert into the certifi file generated errors about the issuer and serial number.

This might be an question for a different package, if so, just let me know and I'll happily quiz them.  I'm torn as to whether this is a urllib3 issue or a requests issue.

**Comment by sigmavirus24** [comment]
https://github.com/requests/requests/issues/2966
