### ISSUE TITLE
Add Status Code Constants As A Module

### ISSUE THREAD

**Issue by ndibari-sp** [requests/requests#4738]
It would be nice if requests had a module that housed all the possible status codes for an HTTP request in the package. That way users can utilize the constants defined in the module instead of hard coding magic numbers for testing/status code checking/etc. The django rest framework library has a similar feature to this, http://www.django-rest-framework.org/api-guide/status-codes/

This could be called something like `requests.status`, with the `status` module providing human-readable names for the different status codes:

```python
HTTP_OK = 200
HTTP_NOT_FOUND = 404
HTTP_SERVER_ERROR = 500
# You get the idea
```

**Comment by kennethreitz** [comment]
`requests.codes`.

**Comment by ndibari-sp** [comment]
Thanks @kennethreitz I didn't know that was a thing
