### ISSUE TITLE
Response.content returns the gzip compressed file

### ISSUE THREAD

**Issue by bobos008** [requests/requests#4742]
Response.content has not been unzip

Response.content has not been unzip
Hello, please ask a question, other website requests are basically decompressed, but when you request this URL(https://www.betburger.com/users/sigin_in), you return the compressed string.
=======================code============================
# coding=utf-8

import requests

url = 'https://www.betburger.com/users/sign_in'
headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'zh-CN,zh;q=0.9',
    'cookie': '__cfduid=dc9505fc253be4d1f40fc6158900b6cb11531922677; cookieconsent_dismissed=yes; abb_web_session=7a9d700e75ad796a695cfad024c93989; _ga=GA1.2.1097857175.1531980113; _gid=GA1.2.765234195.1531980113; _gat_UA-113146417-2=1; _gat_UA-35300177-2=1',
    'referer': 'https://www.betburger.com/',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36'
}
rp = requests.get(url, headers=headers)
print rp.content
================================================

**Comment by xqs42b** [comment]
sos

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by SevenJoker** [comment]
@sigmavirus24 The response header content(content encoding:gzip) is missing
Construct a request by requests moudle,the response header is : 
{
    "Server":"nginx",
    "Date":"Mon, 19 Nov 2018 07:10:00 GMT",
    "Content-Type":"text/html; charset=UTF-8",
    "Transfer-Encoding":"chunked",
    "Connection":"keep-alive",
    "Vary":"Accept-Encoding",
    "Access-Control-Allow-Origin":"http://runapi.showdoc.cc"
}

but,The original response header is : 
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 19 Nov 2018 07:15:20 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Access-Control-Allow-Origin: http://runapi.showdoc.cc
Access-Control-Allow-Credentials : true
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Encoding: gzip

Content-Encoding:gizp  is missing,The gzip file cannot be decompressed automatically,so   response.text  is garbage characters
