### ISSUE TITLE
Link to donate for requests for py3 isn't working

### ISSUE THREAD

**Issue by cgthayer** [requests/requests#4743]
Summary.

link to support requests for py3 isn't working at the top of 
http://docs.python-requests.org/en/master/
leads to https://www.kennethreitz.org/requests3

What you expected.

a website

What happened instead.

404

```python
import requests

```

## System Information

    $ python -m requests.help

```
404
```

Thanks

**Comment by sigmavirus24** [comment]
@kennethreitz this is a bug in your website redesign and URL routing

**Comment by kennethreitz** [comment]
Need to bring the death clock back — or remove the banner entirely.

**Comment by sigmavirus24** [comment]
@kennethreitz #4767 because people are still looking for that page. I've also received emails asking for updates on the progress and spend of that money. I can't answer to either of those. Please either bring the page back and add updates or figure something else out.
