### ISSUE TITLE
error on "pip install requests" with chardet

### ISSUE THREAD

**Issue by mhndm** [requests/requests#4754]
Summary.
pip install requests
Collecting requests
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests) (2.6)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests) (1.22)
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests) (2017.11.5)
Installing collected packages: chardet, requests
  Found existing installation: chardet 2.0.1
Cannot uninstall 'chardet'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
## Expected Result

success install

## Actual Result

not installed

## Reproduction Steps

```python
import requests

```

## System Information
ubuntu 14.04
python 2.75

**Comment by sigmavirus24** [comment]
This is likely an issue with you having system package manager installed packages and then trying to globally reinstall those packages with pip. This is not an issue with Requests or chardet, but with what you're attempting to do. You've also not provided the information we request as part of an issue to help you debug, so there's no further work we will do here. I suggest you perform more online searching to find the appropriate solution.
