### ISSUE TITLE
JSON response has double-quotes replaced by single-quotes

### ISSUE THREAD

**Issue by DavidFriedmanAMD** [requests/requests#4761]
I am trying to develop a Python3 script to query GitHub for data on specific repositories, using their v4 GraphQL API with results in JSON format. I took a sample query from the GitHub developer pages, and embedded it into the attached script "github-graphql-test.py" based on a (referenced) example found in a Web search.

The expected output is in the attached file "query-result.txt".

The script produces this result with output piped thru json.tool, but only if all single-quotes are replaced by double-quotes (see commented-out "print" at end of script). Otherwise json.tool gives the error

"Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"

Evidently the JSON formatting on the output is replacing double with single quotes. Is this possibly happening in the requests module, or in another part of the Python library?

[github-graphql-test.py.txt](https://github.com/requests/requests/files/2275998/github-graphql-test.py.txt)
[query-result.txt](https://github.com/requests/requests/files/2275999/query-result.txt)

**Comment by nateprewitt** [comment]
Hi @DavidFriedmanAMD, the `json()` method is going to return a python representation of the JSON data (i.e. a dictionary) which won’t use double quotes. If you need a valid JSON string with double quotes, you would need to use the json module and call json.dumps, or simply pass the response.content which should be valid json.

**Comment by jeffreyscottgraham** [comment]
Code showing how to convert the unbelievably wrongly named 'json' (because it is NOT LEGAL JSON) response into real, proper json?
