### ISSUE TITLE
HTTPSConnectionPool, SOCKSHTTPSConnectionPool errors

### ISSUE THREAD

**Issue by JonhSilver** [requests/requests#4770]
Using this code a long time, but few month ago, it started to craching with error
--------------------------------------
```
import requests

def get_tor_session():
	session = requests.session()
	session.proxies = {'http':  'socks5://127.0.0.1:9150',
					   'https': 'socks5://127.0.0.1:9150'}
	return session

requests.packages.urllib3.disable_warnings()
session = get_tor_session()
IpUrl = 'https://api.ipify.org'
TorResponse  = session.get(IpUrl)
print('tor ip: {}'.format(TorResponse.text.strip()))
```
--------------------------------------------------------------

Error:

`HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error(10053, 'An established connection was aborted by the software in your host machine')))`
----------------------------
if clear all proxy fields in internet explorer options, got another error:

`SOCKSHTTPSConnectionPool(host='', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0383A1F0>: Failed to establish a new connection: 0x05: Connection refused',))`
-----------------------------

changing socks5:// to socks5h:// make error:
`ValueError: Unable to determine SOCKS version from socks5h://127.0.0.1:9150`

------------------------

`c:\Python27>pip show requests
Name: requests
Version: 2.19.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: c:\python36\lib\site-packages
Requires: idna, chardet, urllib3, certifi
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

c:\Python27>pip show urllib3
Name: urllib3
Version: 1.23
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: c:\python36\lib\site-packages
Requires:
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.`

Installed requests[socks], ssl and everithig else available in internet
Directly in Tor browser all site links opening ok
------------------------------

How to solve problem?

**Comment by nateprewitt** [comment]
Hi @JonhSilver, this appears to be a request for help. The information provided points towards a possible issue with your proxy which is outside of the scope of Requests. These kinds of questions for specific setups should be directed to [StackOverflow](https://stackoverflow.com) since we reserve the use of this issue tracker for defects in Requests.

If you can provide an isolated example of this issue and which version of Requests it breaks between, we may be able to investigate more. Until then I'm going to close this out. Thank you!
