### ISSUE TITLE
Support for HTTP reason phrases

### ISSUE THREAD

**Issue by MattSGS** [requests/requests#4786]
This could arguably be classified as a bug rather than a feature request.

Requests doesn't, as far as I can see, supply an API to return the server's HTTP reason phrase. What it instead supplies is an API that will return its own stringification of the server's HTTP status code.

While in many cases these will probably be the same, I am writing a reverse proxy, so I want to return to my client **exactly** what the origin server supplied to me.
For example, if the origin server said "200 Everything Is Awesome" instead of the more common "200 OK", then I want to return precisely "Everything Is Awesome" (not "OK") to my client in my reason phrase.

Note that the HTTP RFCs permit origin servers to supply custom reason phrases:

> The reason phrases listed here are only
>    recommendations -- they MAY be replaced by local equivalents without
>    affecting the protocol.

By my reading, the HTTP RFCs permit anyone to supply any bytes they like other than CR and LF in this 'reason phrase', and still comply with HTTP.

**Comment by MattSGS** [comment]
My point in that last paragraph is that I don't see a way in the RFCs for the server to specify a character set or encoding for its "reason phrase", yet arbitrary bytes seem to be permitted, so either this should be exposed as Python bytes not a Python string, or perhaps there should be a documented WONTFIX bug that the encoding is always assumed to be ASCII-7, or one of the ISO8859 extended ASCIIs, or maybe UTF-8.

**Comment by sigmavirus24** [comment]
We pull the `Response.reason` attribute from urllib3's Response. That said,

> Requests doesn't, as far as I can see, supply an API to return the server's HTTP reason phrase.

Is clearly wrong.

```py
Python 3.6.5 (default, Mar 29 2018, 18:20:46) 
[GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get("https://httpbin.org/status/418").reason
"I'M A TEAPOT"
```

And I can assure you that's not a standard reason. You can also access the original reason phrase from urllib3:

```py
>>> requests.get("https://httpbin.org/status/418").raw.reason
"I'M A TEAPOT"
>>> 
```
