### ISSUE TITLE
multiline header should be supported!

### ISSUE THREAD

**Issue by alkino** [requests/requests#4796]
Hi everybody.
Yes I read it #4216 

It ends with @Lukasa quoting specification.
But if we read this [specification](https://tools.ietf.org/html/rfc7230#section-3.2.4) a bit further:

> A user agent that receives an obs-fold in a response message that is
> not within a message/http container MUST replace each received
> obs-fold with one or more SP octets prior to interpreting the field
> value.

So it MUST be supported, no?

Regards

**Comment by Lukasa** [comment]
No.

*Receiving* them is a MUST, emitting them is a MUST NOT.

**Comment by alkino** [comment]
For my part I want to receive them.

I got this backtrace:

``
