### ISSUE TITLE
Consider not using single char variables in docs

### ISSUE THREAD

**Issue by claudijd** [requests/requests#4799]
**Summary.**

I was debugging a requests example from the website here (http://docs.python-requests.org/en/master/) and was in a PDB session.  Went to inspect "r" by typing "r" and <enter> it did not reference the variable "r".

**What you expected.**

I expected that it would return the object R

**What happened instead.**

It returned to the next method, because PDB uses hotkeys.

```python
import requests
r = requests.get('https://api.github.com/user', auth=('user', 'pass'))
import pdb; pdb.set_trace()
```
Then type 'r' in PDB session, will return instead of instance of 'r'.

**Suggestion.**

Update the docs to not use single-char variables.  I would have sent a PR, but wanted to start here, as it's more emergent behavior of using PDB and single char vars then a direct requests issue, but is reflected in your examples.

**Comment by nateprewitt** [comment]
Hi @claudijd, thanks for starting the conversation. While we want to make sure the documentation is easily accessible, I’m not sure this warrants a change. PDB has specifically added syntax to handle this issue. Whenever you’re printing a variable in the console, you should be prefixing it with an ! (e.g. !r) to avoid conflicts.

Given that we cannot control how other tools behave, the new variable could fail elsewhere and we’ll have to continue changing it. For those reasons, I think we’ll pass on this.

**Comment by claudijd** [comment]
Thanks @nateprewitt

**Comment by claudijd** [comment]
@nateprewitt just for the sake of argument, should the docs then use the "!r" syntax as you suggest?

**Comment by claudijd** [comment]
You'll end up with collisions with 'r.status_code' as well.

**Comment by claudijd** [comment]
>>> import requests
>>> r = requests.get('https://api.github.com/user', auth=('user', 'pass'))
>>> import pdb; pdb.set_trace()
--Return--
> <stdin>(1)<module>()->None
(Pdb) r
>>> r.status_code
--Call--
> <stdin>(1)<module>()->None
(Pdb) exit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 50, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 83, in dispatch_call
    if self.quitting: raise BdbQuit
bdb.BdbQuit

**Comment by sigmavirus24** [comment]
@claudijd no it shouldn't. The examples are (mostly) shown as if you've opened a python prompt, e.g., 

```
$ python
>>> import requests
>>> r = requests.get('https://httpbin.org/get')
>>> r
```

Not PDB
