### ISSUE TITLE
How to set requests 'user-agent' header globally

### ISSUE THREAD

**Issue by beruhan** [requests/requests#4806]
I want to set requests 'user-agent' header globally,But I can't find any way to do it,Can anyone help me?

**Comment by therumbler** [comment]
Read the documentation: http://docs.python-requests.org/en/master/user/advanced/

```
s = requests.Session()
s.headers.update({'x-test': 'true'})

# both 'x-test' and 'x-test2' are sent
s.get('http://httpbin.org/headers', headers={'x-test2': 'true'})
```

**Comment by nateprewitt** [comment]
Hi @beruhan, @therumbler is correct. For future reference, we use the issue tracker for defects in Requests. Questions and requests for assistance should be directed to StackOverflow.com with the python-requests tag. Thanks!

**Comment by aadibajpai** [comment]
Long time later, but is there a way to set the user agent even for implicit requests? Like if I use a function from a library that makes a request, then it won't fall under the Session if I go that way. What would be the way in that case?

**Comment by sigmavirus24** [comment]
@aadibajpai Quoting literally the last comment here:

> Questions and requests for assistance should be directed to StackOverflow.com with the python-requests tag.

**Comment by aadibajpai** [comment]
> @aadibajpai Quoting literally the last comment here:
> 
> > Questions and requests for assistance should be directed to StackOverflow.com with the python-requests tag.

Been there, found something (https://stackoverflow.com/questions/52497739/how-to-set-requests-user-agent-header-globally), didn't help and since the question is same then a new question would be marked a duplicate :)

**Comment by sigmavirus24** [comment]
Thta doesn't magically make this the right place to ask questions since this is officially not the place for questions or requests for support to be asked

**Comment by aadibajpai** [comment]
> Thta doesn't magically make this the right place to ask questions since this is officially not the place for questions or requests for support to be asked

Fair enough, do you have a recommendation then? 🙂
