### ISSUE TITLE
response cookies missing

### ISSUE THREAD

**Issue by yifeikong** [requests/requests#4808]
cookies not found in response

## Expected Result

`foo=bar` shown in cookies

## Actual Result

empty cookiejar

## Reproduction Steps

```python

In [14]: r = requests.get('http://httpbin.org/cookies/set?foo=bar')

In [15]: r.cookies
Out[15]: <RequestsCookieJar[]>

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.2.2"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.5"
  },
  "platform": {
    "release": "17.5.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010008f",
    "version": "17.5.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020ff"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}

```

**Comment by perkfly** [comment]
I have figured out why, there is a redirection. The cookies were set in first response, which is a 302 redirect, and the second response set no cookies. So r.cookies is empty, but cookies are found in s.cookies. Is this a intended behavior?

**Comment by sigmavirus24** [comment]
It is entirely intended behaviour. I believe it is documented as well.
