### ISSUE TITLE
Using requests with unpatched socket

### ISSUE THREAD

**Issue by kushalagrawal1** [requests/requests#4810]
Hi, 

In my python environment, I am using patched socket using eventlet. But sometimes the thread is getting stuck because of eventlet library limitation,
[https://github.com/eventlet/eventlet/issues/492](https://github.com/eventlet/eventlet/issues/492)

therefore According to event I need to use eventlet.patcher.original("requests"),  while using this I am gettting this error : 
``    requests = eventlet.patcher.original("requests")
  File "/usr/lib/python2.7/site-packages/eventlet/patcher.py", line 194, in original
    real_mod = __import__(modname, {}, {}, modname.split('.')[:-1])
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
ImportError: cannot import name utils ``

When I debug it request.request shows me `func_code = <code object request at 0x7f4443cc7bb0, file "/usr/lib/python2.7/site-packages/requests/api.py", line 16>`

but socket.socket gives me "<class 'eventlet.greenio.base.GreenSocket'>".

So, is it possible pass unpatched socket (which comes from eventlet.patcher.original("socket"))  while using requests.request ?

**Comment by sigmavirus24** [comment]
Based on your traceback, this seems to be an issue with how `eventlet.patcher` works. This is not an issue in Requests. It would seem eventlet doesn't understand import semantics or how to use import machinery. By default Requests uses `socket.socket` (unpatched, not eventlet) so to answer your question, yes it is possible to use that. It would be even more possible if eventlet were using the import machinery appropriately.
