### ISSUE TITLE
Decode as UTF-8 when charset is none and content-type header is "application/json"

### ISSUE THREAD

**Issue by yuji38kwmt** [requests/requests#4811]
## Actual Result

When content-type header is "application/json" and charset is none, `response.encoding` is empty.

```python:server.py
from flask import Flask, make_response, jsonify
import json
app = Flask(__name__)

@app.route('/test')
def test():
    resp = jsonify({"result":"test"})
    resp.headers['Content-Type'] = 'application/json;'
    return resp

```

```python:client.py
r = requests.get("http://localhost:5000/test")
print(r.encoding)
// empty
```

## Feature request

In RFC8259, character encoding of JSON must be UTF-8. Please ensure it is set correctly.

>JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8 [RFC3629].

https://www.rfc-editor.org/rfc/rfc8259.txt

**Comment by nateprewitt** [comment]
Hi @yuji38kwmt, it's important to note RFC8259 specifies that it:
> MUST be **encoded** using UTF-8

That's a directive for a client before sending JSON data outside of its ecosystem. Requests should do this [here](https://github.com/requests/requests/blob/a6cd380c640087218695bc7c62311a4843777e43/requests/models.py#L462-L468). As for receiving data, the very next line of the RFC states:
>  Previous specifications of JSON have not required the use of UTF-8
   when transmitting JSON text.

Many of these implementations still exist in the wild and are actively used. We can't make a decision to blacklist or break compatibility with those clients when a new RFC is released. Requests generally works with the philosophy of ensuring what we emit conforms to the current spec, but that we tolerate receiving many of the commonly observed deviations from it.

The encoding attribute is only used on the `text` method, as noted in the documentation so it's OK for it to be None. You should find though that calling the `json` method on your response returns a properly encoded string if it is in fact utf-8. Are you observing something different?

**Comment by yuji38kwmt** [comment]
Thanks.

>You should find though that calling the json method on your response returns a properly encoded string if it is in fact utf-8. Are you observing something different?

I didn't know `json` method , so I used `json.loads(response.text)` insted of `json` method.
I close this issue.
