### ISSUE TITLE
netrc parsing is overly strict

### ISSUE THREAD

**Issue by ianwremmel** [requests/requests#4813]
This started out as a [bug report for httpie](https://github.com/jakubroztocil/httpie/issues/717#issuecomment-426125261) and they referred me here.

> it appears that auth via netrc is broken if `~/.netrc` includes entries that are not exactly login/password tuples. For example, I have the following entries for circle ci and heroku:
> 
> ```
> machine api.heroku.com
>   login <redacted>
>   password <redacted>
>   method interactive
> machine circleci.com
>   login <redacted>
> ```
>
> both of these entries prevent my entry for `github.com` from working with `httpie` (but curl works just fine).

## Expected Result

`https api.github.com/users` should return 200

## Actual Result

`https api.github.com/users` should returned 401

## Reproduction Steps

See summary section for `.netrc` configs that don't parse.

## System Information

    $ python -m requests.help

> I'm not sure if this is the output you wanted since I don't know enough about python to know if the requests found this way is the same one that httpie depends on.

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.15"
  }, 
  "platform": {
    "release": "18.0.0", 
    "system": "Darwin"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.18.4"
  }, 
  "system_ssl": {
    "version": "1000210f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there,

What happens if you do:

```py
import netrc
import os.path

netrc.netrc(os.path.expanduser('~/.netrc')).authenticators('api.github.com')
```

**Comment by sigmavirus24** [comment]
I ask, because [we rely on the standard library](https://github.com/requests/requests/blob/a6cd380c640087218695bc7c62311a4843777e43/requests/utils.py#L166..L210) to parse the file. That means if anything is actually overly strict then it's Python.

**Comment by ianwremmel** [comment]
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    netrc.netrc(os.path.expanduser('~/.netrc')).authenticators('api.github.com')
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/netrc.py", line 35, in __init__
    self._parse(file, fp, default_netrc)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/netrc.py", line 88, in _parse
    file, lexer.lineno)
netrc.NetrcParseError: malformed machine entry circleci.com terminated by 'machine' (/Users/ian/.netrc, line 3)
```

**Comment by ianwremmel** [comment]
In this case, I only had circleci.com and api.github.com in netrc

**Comment by sigmavirus24** [comment]
Your traceback shows that this is in fact not the fault of Requests and there's little for us to do to work around it.

Perhaps a more modern version of Python fixes the issue with the standard library.
