### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by hook-s3c** [requests/requests#4818]
Running the unit tests, many failures. Am I doing this wrong? Couldn't find docs to run the tests from source.

## Expected Result

All tests to pass

## Actual Result

Many failed

## Reproduction Steps

```
git clone https://github.com/requests/requests
cd requests
sudo make init
sudo pipenv run detox
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": "2.2.2"
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.13"
  }, 
  "platform": {
    "release": "4.15.13-041513-generic", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "1000207f", 
    "version": "0.15.1"
  }, 
  "requests": {
    "version": "2.19.1"
  }, 
  "system_ssl": {
    "version": "1010003f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by ifosch** [comment]
Is that right you use `sudo make init` and `sudo pipenv run detox`? It sounds a little bit strange to me that you need su rights for running tests.

**Comment by ifosch** [comment]
@hook-s3c what errors do you get?

**Comment by sigmavirus24** [comment]
No response
