### ISSUE TITLE
Are connections reused when response is read through json() method?

### ISSUE THREAD

**Issue by rybak** [requests/requests#4819]
From [Advanced Usage page](http://docs.python-requests.org/en/master/user/advanced/#keep-alive) (emphasis mine):

> ## Keep-Alive
>
> Excellent news — thanks to urllib3, keep-alive is 100% automatic within a session! Any requests that you make within a session will automatically reuse the appropriate connection!
> 
> Note that connections are only released back to the pool for reuse once all body data has been read; be sure to either set `stream` to `False` or **read the `content` property** of the `Response` object.

Could you please clarify if the connection would be released to the pool for reuse if the response is read though `.json()` method instead of the `content` property?

**Comment by sigmavirus24** [comment]
If you're not using `stream=True` the connection will always be released to the pool.

If you do use `stream=True` then anything that reads the body of the response (`.content`, `.text`, `.json()`) will release the connection upon successfully consuming the body.
