### ISSUE TITLE
Cookies problem

### ISSUE THREAD

**Issue by gaplan** [requests/requests#4843]
Hello,
I'm working on instagram, and I've seen the error in the Cookie part of the response and add the result.

## Expected Result
`"{\"78.183.146.64\": 9121}:1gDpKI:LjSZuxpGaGdQPUPDd3rqZGx6BfQ"`

## Actual Result
"{78.183.146.64: 9121}:1gDpKI:LjSZuxpGaGdQPUPDd3rqZGx6BfQ"

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": "2.3.1"
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.10"
  }, 
  "platform": {
    "release": "17.7.0", 
    "system": "Darwin"
  }, 
  "pyOpenSSL": {
    "openssl_version": "20000000", 
    "version": "0.13.1"
  }, 
  "requests": {
    "version": "2.20.0"
  }, 
  "system_ssl": {
    "version": "20000000"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by gaplan** [comment]
if i try like this, i can see Expected Result

`
import cookielib
import urllib2

cookies = cookielib.LWPCookieJar()
handlers = [
    urllib2.HTTPHandler(),
    urllib2.HTTPSHandler(),
    urllib2.HTTPCookieProcessor(cookies)
    ]
opener = urllib2.build_opener(*handlers)

def fetch(uri):
    req = urllib2.Request(uri)
    return opener.open(req)

def dump():
    for cookie in cookies:
        print cookie.name, cookie.value

uri = 'https://i.instagram.com/api/v1/users/8748681962/info/'
res = fetch(uri)
dump()`


`
csrftoken DmSQpBYsLLvDJDBn37qGzsYML0pNLSdz
mcd 3
mid W88LbQAEAAGwiOHOaLsBWlW5hhO-
rur FRC
urlgen "{\"78.180.81.143\": 9121}:1gEvEL:dG2Yo8R-iIFx1GgExKUr74xtWuY"
`

**Comment by gaplan** [comment]
Anybody ?

**Comment by nateprewitt** [comment]
Hi @gaplan, we haven’t had a chance yet to review this ticket. If you can please look at creating a test to demonstrate your issue with Requests code that will help expedite things.

**Comment by gaplan** [comment]
Hello @nateprewitt Thank you for reply.
If I use Requests ;

code:
`import requests
r = requests.get('https://i.instagram.com/api/v1/users/8748681962/info/')
kuki = r.cookies.get_dict()
for i in kuki:
    print i,kuki[i]`

Response : 
`csrftoken 0ckvyNUJ54UYBVV7os8DmsLF2NlBTWjr
rur FTW
mcd 3
mid W8_OygAEAAEH_3MwkXUh_pM3O4Qp
urlgen "{78.180.81.143: 9121}:1gF8F0:fvj1GU2r17d3u7Ylo5c4rtDOU-k"`

but if i use urllib2 for this link 

Code:
`import cookielib
import urllib2

cookies = cookielib.LWPCookieJar()
handlers = [
    urllib2.HTTPHandler(),
    urllib2.HTTPSHandler(),
    urllib2.HTTPCookieProcessor(cookies)
    ]
opener = urllib2.build_opener(*handlers)

def fetch(uri):
    req = urllib2.Request(uri)
    return opener.open(req)

def dump():
    for cookie in cookies:
        print cookie.name, cookie.value
    print '*'*10

uri = 'https://i.instagram.com/api/v1/users/8748681962/info/'
res = fetch(uri)
dump()
`

and response : 
`csrftoken BbvolUUXZ1ChLVu9v75NHdBiOZhzGLMG
mcd 3
mid W8_OyQAEAAHoH7b4DHRGrb4od9PR
rur FRC
urlgen "{\"78.180.81.143\": 9121}:1gF8Ez:WSrOofW2qu5r4kwgjfs0f2STfKg"
`

**please see the urlgen values**

**Comment by gaplan** [comment]
still waiting...

**Comment by sigmavirus24** [comment]
@gaplan We don't have infinite time to help you with problems that don't seem to be caused by a bug in requests. This looks to be a problem with how the server generates the cookie value. We don't do any extra prasing here that would cause this.
