### ISSUE TITLE
About the json param

### ISSUE THREAD

**Issue by Arayui** [requests/requests#4845]
In my work, I encountered such a problem:
Developers require the use of most compact json.
But when I use the requests module, 
I found that the internal code used "body = complexjson.dumps (json)".
This is not flexible enough.
Especially when developers do not deal with such problems. (I am a tester)
So, can you add a parameter to deal with this kind of thing?
Looking forward to your reply.

**Comment by sigmavirus24** [comment]
Developers can already use their own JSON serialization by not using the `json` parameter. We will not add a new parameter to a feature-frozen API for an unspecified use-case.
