### ISSUE TITLE
Adding `timeout` changes behavior without raising an exception

### ISSUE THREAD

**Issue by davisjam** [requests/requests#4846]
I am using `requests` to query a website.
If I query with `timeout`, it behaves like I want (well, kind of).
If I query without `timeout`, the request hangs.

This behavior seems to be specific to this website. My code works fine against other websites.

## Expected Result

The request does not hang.

## Actual Result

Without `timeout`, the request hangs.
With `timeout`, the request takes the full timeout window before returning successfully.

## Reproduction Steps

```python
#!/usr/bin/env python3

import requests

# Works -- but takes the full timeout before the call returns
print('Try 1')
r = requests.get('https://repo.packagist.org/p/jrodella/payment-form-api.json', timeout=5)

# Hangs
print('Try 2')
r = requests.get('https://repo.packagist.org/p/jrodella/payment-form-api.json')
```

If I add in logging, the hang occurs after the log statement:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.packagist.org
```

## System Information

    $ python -m requests.help

```
(13:21:07) jamie@woody ~/Desktop/EcosystemRegexps/ecosystems $ python3 -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "4.15.0-33-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1000207f",
    "version": "17.3.0"
  },
  "requests": {
    "version": "2.18.1"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": true
}
```

**Comment by nateprewitt** [comment]
Hi @davisjam,

This is the expected behavior of not passing a timeout, the connection will remain open until closed by one of the involved parties.

This information is available at the top of the timeout section in the [docs](http://docs.python-requests.org/en/master/user/quickstart/#timeouts).

>  Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely

**Comment by davisjam** [comment]
Hi @nateprewitt.

I have read the documentation. Perhaps I was too hasty in my writeup.

Can you clarify what I find the odd behavior here? Namely that:

> With timeout, the request takes the full timeout window before returning successfully.

This implies that there is a path wherein the timeout expires but no exception is raised.
I could not find this described in the documentation.

If I add `verify=False` then no `timeout` parameter is necessary; the request completes promptly and the website closes the connection.
