### ISSUE TITLE
PyPI page for requests shows raw markup

### ISSUE THREAD

**Issue by mgedmin** [requests/requests#4859]
https://pypi.org/project/requests/ shows raw markdown.

## Expected Result

Properly formatted text.

## Actual Result

![ekrano nuotrauka is 2018-11-05 17-19-29](https://user-images.githubusercontent.com/159967/48006834-fde96500-e11e-11e8-9173-69de1ab7ca73.png)

## Reproduction Steps

Open https://pypi.org/p/requests in a browser

**Comment by nateprewitt** [comment]
Hi @mgedmin, this is a result of the version of twine used to upload the 2.20 release. The readme was recently changed to markdown which had issues rendering properly with older versions of twine.

We’ll be doing a hotfix release sometime this week which will resolve the issue. Thanks for making sure we were aware :)
