### ISSUE TITLE
why use Session post a data contain a empty tuple,the status_code always 400

### ISSUE THREAD

**Issue by yanchunhuo** [requests/requests#4864]
Summary.
why use Session post a data contain a empty tuple,the status_code always 400

## Expected Result
200
200
## Actual Result
200
400

What happened instead.

## Reproduction Steps

```python
#-*- coding:utf8 -*-
import requests

if __name__=='__main__':
    session = requests.session()
    params={}
    a=()
    params.update({'id':a})
    httpresult = session.get('http://www.baidu.com/',data=params)
    print httpresult.status_code
    httpresult = session.get('http://www.baidu.com/')
    print httpresult.status_code

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.12"
  }, 
  "platform": {
    "release": "4.15.0-29-generic", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.20.0"
  }, 
  "system_ssl": {
    "version": "1000207f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
