### ISSUE TITLE
Cryptiles dependency vulnerability: Update to >4.1.2

### ISSUE THREAD

**Issue by carlosscastro** [requests/requests#4875]
Hello!

In some of the Microsoft Bot Framework repos have a dependency on request which has an indirect dependency on Cryptiles. We are getting a warning from a security vulnerability that would be solved upgrading cryptyles to >4.1.2. 

It seems like it is an indirect dependency of yours. Any idea how I can fix this vulnerability or plans to somehow upgrade cryptiles dependency?

Thanks!

**Comment by nateprewitt** [comment]
Hi @carlosscastro, we shouldn’t have any dependencies on that package. Can you tell us how you determined this was tied back to Requests?

**Comment by nateprewitt** [comment]
I took a look and that is a JavaScript package. Requests only contains python code, so I think this may be filed in the wrong repository. Perhaps you were looking for the request/request repo.
