### ISSUE TITLE
Use a certificate

### ISSUE THREAD

**Issue by metropt** [requests/requests#4878]
I'm trying to use a certificate with requests. I need to use a certificate to access internal services at work. I have installed it on chrome per example to access some internal sites.

With curl I can use it that way: `curl -s --cacert /home/path/certificate.crt -u USER:PASSWORD https://server:8443/teste`

With requests I can't make it work. I have already read some old closed issues without success. I also created a post on stack-overflow but I couldn't understand the answers I got on comments. https://stackoverflow.com/questions/53340465/cant-use-a-crt-certificate

I use the command 
`r = requests.get('https://server:8443/teste', auth=HTTPBasicAuth('USER', 'PASSWORD'), verify='/home/path/certificate.crt')`
 with result:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='server', port=8443): Max retries exceeded with url: /teste (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))`

Thank you

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by metropt** [comment]
Hi, thank you. I tried to get help there without success :(
