### ISSUE TITLE
Cookies from Response don't show up in cookies list

### ISSUE THREAD

**Issue by jcrmatos** [requests/requests#4881]
Hello,

I receive a response (checked with Chrome/Firefox inspector) from the post request with the following headers:
Cache-control: no-cache, no-store, max-age=0
Connection: Keep-Alive
Content-Language: pt
Content-Type: text/html
Pragma: no-cache
Set-cookie: Cookie=sid=46c76f5a656dcb9092e7c2840b0a9747fe248af99bc7e62e372bfcede16c0e63:Language:portuguese:id=1;path=/
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN

but the cookies don't appear in the response.cookies or the session.cookies.

## Expected Result

The cookies should appear in the response cookies list.

## Actual Result

Both cookies lists are empty.
200
200
<RequestsCookieJar[]>
<RequestsCookieJar[]>

## Reproduction Steps

```python
import requests

headers = {
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
'Accept-Encoding': 'gzip, deflate',
'Accept-Language': 'pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7',
'Cache-Control': 'no-cache',
'Connection': 'keep-alive',
'Cookie': 'Cookie=sid=254f086ef66799f95c777d1e681ac2b3380a80f4c7faa172163a261eaab2da12:Language:portuguese:id=1',
'Pragma': 'no-cache',
'Upgrade-Insecure-Requests': '1',
'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36',
}

headers_login = {
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
'Accept-Encoding': 'gzip, deflate',
'Accept-Language': 'pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7',
'Cache-Control': 'max-age=0',
'Connection': 'keep-alive',
'Content-Length': '89',
'Content-Type': 'application/x-www-form-urlencoded',
'Cookie': 'Cookie=body:Language:portuguese:id=-1',
'DNT': '1',
'Host': '192.168.255.254',
'Origin': 'http://192.168.255.254',
'Referer': 'http://192.168.255.254/',
'Upgrade-Insecure-Requests': '1',
'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36',
}

with requests.Session() as s:
    resp = s.get('http://192.168.255.254', headers=headers)
    print(resp.status_code)
    resp = s.post('http://192.168.255.254/login.cgi',
                  data={'UserName': 'username', 'PassWord': 'password',
                        'x.X_HW_Token': 'c95075d23616ccc9c149ec82c651becd'},
                  headers=headers_login)
    print(resp.status_code)
    print(resp.cookies)
    print(s.cookies)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.0"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "1010008f"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": false
}
```

Thanks,

JM

**Comment by sigmavirus24** [comment]
- Are there redirects? Check `resp.history` and those responses' cookie jars.
- Is the cookie header ever present in `resp.headers`?
- Are you expecting the cookie header you're sending to show up in the headers on the response or session? This won't work
- Have you read over the myriad of other closed issues that are just like this one?

**Comment by jcrmatos** [comment]
Hello,

No, no redirects that I can find. resp.history is empty.
No it does not appear in the response.headers from requests, but I see it in Chrome/Firefox inspect response headers.
No, I'm expecting the cookie header that I receive to appear in the response cookies list, or at least in the response headers.
Yes, I read them.

Thanks,

JM

**Comment by sigmavirus24** [comment]
>  No it does not appear in the response.headers from requests, but I see it in Chrome/Firefox inspect response headers.

Then this is why it doesn't show up in your cookiejar. If there is no header returned to us, we can't pull the cookie strings out of thin air.

It would seem the server isn't returning the value to you and therein lies the problem

**Comment by jcrmatos** [comment]
Hello,

As I stated "No it does not appear in the response.headers from requests, **but I see it in Chrome/Firefox inspect response headers.**"
The server IS sending the header because I see it in Chrome/Firefox.

Thanks,
JM

**Comment by sigmavirus24** [comment]
It is not sending it to us though. We don't modify the headers at all. If it doesn't show up in our headers dictionary, the server isn't sending it.

**Comment by jcrmatos** [comment]
Hello,

Your are correct. It was sending it to the browser (Chrome/Firefox) but not to the requests module.
There was a token missing in the request headers. As soon as I added the missing token, requests received the cookie headers and everything showed up.
Sorry for the inconvenience and thanks for the help.

Thanks,

JM
