### ISSUE TITLE
https://docs.python-requests.org certificate's CN is *.readthedocs.org

### ISSUE THREAD

**Issue by juga0** [requests/requests#4885]
This is not a software bug but a deployment bug.
http://docs.python-requests.org does not redirect to HTTPS.
In some browsers, visiting https://docs.python-requests.org, will give SSL_ERROR_BAD_CERT_DOMAIN, because the certificate's CN does not match the requested URL.
https://readthedocs.org/projects/requests/latest/ redirects http://docs.python-requests.org.

## Expected Result

docs.python-requests.org Website via HTTPS

## Actual Result

SSL_ERROR_BAD_CERT_DOMAIN: Unable to communicate securely with peer: requested domain name does not match the server’s certificate. 

## Reproduction Steps

Open https://docs.python-requests.org in a browser, or:
```
curl https://docs.python-requests.org
curl: (51) SSL: no alternative certificate subject name matches target host name 'docs.python-requests.org'
```

**Comment by kennethreitz** [comment]
currently unsupported
