### ISSUE TITLE
windows for ubuntu18.04,data={"id":None},no response

### ISSUE THREAD

**Issue by cxdtotsj** [requests/requests#4887]
Summary.

## Actual Result

No response, no timeout parameter does not work

## Reproduction Steps

```python
import requests

url = "https://dt-dev.arctron.cn/api/zone/get"    (my company progect)
data = {"id":None}
headers = header
reqs = requests.post(url=url,data=data,headers=header)
```
## the picture
![image](https://user-images.githubusercontent.com/42604280/49431871-5cbb0080-f7e9-11e8-946f-ec1cb82b0982.png)

**Comment by tr0yspradling** [comment]
Seems to be an issue with the host: `https://dt-dev.arctron.cn/api/zone/get`

`curl https://dt-dev.arctron.cn/api/zone/get` acts the same.
