### ISSUE TITLE
idna 2.8 released

### ISSUE THREAD

**Issue by Nothing4You** [requests/requests#4890]
[`idna`](https://pypi.org/project/idna/#history) 2.8 was just released. requests is [pinned to `idna>=2.5,<2.8`](https://github.com/requests/requests/blob/57d7284c1a245cf9fbcecb594f50471d86e879f7/setup.py#L46)

Can the pin be updated to allow v2.8?

**Comment by Vlad-Shcherbina** [comment]
By the way, out of curiosity, what's the reason to pin minor version number at all?
It seems it was first introduced in 1ea27b35649571abb796f7cffbab83938d882a8d, but there is no explanation in the commit metadata.

**Comment by sigmavirus24** [comment]
@Vlad-Shcherbina why have a lowest version we support? Because that's the lowest version we know works with idna at all. Libraries change things in subtly backwards incompatible ways. If we don't put together a range of known good versions, users will use whatever they want, shoot themselves in the foot, and demand we fix it for them. With only 2 people working on this project, no one has time for that

**Comment by asvetlov** [comment]
My 2 cents.

`aiohttp` library depends on `yarl`. In turn, `yarl` depends on `idna>=2.0`.
So far so good.
`aiohttp` uses `twine check` for making sure that `setup.py` is (at least partially) correct.
There is no surprise that `twine` uses the awesome `requests` (almost every tool that needs synchronous HTTP access uses `requests`).

Today our daily CI job has failed wit version conflict error. Sure, we can create a separate virtual env for  `twine` usage or we can find another solution but the situation looks odd.

On another hand I understand the striving to pin everything for such community important project: any backward incompatibility in `requests` dependencies can hurt too many people.

**Comment by asvetlov** [comment]
Could you please make a new release? 
Releasing `requests==2.20.2` should not take too long perhaps.

**Comment by sigmavirus24** [comment]
>  Releasing requests==2.20.2 should not take too long perhaps.

Changing version constraints would lead to a 2.21 version. There's already a PR for upgrading the dependency version https://github.com/requests/requests/pull/4889

**Comment by Schamschula** [comment]
Breaks py-requests, and in turn certbot under MacPorts.

**Comment by nateprewitt** [comment]
Hi @Schamschula, we’re aware of the impact. Using the requirements specified by Requests will continue to work until the next patch is released. I’m aiming to get something out early next week once we can get the testing issues worked out.

**Comment by Schamschula** [comment]
@nateprewitt Thanks for the update.!

 In the meantime, I've opened a ticket for those MacPorts users that might run into this issue:

https://trac.macports.org/ticket/57747

**Comment by nateprewitt** [comment]
Requests 2.21.0 is up on PyPi now supporting idna 2.8.
