### ISSUE TITLE
Exceptions occur when nonstandard headers are returned

### ISSUE THREAD

**Issue by Lcys** [requests/requests#4899]
requests==2.20.1
python2.7.15
 ```
HTTP/1.1 200 OK
	Content-Type: application/octet-stream
	Content-Length: 35239
	Content-Disposition: attachment; filename="text.txt" 
```

Exceptions occur when tabs exist in HTTP return headers
Exception information: `Header continuation with no previous header: urllib3.exceptions.InvalidHeader: Header continuation with no previous header: 	Content-Type: application/octet-stream
`

**Comment by sigmavirus24** [comment]
It's not that these are non-standard headers. It's that the headers are formatted as if they're all part of the line `HTTP/1.1 200 OK`. This is a bug that has been opened in the past. It's not something we can fix. There's only so much we can do to override httplib's behaviour when a server completely and totally misbehaves.
