### ISSUE TITLE
Not clear how to build coverage report

### ISSUE THREAD

**Issue by boxed** [requests/requests#4900]
I was looking into trying out mutation testing (with mutmut) on requests, seeing as this is one of the most critical libraries for python. But to do this effectively I need to get the coverage report and this was non-trivial.

## Expected Result

`tox -e coverage` or `make coverage` should run tests with coverage.

## Actual Result

It complains about me not having pipenv, so I installed that, then it build some venv and then fails with

```
pipenv run py.test --cov-config .coveragerc --verbose --cov-report term --cov-report xml --cov=requests tests
Error: the command py.test could not be found within PATH or Pipfile's [scripts].
make: *** [coverage] Error 1
```

(aside: py.test? It's pytest nowadays)

## Reproduction Steps

Check out requests. Run `make coverage`.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.7"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.15"
  }, 
  "platform": {
    "release": "18.0.0", 
    "system": "Darwin"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.20.1"
  }, 
  "system_ssl": {
    "version": "1000210f"
  }, 
  "urllib3": {
    "version": "1.24.1"
  }, 
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @boxed,

There's a couple options for running coverage.

1.) You'll need to setup pipenv to run `make coverage`. More info on that [here](https://pipenv.readthedocs.io/en/latest/).
2.) You can call `pytest --cov-config .coveragerc --verbose --cov-report term --cov-report xml --cov=requests tests` directly with the pytest dependencies installed. You can find those dependencies in the [Pipfile](https://github.com/requests/requests/blob/master/Pipfile).

**Comment by boxed** [comment]
Why did you close this? This is a documentation and/or tooling issue, not a support forum question.

**Comment by sigmavirus24** [comment]
This is the first report of someone who couldn't get the tooling to work. If it continues to be an issue, we can invest time in figuring out how to make it easier. Otherwise, I agree with Nate closing this.
