### ISSUE TITLE
Only use urllib3's pyOpenSSL support when SNI isn't available

### ISSUE THREAD

**Issue by SethMichaelLarson** [requests/requests#4902]
I'm floating this idea because currently our native `ssl` module support isn't being utilized by any requests users and I'm planning on making major improvements to SNI within native `ssl` support in urllib3 including leaning on the stdlib for hostname verification.  What are the thoughts on only using pyOpenSSL when `urllib3.util.HAS_SNI` is false?

**Comment by sigmavirus24** [comment]
That would be potentially backwards incompatible. At this point, we inject pyOpenSSL when it's there. It was primarily for SNI support, but I believe this enables other things the stdlib doesn't support and that some users may be relying on "if pyOpenSSL is installed, requests uses it" at this point.

**Comment by sethmlarson** [comment]
Ah okay, I was unaware there were extras besides SNI being added. Thanks for the clarification!
