### ISSUE TITLE
Incorrect claim that params go in the request body

### ISSUE THREAD

**Issue by mjpieters** [requests/requests#4911]
c008bf38836a2b5621ba7b352e9fcecacac4ee93 introduced a factual error in to the documentation for the `params` parameter.

The old text was

>  :param params: (optional) Dictionary or bytes to be sent **in the query string** for the :class:`Request`. 

which was replaced by

>  :param params: (optional) Dictionary, list of tuples or bytes to send **in the body** of the :class:`Request`. 

Bold emphasis mine. Obviously `params` still go in the query parameter, no functionality was changed. This was probably a copy and paste error following 2d1b4482c5916433a642d66c6b3d0cd28058b39e.

Please replace *body* with *query string*.

Cc: @moy

**Comment by nateprewitt** [comment]
Hi @mjpieters, #4910 addressed this so it should be resolved shortly. Thanks!

**Comment by mjpieters** [comment]
Bah, should have checked for pull requests too. Sorry!
