### ISSUE TITLE
Turning off keep-alive

### ISSUE THREAD

**Issue by StKob** [requests/requests#4913]
In older versions of Requests there was option to turn off keep alive. Something like this:
```
s = requests.session()
s.config['keep_alive'] = False
```
How to do it in recent versions?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by abitrolly** [comment]
The question asked is not answered https://stackoverflow.com/questions/53870767/turning-off-keep-alive

**Comment by abitrolly** [comment]
A similar question with 16 upvoted answers doesn't work for requests 2.x
https://stackoverflow.com/questions/21008953/python-requests-1-how-to-disable-keep-alive

    s = requests.session()
    s.keep_alive = False

    AttributeError: 'Session' object has no attribute 'keep_alive'
