### ISSUE TITLE
file named "requests.py" throws AttributeError: module 'requests' has no attribute 'get'

### ISSUE THREAD

**Issue by lupuselit** [requests/requests#4927]
I was playing with requests for a while and I was running into issues

I had a file named requests.py which I was always getting the error:

``` AttributeError: module 'requests' has no attribute 'get' ```

but as soon as I changed the name of the file the error doesn't happen anymore.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by lupuselit** [comment]
How's that a request of help at any matter? I am just pointing a possible bug, which is the fact that the code won't work if I have a file named 'requests.py'.

Never asked for help. Cheers.

**Comment by emerson-d-lopes** [comment]
> Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

How's that a request of help at any matter? I am just pointing a possible bug, which is the fact that the code won't work if I have a file named 'requests.py'.

Never asked for help. Cheers.

**Comment by t-8ch** [comment]
If you do `print(requests.__file__)` you will notice, that the Python import machinery loaded your `requests.py` file instead of the `requests` library. So this is in fact not a bug.

**Comment by hariharan2004** [comment]
> I was playing with requests for a while and I was running into issues
> 
> I had a file named requests.py which I was always getting the error:
> 
> `AttributeError: module 'requests' has no attribute 'get'`
> 
> but as soon as I changed the name of the file the error doesn't happen anymore.

How to change it
