### ISSUE TITLE
Log requests and responses 

### ISSUE THREAD

**Issue by ololoe** [requests/requests#4928]
There is a useful feature in `grablib` to log all requests and responces, although it doesn't work 100% correctly. https://grablib.org/en/latest/grab/debugging.html#grab-debugging-response-saving Don't you want to adopt this feature?

**Comment by nateprewitt** [comment]
Hi @ololoe, Requests is currently under a feature freeze and we don’t have immediate plans to change that. This is something that should be easy to create externally from Requests though, if you want to create your own repository for it.

Thanks for the idea!

**Comment by ololoe** [comment]
What do you mean under "to create externally from Requests"?

**Comment by sigmavirus24** [comment]
https://toolbelt.readthedocs.io/en/latest/dumputils.html already exists

**Comment by ololoe** [comment]
@sigmavirus24 it's not the same.
