### ISSUE TITLE
parse_dict_header should return CaseInsensitiveDict

### ISSUE THREAD

**Issue by adiba** [requests/requests#4931]
https://github.com/requests/requests/blob/c501ec986daa4961cd9dee370b5d45ff2e524b37/requests/utils.py#L344-L375

In `parse_dict_header` a regular dict is used, but as stated in the RFC the keys should be case-insensitive.

**Comment by sigmavirus24** [comment]
This isn't really part of our public API and it's not meant for parsing into a headers dictionary. This is working as intended for the purpose it is supporting.
