### ISSUE TITLE
chardet/urllib3 warnings

### ISSUE THREAD

**Issue by till** [requests/requests#4949]
While debugging a bug in Ansible, I noticed these warnings:

```
RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
```

I spent some time trying to get rid off them, but to no avail. What are the exact/supported dependencies?

Here is a list of installed packages:

```
# pip list
backports.ssl-match-hostname (3.5.0.1)
cached-property (1.5.1)
certifi (2018.11.29)
chardet (3.0.4)
configobj (4.7.2)
decorator (3.4.0)
docker (3.7.0)
docker-compose (1.23.2)
docker-pycreds (0.4.0)
dockerpty (0.4.1)
docopt (0.6.2)
enum34 (1.1.6)
functools32 (3.2.3.post2)
idna (2.7)
iniparse (0.4)
ipaddress (1.0.16)
IPy (0.75)
jsonschema (2.6.0)
kitchen (1.1.1)
perf (0.1)
pip (8.1.2)
policycoreutils-default-encoding (0.1)
pycurl (7.19.0)
pygobject (3.22.0)
pygpgme (0.3)
pyliblzma (0.5.3)
python-linux-procfs (0.4.9)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.13)
requests (2.21.0)
schedutils (0.4)
seobject (0.1)
sepolicy (1.1)
setuptools (0.9.8)
six (1.12.0)
slip (0.4.0)
slip.dbus (0.4.0)
texttable (0.9.1)
urlgrabber (3.10)
urllib3 (1.24.1)
websocket-client (0.54.0)
yum-metadata-parser (1.1.4)
```
## Expected Result

No warning.

## Actual Result

Warning.

## System Information

    $ python -m requests.help

```
# python -m requests.help
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
{
  "chardet": {
    "version": "2.2.1"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.7"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.5"
  }, 
  "platform": {
    "release": "3.10.0-957.el7.x86_64", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.21.0"
  }, 
  "system_ssl": {
    "version": "100020bf"
  }, 
  "urllib3": {
    "version": "1.24.1"
  }, 
  "using_pyopenssl": false
}
```

OS: 

```
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

**Comment by till** [comment]
Should have read the source:
https://github.com/requests/requests/blob/master/requests/__init__.py#L57-L71

 - urllib3: < 1.23
 - charded: < 3.0.0

Any reason why this is not enforced via `requirements.txt`? (I am new to Python, so excuse my ignorance.)

**Comment by sigmavirus24** [comment]
It is enforced via Python packaging methods but downstream redistributors do whatever they want. :man_shrugging:

**Comment by tedder** [comment]
As an update to Till's list for future googlers, here's the current version spec:

    urllib3 >= 1.21.1, <= 1.24
    chardet >= 3.0.2, < 3.1.0

Notably, `chardet` is in the early 3.x range. You can copy/paste that into your requirements.txt, no changes needed.

Follow the source to see what has changed since I posted this: https://github.com/requests/requests/blob/master/requests/__init__.py#L57-L71
