### ISSUE TITLE
post multipart form data with additional parameters inContent-Disposition

### ISSUE THREAD

**Issue by LeiYangGH** [requests/requests#4950]
This question is a bit special but I cannot find the solution anywhere.
I've posted the same question in stackoverflow but there's no answer yet.https://stackoverflow.com/questions/54209711/python-requests-post-multipart-form-data-with-additional-parameters-in-content-d

I have curl data like this(it's working)
--message_boundary_0001--
Content-Disposition: form-data; name="RequestData"
Content-Type: application/json; charset=utf-8

{
    "appKey": "525348e77144a9cee9a7471a8b67c50ea85b9e3eb377a3c1a3a23db88f9150eefe76e6a339fdbc62b817595f53d72549d9ebe36438f8c2619846b963e9f43a93",
    "appId": "SAMPLE_DEBUG_NMAID_TO_BE_REPLACED",
    "outCodec": "OPUS_16K",
    "cmdName": "NVC_TTS_CMD",  
    "cmdDict": {
        "tts_language":"eng-USA",
        "tts_voice":"ava-ml",
        "tts_log_level": "FULL",
    "supportedTtsFeature":{
            "tts_multi_logic_stream_flag": "true",
            "tts_early_emission_flag": "true"
        }  
    }
}
--message_boundary_0001--
Content-Disposition: form-data; name="TtsParameter"; **paramName**="TEXT_TO_READ"
Content-Type: application/json; charset=utf-8

{
   "tts_type": "native_text",
   "tts_input":"The result will be millions of Americans who have insurance who did not have it before. Thats the goal. And the goal is not about the website. The goal is that the American people who have been shut out of affordable health care options in the past have those options available to them."
}
--message_boundary_0001--

but I don't know how to convert it to requests code.

## Expected Result
python3 requests library should be able to post above data. the main difficulty is there's special Content-Disposition.
Content-Disposition: form-data; name="RequestData"
Content-Disposition: form-data; name="TtsParameter"; **paramName**="TEXT_TO_READ"

please note the second one is called 'paramName', instead of 'filename', which can be solved by another solved issue: _Can't set headers per part of multipart requests_ 
 https://github.com/requests/requests/issues/1495

## What you expected.
Some python code sample to convert my curl data.

## Actual Result
my code not work. always got 403, or connection timeout error.

## Reproduction Steps
Since I'm in private network you cannot debug directly.

`import requests
from requests_toolbelt import MultipartEncoder

RequestData = '''{
    "appKey": "525348e77144a9cee9a7471a8b67c50ea85b9e3eb377a3c1a3a23db88f9150eefe76e6a339fdbc62b817595f53d72549d9ebe36438f8c2619846b963e9f43a93",
    "appId": "SAMPLE_DEBUG_NMAID_TO_BE_REPLACED",
    "outCodec": "OPUS_16K",
    "cmdName": "NVC_TTS_CMD",  
    "cmdDict": {
        "tts_language":"eng-USA",
        "tts_voice":"ava-ml",
    "supportedTtsFeature":{
            "tts_multi_logic_stream_flag": "true",
            "tts_early_emission_flag": "true"
        }  
    }
}'''

TtsParameter_TEXT_TO_READ = '''{
   "tts_type": "native_text",
   "tts_input":"9 The result will be millions of Americans who have insurance who did not have it before.
"
}'''

multipart_data = MultipartEncoder(
    fields={
        'RequestData': (None, RequestData, 'application/json; charset=utf-8'),
        'TtsParameter': ('TEXT_TO_READ', TtsParameter_TEXT_TO_READ, 'application/json; charset=utf-8')

    }
)

#url = 'https://httpbin.org/post'
url = 'http://10.3.65.142:21857/NmspServlet/'

headers = {
    'Accept': 'audio/ogg;codecs=opus;',
    'Connection': 'keep-alive'
}

resp = requests.post(url,
                     data=multipart_data,
                     headers=headers,
                     timeout=6)
print(resp.status_code)
print(resp.content.decode('utf-8'))
#requests.exceptions.ReadTimeout`

 
## System Information
Windows 10, python3.6

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

You already have a question on StackOverflow so please be patient. Cross-posting here is not productive.
