### ISSUE TITLE
About the difference of requests.get and requests.session().get

### ISSUE THREAD

**Issue by zhongxinghong** [requests/requests#4952]
Hai ! In your `api.py` file, the function `get` declare the para `params`, and assign a default value to it, then we can use the `get` func like `requests.get(url, {"k1":"v1", "k2":"v2"})` without pointing out the key `params` of the second para. But in your `sessions.py` file, the method `get` of the class `Session` didn't declare the para `params`, so we must use the `Session.get` method like `s.get(url, params={"k1":"v1", "k2":"v2"})`, or it will raise a TypeError `TypeError: get() takes 2 positional arguments but 3 were given`. I checked all request methods defined under the class `Session` and all requests API in the `api.py` file, and found that only the `get` method has this little difference. It used to bother me. Could you please eliminate this little difference? :) Good Luck !

**Comment by sigmavirus24** [comment]
I don't think this warrants an update. Keyword parameters are better and as soon as we can get on Python 3 only I think we should switch everything except URL to be a keyword-only parameter. This just nudges people in the right direction sooner. We could, however, make `params` be a keyword argument in the functional API but that'd be backwards incompatible so we won't do that either.
