### ISSUE TITLE
Unable to call API on a system using unsigned SSL cert

### ISSUE THREAD

**Issue by espressobeanies** [requests/requests#4953]
I'm not able to call an API on a system using an unsigned SSL certificate

## Expected Result

JSON output data

## Actual Result

`requests.exceptions.SSLError: HTTPSConnectionPool(host='apitest.internal', port=443): Max retries exceeded with url: /login/oauth2/token (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)')`,))

## Reproduction Steps

```python
from oauthlib.oauth2 import BackendApplicationClient
from requests.auth import HTTPBasicAuth
from requests_oauthlib import OAuth2Session
import requests, json

def client_credentials(client_id, client_secret, token_uri):
    auth = HTTPBasicAuth(client_id, client_secret)
    client = BackendApplicationClient(client_id=client_id)
    oauth = OAuth2Session(client=client)
    token = oauth.fetch_token(token_url=token_uri, auth=auth)
    return token

storecreds=client_credentials(client_id, client_secret, token_uri)
print(storecreds)
```

## System Information

    $ python3 -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.7"
  },
  "platform": {
    "release": "4.15.0-43-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.20.0"
  },
  "system_ssl": {
    "version": "1010007f"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": false
}
```

**Comment by espressobeanies** [comment]
Same issue if I install pyOpenSSL and upgrade PIP to 18.0

`{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.5"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.7"
  },
  "platform": {
    "release": "4.15.0-43-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010101f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.20.0"
  },
  "system_ssl": {
    "version": "1010007f"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": true
}`

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
