### ISSUE TITLE
requests.post taking integer as string

### ISSUE THREAD

**Issue by amruizva** [requests/requests#4955]
There is something I am not able to understand using the **requests.post** method,

Having this set of parameters, the requests.post works perfect.

params = {
        "profiles":  123456789, 
        "date_start":  2019-01-01,
        "date_end": 2019-01-10,
        "fields": [
            "attachments",
            "author_id",
            "comments",
            "created_time",
            "id",
            "interactions",
            "likes",
            "message",
            "post_labels",
            "type",
            "insights_engagement",
            "insights_impressions", 
            "insights_reach", 
            "insights_saved", 
            "insights_video_views", 
            "url"
            ],   
        }

However, when I add a key as an **integer**, I am getting a response that is taken as a **string**

Here is the example adding the new key: 

params = {
        "profiles":  123456789, 
        "date_start":  2019-01-01,
        "date_end": 2019-01-10,
        "fields": [
            "attachments",
            "author_id",
            "comments",
            "created_time",
            "id",
            "interactions",
            "likes",
            "message",
            "post_labels",
            "type",
            "insights_engagement",
            "insights_impressions", 
            "insights_reach", 
            "insights_saved", 
            "insights_video_views", 
            "url"
            ],  
            "limit": 500
        }

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
