### ISSUE TITLE
Exception when calling 'merge_environment_settings' as documented

### ISSUE THREAD

**Issue by andrewbonney** [requests/requests#4959]
When calling `merge_environment_settings` as documented in http://docs.python-requests.org/en/master/user/advanced/#prepared-requests an exception occurs. There appears to be a conflict between the code and the documentation.

## Expected Result

Calling `merge_environment_settings` on a Session object with 'None' in all arguments except the first proceeds without error.

## Actual Result

An exception occurs: `'NoneType' object has no attribute 'setdefault'`. This is caused by https://github.com/requests/requests/blob/eaab47f033cae3bd443abb6707dfc30ae3482c36/requests/sessions.py#L702 when the 'proxies' argument is set to 'None'.

## Reproduction Steps

As-per the documentation example
```python
from requests import Request, Session

s = Session()
url = "https://google.com"
req = Request('GET', url)
prepped = s.prepare_request(req)
settings = s.merge_environment_settings(prepped.url, None, None, None, None)
```

## System Information
```
Python 3.5
Requests 2.9.1
Ubuntu Xenial
```

**Comment by sigmavirus24** [comment]
Yes, the documentation is out of date. I'd be happy to merge a pull request that updates it.
