### ISSUE TITLE
Requests.get producing different JSON than curl

### ISSUE THREAD

**Issue by OpSecIsSexy** [requests/requests#4962]
When making a get request requests.get and curl, the returned JSON object is identical in every way, except with requests.get leading digits in an "id":# kv pair are omitted.

## Expected Result

cURL and requests.get returned JSON objects should be identical

## Actual Result

requests.get returns
`"id":12345`

Whereas curl returns
`"id":10000000000012345`

## Reproduction Steps

```python
import requests
HEADERS = {'Authorization': f'Bearer {args.api_key}'}
API_URL = f'https://canvas.instructure.com/api/v1'
STUDENT = requests.get(f'{API_URL}/courses/', params=None, headers=HEADERS)

studnetlst = STUDENT.json()
print(studnetlst)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.2"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "101000af"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": false
}
```

More info: https://stackoverflow.com/questions/54527648/pythons-requests-get-producing-different-json-than-api-client

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Can you share the relevant bit from `STUDENT.content`?

**Comment by MikeFindsThings** [comment]
`STUDENT.content`:

`b'[{"id":12345,"name":"Class1","account_id":188,"uuid":"itsadifferentsecret","start_at":"2019-01-13T17:33:04Z","grading_standard_id":null}]'`

the desired result should look like:

`b'[{"id":10000000000012345,"name":"Class1","account_id":188,"uuid":"itsadifferentsecret","start_at":"2019-01-13T17:33:04Z","grading_standard_id":null}]'`

**Comment by sigmavirus24** [comment]
So this shows that Canvas is responding with incorrect data. Literally the bytes we receive from the server do no thave the digits you're looking for and there's nothing Requests can do.

Often times, this is the result of the server introspecting user-agent headers so I suspect you try sending a different one.

Cheers,
Ian

**Comment by MikeFindsThings** [comment]
But if I change the user-agent to the same as one that runs successfully I have the same problem.

**Comment by MikeFindsThings** [comment]
@sigmavirus24 does adding `'User-Agent': 'adifferentagent'` actually change the header? From captured frames in Wireshark it appears to, just checking my understanding.
