### ISSUE TITLE
phython error

### ISSUE THREAD

**Issue by achyuthachu** [requests/requests#4964]
Summary.

## Expected Result
output should run without any error or exception

What you expected.

## Actual Result

Can please resolve this issue??
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

  self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x02D87DB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

**Comment by sigmavirus24** [comment]
This is not a Requests bug.
